### ISSUE TITLE
[ERROR] UnauthorizedAccessException

### ISSUE THREAD

**Issue by Dantez1609** [bloxstraplabs/bloxstrap#2892]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Good afternoon, please tell me. This error occurred when reinstalling bloxstrap.
System.UnauthorizedAccessException: Access to the path 'C:\Users\ADCC~1\AppData\Local\Temp\Rar$EXa576.30260\Logs' is denied.
--
2024-09-14T20:29:16Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-09-14T20:29:16Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 9:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-09-14T20:29:16Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.7.0 (1).exe
2024-09-14T20:29:16Z [LaunchSettings::Parse] Parsing launch arguments
2024-09-14T20:29:16Z [LaunchSettings::Parse] No launch arguments to parse
2024-09-14T20:29:16Z [InstallChecker::Check] Could not find install location. Checking if drive has changed...
2024-09-14T20:29:16Z [InstallChecker::Check] Drive has not changed, folder was likely moved or deleted
2024-09-14T20:29:16Z [JsonManager<Settings>::Load] Loading from C:\Users\ADCC~1\AppData\Local\Temp\Rar$EXa576.30260\Settings.json...
2024-09-14T20:29:16Z [JsonManager<Settings>::Load] Failed to load!
2024-09-14T20:29:16Z [JsonManager<Settings>::Load] Could not find a part of the path 'C:\Users\ADCC~1\AppData\Local\Temp\Rar$EXa576.30260\Settings.json'.
2024-09-14T20:29:16Z [JsonManager<State>::Load] Loading from C:\Users\ADCC~1\AppData\Local\Temp\Rar$EXa576.30260\State.json...
2024-09-14T20:29:16Z [JsonManager<State>::Load] Failed to load!
2024-09-14T20:29:16Z [JsonManager<State>::Load] Could not find a part of the path 'C:\Users\ADCC~1\AppData\Local\Temp\Rar$EXa576.30260\State.json'.
2024-09-14T20:29:16Z [JsonManager<Dictionary`2>::Load] Loading from C:\Users\ADCC~1\AppData\Local\Temp\Rar$EXa576.30260\Modifications\ClientSettings\ClientAppSettings.json...
2024-09-14T20:29:16Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-09-14T20:29:16Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path 'C:\Users\ADCC~1\AppData\Local\Temp\Rar$EXa576.30260\Modifications\ClientSettings\ClientAppSettings.json'.
2024-09-14T20:29:16Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-09-14T20:29:16Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-09-14T20:29:16Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-09-14T20:29:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-09-14T20:29:16Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-09-14T20:29:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-09-14T20:29:16Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-09-14T20:29:16Z [Logger::Initialize] Initializing at C:\Users\ADCC~1\AppData\Local\Temp\Rar$EXa576.30260\Logs\Bloxstrap_20240914T202916Z.log
2024-09-14T20:29:16Z [App::GlobalExceptionHandler] An exception occurred
2024-09-14T20:29:16Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'C:\Users\ADCC~1\AppData\Local\Temp\Rar$EXa576.30260\Logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

### Bloxstrap Log

N/A

**Comment by NabHeyka22** [comment]
https://github.com/pizzaboxer/bloxstrap/wiki/"Access-to-the-path-is-denied"-or-"An-error-occurred-trying-to-start-process"-regarding-RobloxPlayerBeta.exe

**Comment by Dantez1609** [comment]
I created another user and everything works but it doesn’t work for this user, tell me how to solve this problem?

**Comment by NabHeyka22** [comment]
i'm just going to explain this to you since you didn't read it
you have an antivirus and is blocking bloxstrap
solution is to add an exception or disable it

**Comment by Dantez1609** [comment]
![image](https://github.com/user-attachments/assets/5c827d4e-a00f-44cd-8387-258b02684ce7)

**Comment by Dantez1609** [comment]
Не помогает, я читал и ознакомился с материалом прежде чем писать

**Comment by NabHeyka22** [comment]
sorry i don't speak russian
try to disable the antivirus

**Comment by Dantez1609** [comment]
I apologize, I added this file to the list earlier so that it would not be blocked, I read and became familiar with the material before asking for help. It’s quite strange that on another PC user, everything works fine and installed quickly. In this user it gives this error

**Comment by Dantez1609** [comment]
As I understand it, the installer is trying to find the ADCC~1 user, but I don't have such a user.

**Comment by bluepilledgreat** [comment]
how did you even manage to install in the winrar temp directory

**Comment by pizzaboxer** [comment]
To fix this, you'll need to open the Registry Editor and delete the `InstallLocation` key at `HKEY_CURRENT_USER\SOFTWARE\Bloxstrap` (better described [here](https://github.com/pizzaboxer/bloxstrap/wiki/Bloxstrap-stops-working-after-renaming-the-user-profile-folder)). Afterwards, reinstall it as normal.
