### ISSUE TITLE
bloxstrap

### ISSUE THREAD

**Issue by soverycool201** [bloxstraplabs/bloxstrap#3105]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

it shows an eeror
![SharedScreenshot](https://github.com/user-attachments/assets/b62d96b7-9956-4ea9-b34c-9bb384438d72)

### Bloxstrap Log

2024-10-09T11:44:13Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-10-09T11:44:13Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 9:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-10-09T11:44:13Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-09T11:44:13Z [LaunchSettings::Parse] Parsing launch arguments
2024-10-09T11:44:13Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-09T11:44:13Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-09T11:44:13Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-09T11:44:13Z [JsonManager<State>::Load] Loaded successfully!
2024-10-09T11:44:13Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-09T11:44:13Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-10-09T11:44:13Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-10-09T11:44:13Z [JsonManager<State>::Save] Save request ignored
2024-10-09T11:44:13Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-10-09T11:44:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-10-09T11:44:13Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-10-09T11:44:14Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-10-09T11:44:14Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-09T11:44:14Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241009T114414Z.log
2024-10-09T11:44:14Z [Logger::Initialize] Finished initializing!
2024-10-09T11:44:14Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-10-09T11:44:14Z [App::OnStartup] Initializing bootstrapper
2024-10-09T11:44:14Z [App::OnStartup] Initializing bootstrapper dialog
2024-10-09T11:44:14Z [Bootstrapper::Run] Running bootstrapper
2024-10-09T11:44:14Z [Bootstrapper::Run] Performing connectivity check...
2024-10-09T11:44:14Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-09T11:44:14Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-09T11:44:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-09T11:44:14Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-09T11:44:14Z [Bootstrapper::Run] Connectivity check finished
2024-10-09T11:44:14Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-09T11:44:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-10-09T11:44:14Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repositories/520583586/releases/latest
2024-10-09T11:44:14Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-09T11:44:14Z [RobloxDeployment::GetInfo] Getting deploy info for channel zflag (extraInformation=False)
2024-10-09T11:44:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zflag
2024-10-09T11:44:14Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zflag
2024-10-09T11:44:14Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-09T11:44:14Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-10-09T11:44:14Z [RobloxFastFlags::Fetch.PCClientBootstrapper.zflag] Fetching fast flags
2024-10-09T11:44:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zflag
2024-10-09T11:44:14Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zflag
2024-10-09T11:44:14Z [App::OnStartup] Bootstrapper task has finished
2024-10-09T11:44:14Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-10-09T11:44:14Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-10-09T11:44:14Z [App::OnStartup] System.AggregateException: One or more errors occurred. (One or more errors occurred. (Deserialised application settings is null!))
 ---> System.AggregateException: One or more errors occurred. (Deserialised application settings is null!)
 ---> System.Exception: Deserialised application settings is null!
   at Bloxstrap.RobloxFastFlags.Fetch()
   at Bloxstrap.RobloxFastFlags.GetAsync[T](String name)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Bloxstrap.RobloxFastFlags.Get[T](String name)
   at Bloxstrap.RobloxDeployment.GetLocation(String resource, String channel)
   at Bloxstrap.Models.Manifest.PackageManifest.Get(String versionGuid)
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass38_0.<<OnStartup>b__0>d.MoveNext()
   --- End of inner exception stack trace ---

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/%22Deserialised-application-settings-is-null!%22-when-launching-Roblox
