### ISSUE TITLE
Bloxstrap exception occured

### ISSUE THREAD

**Issue by ziggyboop** [bloxstraplabs/bloxstrap#3109]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![Screenshot 2024-10-09 145537](https://github.com/user-attachments/assets/e0a430e4-be73-48e7-a1c7-29de77b3d9b2)
[Bloxstrap_20241009T125231Z.log](https://github.com/user-attachments/files/17308543/Bloxstrap_20241009T125231Z.log)

I get this error whenever i try to access roblox with bloxstrap. How do i make this go away?

### Bloxstrap Log

2024-10-09T12:52:31Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-10-09T12:52:31Z [App::OnStartup] Compiled Tuesday, 9 July 2024 at 8:03:19 PM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-10-09T12:52:31Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-09T12:52:31Z [LaunchSettings::Parse] Parsing launch arguments
2024-10-09T12:52:31Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-09T12:52:31Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-09T12:52:31Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-09T12:52:31Z [JsonManager<State>::Load] Loaded successfully!
2024-10-09T12:52:31Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-09T12:52:31Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-10-09T12:52:31Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-10-09T12:52:31Z [ProtocolHandler::ChangeChannel] Changed Roblox channel from LIVE to zout-of-memory-fixes
2024-10-09T12:52:31Z [JsonManager<State>::Save] Save request ignored
2024-10-09T12:52:31Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-10-09T12:52:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-10-09T12:52:31Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-10-09T12:52:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-10-09T12:52:31Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-09T12:52:31Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241009T125231Z.log
2024-10-09T12:52:31Z [Logger::Initialize] Finished initializing!
2024-10-09T12:52:31Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-10-09T12:52:31Z [App::OnStartup] Initializing bootstrapper
2024-10-09T12:52:31Z [App::OnStartup] Initializing bootstrapper dialog
2024-10-09T12:52:32Z [Bootstrapper::Run] Running bootstrapper
2024-10-09T12:52:32Z [Bootstrapper::Run] Performing connectivity check...
2024-10-09T12:52:32Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-09T12:52:32Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-09T12:52:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-09T12:52:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-09T12:52:32Z [Bootstrapper::Run] Connectivity check finished
2024-10-09T12:52:32Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-09T12:52:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/pizzaboxer/bloxstrap/releases/latest
2024-10-09T12:52:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repositories/520583586/releases/latest
2024-10-09T12:52:32Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-09T12:52:32Z [RobloxDeployment::GetInfo] Getting deploy info for channel zout-of-memory-fixes (extraInformation=False)
2024-10-09T12:52:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zout-of-memory-fixes
2024-10-09T12:52:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zout-of-memory-fixes
2024-10-09T12:52:32Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-09T12:52:32Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-10-09T12:52:32Z [RobloxFastFlags::Fetch.PCClientBootstrapper.zout-of-memory-fixes] Fetching fast flags
2024-10-09T12:52:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zout-of-memory-fixes
2024-10-09T12:52:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zout-of-memory-fixes
2024-10-09T12:52:32Z [App::OnStartup] Bootstrapper task has finished
2024-10-09T12:52:32Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-10-09T12:52:32Z [App::OnStartup] An exception occurred when running the bootstrapper
2024-10-09T12:52:32Z [App::OnStartup] System.AggregateException: One or more errors occurred. (One or more errors occurred. (Deserialised application settings is null!))
 ---> System.AggregateException: One or more errors occurred. (Deserialised application settings is null!)
 ---> System.Exception: Deserialised application settings is null!
   at Bloxstrap.RobloxFastFlags.Fetch()
   at Bloxstrap.RobloxFastFlags.GetAsync[T](String name)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Bloxstrap.RobloxFastFlags.Get[T](String name)
   at Bloxstrap.RobloxDeployment.GetLocation(String resource, String channel)
   at Bloxstrap.Models.Manifest.PackageManifest.Get(String versionGuid)
   at Bloxstrap.Bootstrapper.CheckLatestVersion()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.App.<>c__DisplayClass38_0.<<OnStartup>b__0>d.MoveNext()
   --- End of inner exception stack trace ---
2024-10-09T12:56:56Z [App::Terminate] Terminating with exit code 1603 (ERROR_INSTALL_FAILURE)
2024-10-09T12:56:56Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-09T12:56:56Z [JsonManager<Settings>::Save] Save complete!
2024-10-09T12:56:56Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-09T12:56:56Z [JsonManager<State>::Save] Save complete!

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/%22Deserialised-application-settings-is-null!%22-when-launching-Roblox
