### ISSUE TITLE
[BUG] install bloxstrap bugs

### ISSUE THREAD

**Issue by abcd68316** [bloxstraplabs/bloxstrap#3134]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I was uninstall the bloxstrap and i wanna install it today,but i was change the username before,and it says it can not find logs or something.
![image](https://github.com/user-attachments/assets/be5028d9-2743-46fe-8b13-c2b232ee65d2)

### Bloxstrap Log

2024-10-13T14:13:09Z [App::OnStartup] Starting Bloxstrap v2.7.0
2024-10-13T14:13:09Z [App::OnStartup] Compiled Wednesday, 10 July 2024 at 2:03:19 AM from commit a7d2a2c3d5af7137804416ba4e5fbdd27bd10f1e (tag/v2.7.0)
2024-10-13T14:13:09Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.7.0.exe
2024-10-13T14:13:09Z [LaunchSettings::Parse] Parsing launch arguments
2024-10-13T14:13:09Z [LaunchSettings::Parse] No launch arguments to parse
2024-10-13T14:13:09Z [InstallChecker::Check] Could not find install location. Checking if drive has changed...
2024-10-13T14:13:09Z [InstallChecker::Check] Drive has not changed, folder was likely moved or deleted
2024-10-13T14:13:09Z [JsonManager<Settings>::Load] Loading from C:\Users\黄毓铭\AppData\Local\Bloxstrap\Settings.json...
2024-10-13T14:13:09Z [JsonManager<Settings>::Load] Failed to load!
2024-10-13T14:13:09Z [JsonManager<Settings>::Load] Could not find a part of the path 'C:\Users\黄毓铭\AppData\Local\Bloxstrap\Settings.json'.
2024-10-13T14:13:09Z [JsonManager<State>::Load] Loading from C:\Users\黄毓铭\AppData\Local\Bloxstrap\State.json...
2024-10-13T14:13:09Z [JsonManager<State>::Load] Failed to load!
2024-10-13T14:13:09Z [JsonManager<State>::Load] Could not find a part of the path 'C:\Users\黄毓铭\AppData\Local\Bloxstrap\State.json'.
2024-10-13T14:13:09Z [JsonManager<Dictionary`2>::Load] Loading from C:\Users\黄毓铭\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-13T14:13:09Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-10-13T14:13:09Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path 'C:\Users\黄毓铭\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json'.
2024-10-13T14:13:09Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-10-13T14:13:09Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-13T14:13:09Z [RobloxDeployment::TestConnection.https://setup.rbxcdn.com] Connecting...
2024-10-13T14:13:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-10-13T14:13:09Z [RobloxDeployment::InitializeConnectivity] Testing connectivity...
2024-10-13T14:13:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-10-13T14:13:11Z [RobloxDeployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-13T14:13:11Z [Logger::Initialize] Initializing at C:\Users\黄毓铭\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241013T141311Z.log
2024-10-13T14:13:11Z [App::GlobalExceptionHandler] An exception occurred
2024-10-13T14:13:11Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'C:\Users\黄毓铭\AppData\Local\Bloxstrap\Logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by NabHeyka22** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/"Access-to-the-path-is-denied"-or-"An-error-occurred-trying-to-start-process"-regarding-RobloxPlayerBeta.exe

**Comment by pizzaboxer** [comment]
When you changed your username, did you also rename your user profile folder?

**Comment by abcd68316** [comment]
> When you changed your username, did you also rename your user profile folder?

yes because my old folder is unenglish folder so i changed it

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/Bloxstrap-stops-working-after-renaming-the-user-profile-folder

To do a fresh reinstall, delete the 'InstallLocation' key.
