### ISSUE TITLE
[BUG] System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by TaxRBX** [bloxstraplabs/bloxstrap#3193]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I'm trying to use the latest version of Bloxstrap but doesn't open for some reason, I also check the version of windowsdesk but the main problem stands still. Pls I need help for fix this

### Bloxstrap Log

2024-10-16T21:29:40Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-16T21:29:40Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 6:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-16T21:29:40Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.0.exe
2024-10-16T21:29:40Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-16T21:29:40Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-16T21:29:40Z [Logger::Initialize] Initializing at %UserProfile%\Downloads\Bloxstrap\Logs\Bloxstrap_20241016T212940Z.log
2024-10-16T21:29:40Z [Logger::Initialize] Finished initializing!
2024-10-16T21:29:40Z [JsonManager<Settings>::Load] Loading from %UserProfile%\Downloads\Bloxstrap\Settings.json...
2024-10-16T21:29:40Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-16T21:29:40Z [JsonManager<State>::Load] Loading from %UserProfile%\Downloads\Bloxstrap\State.json...
2024-10-16T21:29:40Z [JsonManager<State>::Load] Loaded successfully!
2024-10-16T21:29:40Z [FastFlagManager::Load] Loading from %UserProfile%\Downloads\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-16T21:29:40Z [FastFlagManager::Load] Loaded successfully!
2024-10-16T21:29:40Z [App::GlobalExceptionHandler] An exception occurred
2024-10-16T21:29:40Z [App::FinalizeExceptionHandling] System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Version.TryParseComponent(ReadOnlySpan`1 component, String componentName, Boolean throwOnFailure, Int32& parsedComponent)
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Bloxstrap.Utilities.CompareVersions(String versionStr1, String versionStr2)
   at Bloxstrap.Installer.HandleUpgrade()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by pizzaboxer** [comment]
What's your system locale set to?

**Comment by TaxRBX** [comment]
Idk how to see that

**Comment by TaxRBX** [comment]
Did you know how?

**Comment by lilzulyy89** [comment]
bloxstrap bugging fr

**Comment by TaxRBX** [comment]
I see it, it's from Argentina the format

**Comment by pizzaboxer** [comment]
You'll likely need to reinstall Bloxstrap fresh to get around this problem for now

**Comment by TaxRBX** [comment]
I just need to follow the steps of how to unistall Bloxstrap and reinstall it again right?

**Comment by pizzaboxer** [comment]
If you're still there, would you be able to help me test a fix?
