### ISSUE TITLE
[BUG] System.AggregateException cant run roblox with bloxstrap

### ISSUE THREAD

**Issue by RicardomanV1** [bloxstraplabs/bloxstrap#3201]
### What problem did you encounter?

Every time I try to run roblox with bloxstrap i get this error: System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.

### Bloxstrap Log

2024-10-16T21:48:49Z [App::OnStartup] Starting Bloxstrap v2.5.3
2024-10-16T21:48:49Z [App::OnStartup] Compiled Tuesday, 18 June 2024 at 12:39:08 PM from DESKTOP-FGF6DO8\User
2024-10-16T21:48:49Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-16T21:48:49Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241016T214849Z.log
2024-10-16T21:48:49Z [Logger::Initialize] Finished initializing!
2024-10-16T21:48:49Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-16T21:48:49Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-16T21:48:49Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-16T21:48:49Z [JsonManager<State>::Load] Loaded successfully!
2024-10-16T21:48:49Z [JsonManager<Dictionary`2>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-16T21:48:49Z [JsonManager<Dictionary`2>::Load] Loaded successfully!
2024-10-16T21:48:49Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-10-16T21:48:49Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-10-16T21:48:49Z [JsonManager<State>::Save] Save request ignored
2024-10-16T21:48:49Z [App::OnStartup] Initializing bootstrapper
2024-10-16T21:48:49Z [App::OnStartup] Initializing bootstrapper dialog
2024-10-16T21:48:49Z [App::OnStartup] Creating singleton mutex
2024-10-16T21:48:49Z [Bootstrapper::Run] Running bootstrapper
2024-10-16T21:48:49Z [Bootstrapper::Run] Performing connectivity check...
2024-10-16T21:48:49Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-16T21:48:49Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-16T21:48:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-16T21:48:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-16T21:48:49Z [Bootstrapper::Run] Connectivity check finished
2024-10-16T21:48:49Z [RobloxDeployment::GetInfo] Getting deploy info for channel Live (extraInformation=False)
2024-10-16T21:48:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/Live
2024-10-16T21:48:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/Live
2024-10-16T21:48:49Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-16T21:48:49Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-10-16T21:48:49Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-10-16T21:48:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-10-16T21:48:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-10-16T21:48:50Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-10-16T21:48:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-16T21:48:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-16T21:48:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxManifest.txt
2024-10-16T21:48:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxManifest.txt
2024-10-16T21:48:50Z [Bootstrapper::SetStatus] Upgrading Roblox...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\avatar\...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\configs\...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\fonts\...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\models\...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\sky\...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\sounds\...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\shaders\...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ssl\...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\textures\...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\PlatformContent\pc\textures\...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\PlatformContent\pc\terrain\...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\PlatformContent\pc\fonts\...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ExtraContent\places\...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ExtraContent\LuaPackages\...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ExtraContent\translations\...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ExtraContent\models\...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ExtraContent\textures\...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1...
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-10-16T21:48:50Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting redist.zip'
2024-10-16T21:48:50Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-16T21:48:50Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-16T21:48:51Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-16T21:48:51Z [Bootstrapper::SetStatus] Configuring Roblox...

**Comment by bluepilledgreat** [comment]
Update to 2.8.0.
