### ISSUE TITLE
[BUG] an exception occured while running bloxstrap

### ISSUE THREAD

**Issue by DripzHitYaWitDatFye** [bloxstraplabs/bloxstrap#3223]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/71ada455-b946-48f0-9522-7390ed272a8c)

### Bloxstrap Log

2024-10-17T00:37:24Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-17T00:37:24Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 5:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-17T00:37:24Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-17T00:37:24Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-17T00:37:24Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-17T00:37:24Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241017T003724Z.log
2024-10-17T00:37:24Z [Logger::Initialize] Finished initializing!
2024-10-17T00:37:24Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-17T00:37:24Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-17T00:37:24Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-17T00:37:24Z [JsonManager<State>::Load] Loaded successfully!
2024-10-17T00:37:24Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-17T00:37:24Z [FastFlagManager::Load] Loaded successfully!
2024-10-17T00:37:26Z [MainWindow] Initializing settings window
2024-10-17T00:37:37Z [Frontend::ShowMessageBox] You appear to be importing a very large configuration. You should only be importing configurations that you fully understand. Do NOT blindly paste in configurations made by other people. If you continue, you will very likely end up with stability issues and encounter unexpected changes.

Are you sure you want to continue?
2024-10-17T00:37:38Z [Frontend::ShowMessageBox] Some of the flags you are attempting to import already have set values. Would you like to overwrite their current values with the ones defined in the import?

There are 17 conflicting flag definitions:
FFlagDisablePostFx, DFIntConnectionMTUSize, FFlagDebugDisableTelemetryEventIngest, FFlagDebugSkyGray, FFlagNewLightAttenuation, FFlagDebugDisableTelemetryPoint, DFFlagTextureQualityOverrideEnabled, FFlagFastGPULightCulling3, FFlagDebugDisableTelemetryEphemeralCounter, FFlagDebugDisableTelemetryV2Stat, FFlagDebugDisableTelemetryV2Counter, DFIntClientLightingTechnologyChangedTelemetryHundredthsPercent, FFlagDebugDisableTelemetryEphemeralStat, FFlagDebugDisableTelemetryV2Event, FFlagDebugDisplayFPS, FIntFullscreenTitleBarTriggerDelayMillis, DFIntTextureQualityOverride
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Setting of 'DFIntDebugFRMQualityLevelOverride' to '1' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'DFFlagTextureQualityOverrideEnabled' from 'True' to 'True' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'DFIntTextureQualityOverride' from '3' to '3' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'DFIntConnectionMTUSize' from '900' to '900' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'FFlagDebugDisableTelemetryEphemeralCounter' from 'True' to 'True' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'FFlagDebugDisableTelemetryEphemeralStat' from 'True' to 'True' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'FFlagDebugDisableTelemetryEventIngest' from 'True' to 'True' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'FFlagDebugDisableTelemetryPoint' from 'True' to 'True' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'FFlagDebugDisableTelemetryV2Counter' from 'True' to 'True' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'FFlagDebugDisableTelemetryV2Event' from 'True' to 'True' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'FFlagDebugDisableTelemetryV2Stat' from 'True' to 'True' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'FFlagDebugSkyGray' from 'True' to 'true' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Changing of 'FFlagDebugDisplayFPS' from 'False' to 'True' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Setting of 'FIntFRMMinGrassDistance' to '0' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Setting of 'FIntFRMMaxGrassDistance' to '0' is pending
2024-10-17T00:37:41Z [FastFlagManager::SetValue] Setting of 'FIntRenderGrassDetailStrands' to '0' is pending
2024-10-17T00:37:41Z [Frontend::ShowMessageBox] The entry for 'FintRenderGrassHeightScaler' is not valid as the name must start with FFlag, DFInt, etc
2024-10-17T00:37:48Z [FastFlagManager::SetValue] Setting of 'DFIntMaxFrameBufferSize' to '4' is pending
2024-10-17T00:37:48Z [Frontend::ShowMessageBox] The entry for 'DebugGraphicsDisableVulkan' is not valid as the name must start with FFlag, DFInt, etc
2024-10-17T00:37:52Z [Frontend::ShowMessageBox] The entry for 'DebugGraphicsDisableVulkan11' is not valid as the name must start with FFlag, DFInt, etc
2024-10-17T00:37:53Z [Frontend::ShowMessageBox] The entry for 'DebugGraphicsDisableOpenGL' is not valid as the name must start with FFlag, DFInt, etc
2024-10-17T00:37:53Z [Frontend::ShowMessageBox] The entry for 'DebugGraphicPreferD3D11' is not valid as the name must start with FFlag, DFInt, etc
2024-10-17T00:37:54Z [FastFlagManager::SetValue] Setting of 'FIntRobloxGuiBlurIntensity' to '0' is pending
2024-10-17T00:37:54Z [FastFlagManager::SetValue] Changing of 'FIntFullscreenTitleBarTriggerDelayMillis' from '3600000' to '18000000' is pending
2024-10-17T00:37:54Z [FastFlagManager::SetValue] Changing of 'FFlagFastGPULightCulling3' from 'True' to 'True' is pending
2024-10-17T00:37:54Z [FastFlagManager::SetValue] Changing of 'FFlagNewLightAttenuation' from 'True' to 'True' is pending
2024-10-17T00:37:54Z [FastFlagManager::SetValue] Changing of 'FFlagDisablePostFx' from 'True' to 'True' is pending
2024-10-17T00:37:54Z [FastFlagManager::SetValue] Changing of 'DFIntClientLightingTechnologyChangedTelemetryHundredthsPercent' from '0' to '0' is pending
2024-10-17T00:37:54Z [FastFlagManager::SetValue] Setting of 'DFIntClientLightingEnvmapPlacementTelemetryHundredthsPercent' to '100' is pending
2024-10-17T00:37:54Z [FastFlagManager::SetValue] Setting of 'FIntMockClientLightingTechnologyIxpExperimentMode' to '0' is pending
2024-10-17T00:37:54Z [FastFlagManager::SetValue] Setting of 'FIntMockClientLightingTechnologyIxpExperimentQualityLevel' to '7' is pending
2024-10-17T00:38:04Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-17T00:38:04Z [JsonManager<Settings>::Save] Save complete!
2024-10-17T00:38:04Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-17T00:38:04Z [JsonManager<State>::Save] Save complete!
2024-10-17T00:38:04Z [FastFlagManager::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-17T00:38:04Z [FastFlagManager::Save] Save complete!
2024-10-17T00:38:41Z [Frontend::ShowMessageBox] Test mode makes it easier to iteratively test how your settings affect Roblox. 

While enabled, it will automatically launch Roblox after closing Settings, and reopen Settings after closing Roblox, in a cycle until you disable it.

Would you like to enable test mode?
2024-10-17T00:38:43Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-17T00:38:43Z [JsonManager<Settings>::Save] Save complete!
2024-10-17T00:38:43Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-17T00:38:43Z [JsonManager<State>::Save] Save complete!
2024-10-17T00:38:43Z [FastFlagManager::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-17T00:38:43Z [FastFlagManager::Save] Save complete!
2024-10-17T00:38:44Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-17T00:38:44Z [JsonManager<State>::Save] Save complete!
2024-10-17T00:38:44Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-17T00:38:44Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-17T00:38:44Z [Bootstrapper::Run] Running bootstrapper
2024-10-17T00:38:44Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-17T00:38:44Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-17T00:38:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-17T00:38:44Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-17T00:38:45Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-17T00:38:45Z [Bootstrapper::Run] Connectivity check finished
2024-10-17T00:38:45Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-17T00:38:45Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-17T00:38:45Z [Bootstrapper::GetLatestVersionInfo] Got channel as zaomarpcregressiontestcurrent
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zaomarpcregressiontestcurrent
2024-10-17T00:38:45Z [Deployment::GetInfo] Getting deploy info for channel zaomarpcregressiontestcurrent
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zaomarpcregressiontestcurrent
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zaomarpcregressiontestcurrent
2024-10-17T00:38:45Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-17T00:38:45Z [RegistryKeyEx::SetValueSafe] Writing 'zaomarpcregressiontestcurrent' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-17T00:38:45Z [ApplicationSettings::Fetch.PCClientBootstrapper.zaomarpcregressiontestcurrent] Fetching fast flags
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zaomarpcregressiontestcurrent
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zaomarpcregressiontestcurrent
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-17T00:38:45Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-10-17T00:38:45Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zaomarpcregressiontestcurrent
2024-10-17T00:38:45Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-10-17T00:38:45Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-17T00:38:45Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-17T00:38:45Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-17T00:38:45Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-10-17T00:38:45Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-17T00:38:45Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-17T00:38:45Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-17T00:38:45Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-17T00:38:45Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-17T00:38:45Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-17T00:38:45Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-17T00:38:45Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-10-17T00:38:46Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-17T00:38:46Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-17T00:38:47Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-17T00:38:47Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-17T00:38:48Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-17T00:38:48Z [Bootstrapper::UpgradeRoblox] Writing AppSettings.xml...
2024-10-17T00:38:48Z [Bootstrapper::UpgradeRoblox] Registering approximate program size...
2024-10-17T00:38:48Z [RegistryKeyEx::SetValueSafe] Writing '444669' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\EstimatedSize
2024-10-17T00:38:48Z [Bootstrapper::UpgradeRoblox] Registered as 444669 KB
2024-10-17T00:38:48Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-17T00:38:48Z [JsonManager<State>::Save] Save complete!
2024-10-17T00:38:48Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] Begin font check
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] End font check
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\CustomFont.ttf has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\sounds\action_falling.mp3 has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\sounds\action_footsteps_plastic.mp3 has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\sounds\action_get_up.mp3 has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\sounds\action_jump.mp3 has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\sounds\action_jump_land.mp3 has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\sounds\action_swim.mp3 has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\sounds\impact_water.mp3 has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] ExtraContent\places\Mobile.rbxl has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\AccanthisADFStd.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\AmaticSC.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Arimo.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Balthazar.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Bangers.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\BuilderSans.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\ComicNeueAngular.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Creepster.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\DenkOne.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Fondamento.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\FredokaOne.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\GrenzeGotisch.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Guru.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\HighwayGothic.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Inconsolata.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\IndieFlower.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\JosefinSans.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Jura.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Kalam.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\LegacyArial.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\LegacyArimo.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\LuckiestGuy.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Merriweather.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Michroma.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Montserrat.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Nunito.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Oswald.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\PatrickHand.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\PermanentMarker.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\PressStart2P.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Roboto.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\RobotoCondensed.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\RobotoMono.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\RomanAntique.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Sarpanch.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\SourceSansPro.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\SpecialElite.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\TitilliumWeb.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Ubuntu.json has been copied to the version folder
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Zekton.json has been copied to the version folder
2024-10-17T00:38:48Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-17T00:38:48Z [JsonManager<State>::Save] Save complete!
2024-10-17T00:38:48Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-10-17T00:38:48Z [Bootstrapper::SetStatus] Starting {product}...
2024-10-17T00:38:50Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-17T00:38:50Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-17T00:38:50Z [App::FinalizeExceptionHandling] System.ComponentModel.Win32Exception (740): An error occurred trying to start process '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player'. The requested operation requires elevation.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()

**Comment by pizzaboxer** [comment]
Antivirus issue. Check to make sure it's not blocking anything, or try reinstalling.
