### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: An error occurred trying to start process 'D:\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory 'D:\Bloxstrap\Roblox\Player'. The requested operation requires elevation.

### ISSUE THREAD

**Issue by strait7291** [bloxstraplabs/bloxstrap#3255]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

idk this problem appeared out of nowhere
![asdwafx](https://github.com/user-attachments/assets/15025897-7de6-4e5e-b7e6-24aa270b5182)

### Bloxstrap Log

2024-10-17T13:13:02Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-17T13:13:02Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 3:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-17T13:13:02Z [App::OnStartup] Loaded from D:\Bloxstrap\Bloxstrap.exe
2024-10-17T13:13:02Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-17T13:13:02Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-17T13:13:02Z [Logger::Initialize] Initializing at D:\Bloxstrap\Logs\Bloxstrap_20241017T131302Z.log
2024-10-17T13:13:02Z [Logger::Initialize] Finished initializing!
2024-10-17T13:13:02Z [JsonManager<Settings>::Load] Loading from D:\Bloxstrap\Settings.json...
2024-10-17T13:13:02Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-17T13:13:02Z [JsonManager<State>::Load] Loading from D:\Bloxstrap\State.json...
2024-10-17T13:13:02Z [JsonManager<State>::Load] Loaded successfully!
2024-10-17T13:13:02Z [FastFlagManager::Load] Loading from D:\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-17T13:13:02Z [FastFlagManager::Load] Loaded successfully!
2024-10-17T13:13:03Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-17T13:13:03Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-17T13:13:03Z [Bootstrapper::Run] Running bootstrapper
2024-10-17T13:13:03Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-17T13:13:03Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-17T13:13:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-17T13:13:03Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-17T13:13:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-17T13:13:05Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-17T13:13:05Z [Bootstrapper::Run] Connectivity check finished
2024-10-17T13:13:05Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-17T13:13:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-17T13:13:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-17T13:13:05Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-17T13:13:05Z [Bootstrapper::GetLatestVersionInfo] Got channel as zassetcacheinit4
2024-10-17T13:13:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zassetcacheinit4
2024-10-17T13:13:05Z [Deployment::GetInfo] Getting deploy info for channel zassetcacheinit4
2024-10-17T13:13:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zassetcacheinit4
2024-10-17T13:13:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zassetcacheinit4
2024-10-17T13:13:06Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-17T13:13:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-17T13:13:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-17T13:13:06Z [RegistryKeyEx::SetValueSafe] Writing 'zassetcacheinit4' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-17T13:13:06Z [ApplicationSettings::Fetch.PCClientBootstrapper.zassetcacheinit4] Fetching fast flags
2024-10-17T13:13:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zassetcacheinit4
2024-10-17T13:13:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zassetcacheinit4
2024-10-17T13:13:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-17T13:13:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-17T13:13:06Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-17T13:13:06Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-17T13:13:06Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json has been copied to the version folder
2024-10-17T13:13:06Z [JsonManager<State>::Save] Saving to D:\Bloxstrap\State.json...
2024-10-17T13:13:06Z [JsonManager<State>::Save] Save complete!
2024-10-17T13:13:06Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-10-17T13:13:06Z [Bootstrapper::SetStatus] Starting {product}...
2024-10-17T13:13:06Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zassetcacheinit4
2024-10-17T13:13:09Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-17T13:13:09Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-17T13:13:09Z [App::FinalizeExceptionHandling] System.ComponentModel.Win32Exception (740): An error occurred trying to start process 'D:\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory 'D:\Bloxstrap\Roblox\Player'. The requested operation requires elevation.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()

**Comment by strait7291** [comment]
idk it just shows this when i open bloxstrap

**Comment by strait7291** [comment]
also before this happened i could not use true full screen and please fix this problem

**Comment by pizzaboxer** [comment]
Antivirus issue. Try configuring your antivirus to add Bloxstrap's installation folder as an exception, or try reinstalling Bloxstrap.
