### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Users\ZTS\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory 'C:\Users\ZTS\AppData\Local\Bloxstrap\Roblox\Player'. The requested operation requires elevation.

### ISSUE THREAD

**Issue by suramraja** [bloxstraplabs/bloxstrap#3299]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

2024-10-18T08:22:21Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-18T08:22:21Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 4:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-18T08:22:21Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-18T08:22:21Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-18T08:22:21Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-18T08:22:21Z [LaunchSettings] Identifier 'player' is active with data
2024-10-18T08:22:21Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241018T082221Z.log
2024-10-18T08:22:21Z [Logger::Initialize] Finished initializing!
2024-10-18T08:22:21Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-18T08:22:21Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-18T08:22:21Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-18T08:22:21Z [JsonManager<State>::Load] Loaded successfully!
2024-10-18T08:22:21Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-18T08:22:21Z [FastFlagManager::Load] Loaded successfully!
2024-10-18T08:22:21Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-18T08:22:21Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-18T08:22:21Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-18T08:22:21Z [Bootstrapper::Run] Running bootstrapper
2024-10-18T08:22:21Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-18T08:22:21Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-18T08:22:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-18T08:22:21Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-18T08:22:22Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-18T08:22:22Z [Bootstrapper::Run] Connectivity check finished
2024-10-18T08:22:22Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessResponse] 403 rate limit exceeded https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-18T08:22:22Z [App::GetLatestRelease] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.App.GetLatestRelease()
2024-10-18T08:22:22Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-18T08:22:22Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-18T08:22:22Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-18T08:22:22Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-18T08:22:22Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-18T08:22:22Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-10-18T08:22:22Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-18T08:22:22Z [JsonManager<State>::Save] Save complete!
2024-10-18T08:22:22Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-10-18T08:22:22Z [Bootstrapper::SetStatus] Starting {product}...
2024-10-18T08:22:22Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-18T08:22:22Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-18T08:22:22Z [App::FinalizeExceptionHandling] System.ComponentModel.Win32Exception (740): An error occurred trying to start process '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player'. The requested operation requires elevation.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()

### Bloxstrap Log

2024-10-18T08:22:21Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-18T08:22:21Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 4:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-18T08:22:21Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-18T08:22:21Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-18T08:22:21Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-18T08:22:21Z [LaunchSettings] Identifier 'player' is active with data
2024-10-18T08:22:21Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241018T082221Z.log
2024-10-18T08:22:21Z [Logger::Initialize] Finished initializing!
2024-10-18T08:22:21Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-18T08:22:21Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-18T08:22:21Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-18T08:22:21Z [JsonManager<State>::Load] Loaded successfully!
2024-10-18T08:22:21Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-18T08:22:21Z [FastFlagManager::Load] Loaded successfully!
2024-10-18T08:22:21Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-18T08:22:21Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-18T08:22:21Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-18T08:22:21Z [Bootstrapper::Run] Running bootstrapper
2024-10-18T08:22:21Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-18T08:22:21Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-18T08:22:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-18T08:22:21Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-18T08:22:22Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-18T08:22:22Z [Bootstrapper::Run] Connectivity check finished
2024-10-18T08:22:22Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessResponse] 403 rate limit exceeded https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-18T08:22:22Z [App::GetLatestRelease] System.Net.Http.HttpRequestException: Response status code does not indicate success: 403 (rate limit exceeded).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.App.GetLatestRelease()
2024-10-18T08:22:22Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-18T08:22:22Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-18T08:22:22Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-18T08:22:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-18T08:22:22Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-18T08:22:22Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-18T08:22:22Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-10-18T08:22:22Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-18T08:22:22Z [JsonManager<State>::Save] Save complete!
2024-10-18T08:22:22Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-10-18T08:22:22Z [Bootstrapper::SetStatus] Starting {product}...
2024-10-18T08:22:22Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-18T08:22:22Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-18T08:22:22Z [App::FinalizeExceptionHandling] System.ComponentModel.Win32Exception (740): An error occurred trying to start process '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player'. The requested operation requires elevation.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()

**Comment by suramraja** [comment]
i already try re-install roblox and bloxstrap but still not working

**Comment by suramraja** [comment]
solved , thank you pizzaboxer 
https://github.com/bloxstraplabs/bloxstrap/issues/3274#issuecomment-2420390038
