### ISSUE TITLE
[BUG] An exception occured while running bloxstrap

### ISSUE THREAD

**Issue by zura53** [bloxstraplabs/bloxstrap#3308]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

ALSO This is 2.80 version
![ohsa](https://github.com/user-attachments/assets/5b2da5c8-6336-4fa8-a4ec-fbd701d5537c)

### Bloxstrap Log
```
N/A2024-10-18T11:53:17Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-18T11:53:17Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 1:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-18T11:53:17Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.0.exe
2024-10-18T11:53:17Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-18T11:53:17Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-18T11:53:17Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241018T115317Z.log
2024-10-18T11:53:17Z [Logger::Initialize] Finished initializing!
2024-10-18T11:53:17Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-18T11:53:17Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-18T11:53:17Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-18T11:53:17Z [JsonManager<State>::Load] Loaded successfully!
2024-10-18T11:53:17Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-18T11:53:17Z [FastFlagManager::Load] Loaded successfully!
2024-10-18T11:53:17Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-18T11:53:20Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-18T11:53:20Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-18T11:53:21Z [Bootstrapper::Run] Running bootstrapper
2024-10-18T11:53:21Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-18T11:53:21Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-18T11:53:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-18T11:53:21Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-18T11:53:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-18T11:53:21Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-18T11:53:21Z [Bootstrapper::Run] Connectivity check finished
2024-10-18T11:53:21Z [Bootstrapper::CheckForUpdates] More than one Bloxstrap instance running, aborting update check
2024-10-18T11:53:21Z [Bootstrapper::GetLatestVersionInfo] Got channel as zaomarpcregressionteststale3
2024-10-18T11:53:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zaomarpcregressionteststale3
2024-10-18T11:53:21Z [Deployment::GetInfo] Getting deploy info for channel zaomarpcregressionteststale3
2024-10-18T11:53:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zaomarpcregressionteststale3
2024-10-18T11:53:21Z [Deployment::GetInfo] Failed to contact clientsettingscdn! Falling back to clientsettings...
2024-10-18T11:53:21Z [Deployment::GetInfo] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.RobloxInterfaces.Deployment.GetInfo(String channel)
2024-10-18T11:53:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettings.roblox.com/v2/client-version/WindowsPlayer/channel/zaomarpcregressionteststale3
2024-10-18T11:53:21Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zaomarpcregressionteststale3
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettings.roblox.com/v2/client-version/WindowsPlayer/channel/zaomarpcregressionteststale3
2024-10-18T11:53:22Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-18T11:53:22Z [Deployment::GetInfo] Failed to contact clientsettingscdn! Falling back to clientsettings...
2024-10-18T11:53:22Z [Deployment::GetInfo] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.RobloxInterfaces.Deployment.GetInfo(String channel)
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettings.roblox.com/v2/client-version/WindowsPlayer
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettings.roblox.com/v2/client-version/WindowsPlayer
2024-10-18T11:53:22Z [RegistryKeyEx::SetValueSafe] Writing 'zaomarpcregressionteststale3' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-18T11:53:22Z [ApplicationSettings::Fetch.PCClientBootstrapper.zaomarpcregressionteststale3] Fetching fast flags
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zaomarpcregressionteststale3
2024-10-18T11:53:22Z [ApplicationSettings::Fetch.PCClientBootstrapper.zaomarpcregressionteststale3] Failed to contact clientsettingscdn! Falling back to clientsettings...
2024-10-18T11:53:22Z [ApplicationSettings::Fetch.PCClientBootstrapper.zaomarpcregressionteststale3] System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxInterfaces.ApplicationSettings.Fetch()
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettings.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zaomarpcregressionteststale3
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettings.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zaomarpcregressionteststale3
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-18T11:53:22Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-18T11:53:22Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-18T11:53:22Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-10-18T11:53:22Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg was removed as a mod, restoring from content-sounds.zip
2024-10-18T11:53:22Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-18T11:53:22Z [Bootstrapper::DownloadPackage.content-sounds.zip] An exception occurred after downloading 0 bytes. (1/5)
2024-10-18T11:53:22Z [Bootstrapper::DownloadPackage.content-sounds.zip] System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Downloads\cd77e0e77d698260809f8ae8b3993740'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-10-18T11:53:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-18T11:53:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-18T11:53:23Z [Bootstrapper::DownloadPackage.content-sounds.zip] An exception occurred after downloading 0 bytes. (2/5)
2024-10-18T11:53:23Z [Bootstrapper::DownloadPackage.content-sounds.zip] System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Downloads\cd77e0e77d698260809f8ae8b3993740'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-10-18T11:53:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-18T11:53:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-18T11:53:23Z [Bootstrapper::DownloadPackage.content-sounds.zip] An exception occurred after downloading 0 bytes. (3/5)
2024-10-18T11:53:23Z [Bootstrapper::DownloadPackage.content-sounds.zip] System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Downloads\cd77e0e77d698260809f8ae8b3993740'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-10-18T11:53:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-18T11:53:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-18T11:53:23Z [Bootstrapper::DownloadPackage.content-sounds.zip] An exception occurred after downloading 0 bytes. (4/5)
2024-10-18T11:53:23Z [Bootstrapper::DownloadPackage.content-sounds.zip] System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Downloads\cd77e0e77d698260809f8ae8b3993740'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-10-18T11:53:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-18T11:53:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-18T11:53:23Z [Bootstrapper::DownloadPackage.content-sounds.zip] An exception occurred after downloading 0 bytes. (5/5)
2024-10-18T11:53:23Z [Bootstrapper::DownloadPackage.content-sounds.zip] System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Downloads\cd77e0e77d698260809f8ae8b3993740'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-10-18T11:53:23Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-18T11:53:23Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-18T11:53:23Z [App::FinalizeExceptionHandling] System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Downloads\cd77e0e77d698260809f8ae8b3993740'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.ApplyModifications()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by Graaliam** [comment]
Did you used the mods setting in Manage Compatibility Settings? if so, revert it back to normal. the setting (Run RobloxPlayerBeta as administrator) mainly cause that to happen. should be located somewhere in "C:\Users\(YOURPCNAME)\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe" Search for RobloxPlayerBeta and revert everything to fix it.

**Comment by iambaconlate** [comment]
I have the same problem.
