### ISSUE TITLE
[BUG] Roblox is not launching.

### ISSUE THREAD

**Issue by percivalxp** [bloxstraplabs/bloxstrap#3321]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I went to "C:\Users\User\AppData\Local\Bloxstrap\Roblox\Player" and the roblox files were gone.

### Bloxstrap Log

```text
2024-10-18T21:32:59Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-18T21:32:59Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 4:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-18T21:32:59Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-18T21:32:59Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-18T21:32:59Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-18T21:32:59Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241018T213259Z.log
2024-10-18T21:32:59Z [Logger::Initialize] Finished initializing!
2024-10-18T21:32:59Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-18T21:32:59Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-18T21:32:59Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-18T21:32:59Z [JsonManager<State>::Load] Loaded successfully!
2024-10-18T21:32:59Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-18T21:32:59Z [FastFlagManager::Load] Loaded successfully!
2024-10-18T21:32:59Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-18T21:33:04Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-18T21:33:04Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-18T21:33:04Z [Bootstrapper::Run] Running bootstrapper
2024-10-18T21:33:04Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-18T21:33:04Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-18T21:33:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-18T21:33:05Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-18T21:33:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-18T21:33:05Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-18T21:33:05Z [Bootstrapper::Run] Connectivity check finished
2024-10-18T21:33:05Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-18T21:33:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-18T21:33:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-18T21:33:06Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-18T21:33:06Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-18T21:33:06Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-18T21:33:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-18T21:33:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-18T21:33:06Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-18T21:33:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-18T21:33:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-18T21:33:06Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-18T21:33:09Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-18T21:33:09Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-10-18T21:33:09Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-10-18T21:33:10Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-18T21:33:10Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-10-18T21:33:10Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-10-18T21:33:10Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-10-18T21:33:10Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-18T21:33:10Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-18T21:33:10Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-18T21:33:10Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-18T21:33:10Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-18T21:33:10Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-18T21:33:10Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-18T21:33:10Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-18T21:33:10Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-18T21:33:11Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-18T21:33:11Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-18T21:33:11Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-18T21:33:11Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-18T21:33:12Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-18T21:33:12Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-18T21:33:15Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-18T21:33:16Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-18T21:33:16Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-18T21:33:16Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-18T21:33:16Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-18T21:33:17Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-18T21:33:17Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-18T21:33:17Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-18T21:33:17Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-18T21:33:17Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-18T21:33:17Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-18T21:33:17Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-18T21:33:17Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-18T21:33:18Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-18T21:33:21Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-18T21:33:21Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-18T21:33:21Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-18T21:33:21Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-18T21:33:23Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-18T21:33:39Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-18T21:33:57Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-18T21:33:57Z [Bootstrapper::UpgradeRoblox] Writing AppSettings.xml...
2024-10-18T21:33:57Z [Bootstrapper::UpgradeRoblox] Registering approximate program size...
2024-10-18T21:33:57Z [RegistryKeyEx::SetValueSafe] Writing '444669' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\EstimatedSize
2024-10-18T21:33:57Z [Bootstrapper::UpgradeRoblox] Registered as 444669 KB
2024-10-18T21:33:57Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-18T21:33:57Z [JsonManager<State>::Save] Save complete!
2024-10-18T21:33:57Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-18T21:33:57Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-18T21:33:57Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json has been copied to the version folder
2024-10-18T21:33:57Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-18T21:33:57Z [JsonManager<State>::Save] Save complete!
2024-10-18T21:33:57Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-10-18T21:33:57Z [Bootstrapper::SetStatus] Starting {product}...
2024-10-18T21:34:04Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-18T21:34:04Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-18T21:34:04Z [App::FinalizeExceptionHandling] System.ComponentModel.Win32Exception (740): An error occurred trying to start process '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player'. The requested operation requires elevation.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by percivalxp** [comment]
I tried reinstalling bloxstrap

**Comment by pizzaboxer** [comment]
Read the Wiki next time. https://github.com/bloxstraplabs/bloxstrap/wiki/%22The-requested-operation-requires-elevation%22-error-when-launching-Roblox
