### ISSUE TITLE
[BUG] System.IO.FileNotFoundException: Could not find file 'C:\Users\Admin\AppData\Local\Roblox\logs'.

### ISSUE THREAD

**Issue by Mizuki087jp** [bloxstraplabs/bloxstrap#3328]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

Hello, Bloxtrap Team!
I'm currently facing a Problem where Bloxstrap doesn't seem to find my Roblox logs Non of my troubleshooting that I've done worked. I hoped that The Bloxstrap Team could fix this problem.
![image](https://github.com/user-attachments/assets/d5e452b4-1690-4783-8ebe-ebf59a35959d)

Thank you!

### Bloxstrap Log

```text
2024-10-19T02:10:27Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-19T02:10:27Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 5:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-19T02:10:27Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.0.exe
2024-10-19T02:10:27Z [App::OnStartup] Temp path is C:\Program Files\KMSpico\temp\Bloxstrap
2024-10-19T02:10:27Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-19T02:10:27Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241019T021027Z.log
2024-10-19T02:10:27Z [Logger::Initialize] Finished initializing!
2024-10-19T02:10:27Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-19T02:10:27Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-19T02:10:27Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-19T02:10:27Z [JsonManager<State>::Load] Loaded successfully!
2024-10-19T02:10:27Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-19T02:10:27Z [FastFlagManager::Load] Loaded successfully!
2024-10-19T02:10:27Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-19T02:10:30Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-19T02:10:30Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-19T02:10:30Z [Bootstrapper::Run] Running bootstrapper
2024-10-19T02:10:30Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-19T02:10:30Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-19T02:10:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-19T02:10:31Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-19T02:10:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-19T02:10:31Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-19T02:10:31Z [Bootstrapper::Run] Connectivity check finished
2024-10-19T02:10:31Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-19T02:10:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-19T02:10:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-19T02:10:31Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-19T02:10:31Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-19T02:10:31Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-19T02:10:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-19T02:10:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-19T02:10:31Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-19T02:10:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-19T02:10:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-19T02:10:31Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-19T02:10:31Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-19T02:10:31Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-10-19T02:10:31Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-19T02:10:31Z [JsonManager<State>::Save] Save complete!
2024-10-19T02:10:31Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-10-19T02:10:31Z [Bootstrapper::SetStatus] Starting {product}...
2024-10-19T02:10:31Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-19T02:10:31Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-19T02:10:31Z [App::FinalizeExceptionHandling] System.IO.FileNotFoundException: Could not find file '%UserProfile%\AppData\Local\Roblox\logs'.
File name: '%UserProfile%\AppData\Local\Roblox\logs'
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by pizzaboxer** [comment]
```

**Comment by Mizuki087jp** [comment]
I don't know It just happened randomly when I tried joining on a game. it's quite odd

**Comment by pizzaboxer** [comment]
Bloxstrap appears to be being denied read access to Roblox's installation folder. Do you have any antiviruses installed?

**Comment by Mizuki087jp** [comment]
Malwarebytes is the only Anti-virus that I have

**Comment by pizzaboxer** [comment]
Can you try adding an exception for Bloxstrap in it?

**Comment by Mizuki087jp** [comment]
I'll see for myself if i can try

**Comment by pizzaboxer** [comment]
This isn't a problem on our end, something is messing with Bloxstrap and doing something weird, as there's no other reason for this issue to be happening.

The most I can do to remedy this is to add an informational error message instead of just throwing an exception

**Comment by Mizuki087jp** [comment]
It could be because I didn't have the actual Roblox player installed?
Since Roblox won't install in my PC for no reason
