### ISSUE TITLE
[BUG] Bloxstrap breaks upon trying to install newest update

### ISSUE THREAD

**Issue by sneedcoding** [bloxstraplabs/bloxstrap#3370]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### What problem did you encounter?

I dont even understand why it doesnt work anymore, it was working just fine yesterday but now it keeps bugging out and breaking, pls fix!  : (

### Bloxstrap Log

```text
"System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Users\Al Sneed\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory 'C:\Users\Al Sneed\AppData\Local\Bloxstrap\Roblox\Player'. The requested operation requires elevation." AlSneed is my desktop user btw
"2024-10-20T17:14:07Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-20T17:14:07Z [JsonManager<State>::Save] Save complete!
2024-10-20T17:14:07Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-10-20T17:14:07Z [Bootstrapper::SetStatus] Starting {product}...
2024-10-20T17:14:08Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-20T17:14:08Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-20T17:14:08Z [App::FinalizeExceptionHandling] System.ComponentModel.Win32Exception (740): An error occurred trying to start process '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player'. The requested operation requires elevation.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
"
```

**Comment by sneedcoding** [comment]
![image](https://github.com/user-attachments/assets/4e617eef-b41a-4ec2-a0bb-ed11a5a6bab7)

**Comment by pizzaboxer** [comment]
Addressed in Wiki. https://github.com/bloxstraplabs/bloxstrap/wiki/%22The-requested-operation-requires-elevation%22-error-when-launching-Roblox

**Comment by sneedcoding** [comment]
OMG THANK YOU
