### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'RobloxCrashHandler.exe' is denied.

### ISSUE THREAD

**Issue by comically21** [bloxstraplabs/bloxstrap#3376]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.0

### What problem did you encounter?

Unable to download roblox because of this. I checked every article on the wiki about this error and I cant fix it.

### Bloxstrap Log

```text
2024-10-21T00:24:08Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-21T00:24:08Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 5:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-21T00:24:08Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-21T00:24:08Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-21T00:24:08Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-21T00:24:08Z [LaunchSettings] Identifier 'player' is active
2024-10-21T00:24:08Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241021T002408Z.log
2024-10-21T00:24:08Z [Logger::Initialize] Finished initializing!
2024-10-21T00:24:08Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-21T00:24:08Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-21T00:24:08Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-21T00:24:08Z [JsonManager<State>::Load] Loaded successfully!
2024-10-21T00:24:08Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-21T00:24:08Z [FastFlagManager::Load] Loaded successfully!
2024-10-21T00:24:08Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-21T00:24:08Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-21T00:24:08Z [Bootstrapper::Run] Running bootstrapper
2024-10-21T00:24:08Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-21T00:24:08Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-21T00:24:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-21T00:24:08Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-21T00:24:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-21T00:24:10Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-21T00:24:10Z [Bootstrapper::Run] Connectivity check finished
2024-10-21T00:24:10Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-21T00:24:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-21T00:24:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-21T00:24:11Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-21T00:24:11Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-21T00:24:11Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-21T00:24:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-21T00:24:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-21T00:24:12Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-21T00:24:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-21T00:24:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-21T00:24:12Z [Bootstrapper::SetStatus] Installing {product}...
2024-10-21T00:24:12Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-21T00:24:12Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-21T00:24:12Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'RobloxCrashHandler.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by ItlogNiVenjo** [comment]
Hello, I too had the same problem but soon found the fix for my case, I will list the steps of what to do and maybe it could fix yours too,

![image_2024-10-22_134524815](https://github.com/user-attachments/assets/dfc726ae-da9c-4c28-99f1-960fe5907f99)
My case here.

1. Go to C:\Users\(yo pc name)\AppData\Local\Bloxstrap 
2. Click the Roblox folder then the Player Folder
3. Delete RobloxCrashHandler inside the Player Folder (If it happens to say its running in the background, move the Player Folder somewhere else and create another inside the [Bloxstrap] Roblox Folder and just do the exact same with the last few steps)

4. If you have a Desktop Shortcut of Roblox then Rmb and Open file location the Roblox Launcher (Original)
5. Find it's RobloxCrashHandler and copypaste into the Player folder
6. Relaunch Bloxstrap and wait for the installation to finish

If it had not worked, then I don't know, this is the solution that I found and worked for me.

**Comment by amnahatif65-ui** [comment]
I click on the user part but it doesn’t open.
