### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'WebView2Loader.dll' is denied.

### ISSUE THREAD

**Issue by vivid-2** [bloxstraplabs/bloxstrap#3383]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

i enabled force roblox reinstallation and now this happens all the time

### Bloxstrap Log

```text
2024-10-21T09:12:16Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-21T09:12:16Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 12:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-21T09:12:16Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-21T09:12:16Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-21T09:12:16Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-21T09:12:16Z [LaunchSettings] Identifier 'player' is active with data
2024-10-21T09:12:16Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241021T091216Z.log
2024-10-21T09:12:16Z [Logger::Initialize] Finished initializing!
2024-10-21T09:12:16Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-21T09:12:16Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-21T09:12:16Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-21T09:12:16Z [JsonManager<State>::Load] Loaded successfully!
2024-10-21T09:12:16Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-21T09:12:16Z [FastFlagManager::Load] Loaded successfully!
2024-10-21T09:12:16Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-21T09:12:16Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-21T09:12:16Z [Bootstrapper::Run] Running bootstrapper
2024-10-21T09:12:16Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-21T09:12:16Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-21T09:12:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-21T09:12:16Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-21T09:12:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-21T09:12:16Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-21T09:12:16Z [Bootstrapper::Run] Connectivity check finished
2024-10-21T09:12:16Z [Bootstrapper::CheckForUpdates] More than one Bloxstrap instance running, aborting update check
2024-10-21T09:12:16Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-21T09:12:16Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-21T09:12:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-21T09:12:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-21T09:12:16Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-21T09:12:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-21T09:12:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-21T09:12:16Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-10-21T09:12:16Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-21T09:12:16Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-21T09:12:16Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'WebView2Loader.dll' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by vivid-2** [comment]
fixed it with a reinstall
