### ISSUE TITLE
[BUG] "The requested operation requires elevation" I WILL GO MAD

### ISSUE THREAD

**Issue by Srivspeed** [bloxstraplabs/bloxstrap#3400]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

I looked through the wiki and tried a solution which did not work then reinstalled bloxstrap and still did not work, I will go crazy if I do not get a solution as this has been happening the past week. Bloxstrap is no longer running on administrator perms because when I looked it did not have.

### Bloxstrap Log

```text
2024-10-22T14:45:41Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-22T14:45:41Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 3:14:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-22T14:45:41Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-22T14:45:41Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-22T14:45:41Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-22T14:45:41Z [LaunchSettings] Identifier 'player' is active with data
2024-10-22T14:45:41Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241022T144541Z.log
2024-10-22T14:45:41Z [Logger::Initialize] Finished initializing!
2024-10-22T14:45:41Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-22T14:45:41Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-22T14:45:41Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-22T14:45:41Z [JsonManager<State>::Load] Loaded successfully!
2024-10-22T14:45:41Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-22T14:45:41Z [FastFlagManager::Load] Loaded successfully!
2024-10-22T14:45:41Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-22T14:45:41Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-22T14:45:41Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-22T14:45:41Z [Bootstrapper::Run] Running bootstrapper
2024-10-22T14:45:41Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-22T14:45:41Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-22T14:45:41Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-22T14:45:41Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-22T14:45:43Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-22T14:45:43Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-22T14:45:43Z [Bootstrapper::Run] Connectivity check finished
2024-10-22T14:45:43Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-22T14:45:43Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-22T14:45:43Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-22T14:45:43Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-22T14:45:43Z [Bootstrapper::GetLatestVersionInfo] Got channel as zharmonyplannerv2-0control
2024-10-22T14:45:43Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zharmonyplannerv2-0control
2024-10-22T14:45:43Z [Deployment::GetInfo] Getting deploy info for channel zharmonyplannerv2-0control
2024-10-22T14:45:43Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zharmonyplannerv2-0control
2024-10-22T14:45:44Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zharmonyplannerv2-0control
2024-10-22T14:45:44Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zharmonyplannerv2-0control
2024-10-22T14:45:44Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-22T14:45:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-22T14:45:44Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-22T14:45:44Z [RegistryKeyEx::SetValueSafe] Writing 'zharmonyplannerv2-0control' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-22T14:45:44Z [ApplicationSettings::Fetch.PCClientBootstrapper.zharmonyplannerv2-0control] Fetching fast flags
2024-10-22T14:45:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zharmonyplannerv2-0control
2024-10-22T14:45:44Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zharmonyplannerv2-0control
2024-10-22T14:45:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-22T14:45:44Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-22T14:45:44Z [Bootstrapper::SetStatus] Installing {product}...
2024-10-22T14:45:44Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-10-22T14:45:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-RobloxApp.zip
2024-10-22T14:45:44Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-RobloxApp.zip
2024-10-22T14:46:07Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (86444867 bytes total)
2024-10-22T14:46:07Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-10-22T14:46:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-avatar.zip
2024-10-22T14:46:07Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-22T14:46:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-avatar.zip
2024-10-22T14:46:07Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (402097 bytes total)
2024-10-22T14:46:07Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-22T14:46:07Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-10-22T14:46:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-configs.zip
2024-10-22T14:46:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-configs.zip
2024-10-22T14:46:07Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (256192 bytes total)
2024-10-22T14:46:07Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-22T14:46:07Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-10-22T14:46:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-fonts.zip
2024-10-22T14:46:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-fonts.zip
2024-10-22T14:46:08Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-22T14:46:08Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-22T14:46:09Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-10-22T14:46:09Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-22T14:46:09Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-10-22T14:46:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-models.zip
2024-10-22T14:46:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-models.zip
2024-10-22T14:46:09Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (488968 bytes total)
2024-10-22T14:46:09Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-22T14:46:09Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-10-22T14:46:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sky.zip
2024-10-22T14:46:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sky.zip
2024-10-22T14:46:09Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-22T14:46:10Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-10-22T14:46:10Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-22T14:46:10Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-10-22T14:46:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-22T14:46:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-sounds.zip
2024-10-22T14:46:10Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (373629 bytes total)
2024-10-22T14:46:10Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-22T14:46:10Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-10-22T14:46:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-shaders.zip
2024-10-22T14:46:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-shaders.zip
2024-10-22T14:46:10Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-22T14:46:10Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-22T14:46:10Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-22T14:46:11Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-22T14:46:12Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (9165141 bytes total)
2024-10-22T14:46:12Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-22T14:46:12Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-10-22T14:46:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-ssl.zip
2024-10-22T14:46:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-ssl.zip
2024-10-22T14:46:12Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (135951 bytes total)
2024-10-22T14:46:12Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-22T14:46:12Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-10-22T14:46:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-textures2.zip
2024-10-22T14:46:12Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-22T14:46:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-textures2.zip
2024-10-22T14:46:13Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-22T14:46:16Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (12448624 bytes total)
2024-10-22T14:46:16Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-22T14:46:16Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-10-22T14:46:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-textures3.zip
2024-10-22T14:46:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-textures3.zip
2024-10-22T14:46:17Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-10-22T14:46:17Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-22T14:46:17Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-10-22T14:46:17Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-terrain.zip
2024-10-22T14:46:17Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-terrain.zip
2024-10-22T14:46:17Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-10-22T14:46:17Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-10-22T14:46:17Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-platform-fonts.zip
2024-10-22T14:46:17Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-22T14:46:17Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-22T14:46:17Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-content-platform-fonts.zip
2024-10-22T14:46:17Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-22T14:46:21Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-10-22T14:46:21Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-22T14:46:21Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-10-22T14:46:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-extracontent-places.zip
2024-10-22T14:46:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-extracontent-places.zip
2024-10-22T14:46:21Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1267329 bytes total)
2024-10-22T14:46:21Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-22T14:46:21Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-10-22T14:46:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-extracontent-luapackages.zip
2024-10-22T14:46:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-extracontent-luapackages.zip
2024-10-22T14:46:21Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-22T14:46:22Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-22T14:46:23Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-22T14:46:24Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (9549818 bytes total)
2024-10-22T14:46:24Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-22T14:46:24Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-10-22T14:46:24Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-extracontent-translations.zip
2024-10-22T14:46:24Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-extracontent-translations.zip
2024-10-22T14:46:24Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (483710 bytes total)
2024-10-22T14:46:24Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-22T14:46:24Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-10-22T14:46:24Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-extracontent-models.zip
2024-10-22T14:46:24Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-22T14:46:25Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-extracontent-models.zip
2024-10-22T14:46:25Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-22T14:46:29Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (10111741 bytes total)
2024-10-22T14:46:29Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-22T14:46:29Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-10-22T14:46:29Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-extracontent-textures.zip
2024-10-22T14:46:29Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-extracontent-textures.zip
2024-10-22T14:46:29Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-22T14:46:33Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (16874222 bytes total)
2024-10-22T14:46:33Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-22T14:46:33Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-10-22T14:46:33Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-WebView2.zip
2024-10-22T14:46:33Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-WebView2.zip
2024-10-22T14:46:33Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-10-22T14:46:33Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-22T14:46:33Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-10-22T14:46:33Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-WebView2RuntimeInstaller.zip
2024-10-22T14:46:33Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-22T14:46:33Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-WebView2RuntimeInstaller.zip
2024-10-22T14:46:34Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-10-22T14:46:34Z [Bootstrapper::DownloadPackage.redist.zip] Downloading...
2024-10-22T14:46:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-redist.zip
2024-10-22T14:46:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9dbf9780562444e1-redist.zip
2024-10-22T14:46:34Z [Bootstrapper::DownloadPackage.redist.zip] Finished downloading! (1372275 bytes total)
2024-10-22T14:46:34Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-22T14:46:34Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-22T14:46:34Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-22T14:46:35Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-22T14:46:35Z [Bootstrapper::UpgradeRoblox] Writing AppSettings.xml...
2024-10-22T14:46:35Z [Bootstrapper::UpgradeRoblox] Registering approximate program size...
2024-10-22T14:46:35Z [RegistryKeyEx::SetValueSafe] Writing '444669' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\EstimatedSize
2024-10-22T14:46:35Z [Bootstrapper::UpgradeRoblox] Registered as 444669 KB
2024-10-22T14:46:35Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-22T14:46:35Z [JsonManager<State>::Save] Save complete!
2024-10-22T14:46:35Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-22T14:46:35Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-22T14:46:35Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json has been copied to the version folder
2024-10-22T14:46:35Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-22T14:46:35Z [JsonManager<State>::Save] Save complete!
2024-10-22T14:46:35Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-10-22T14:46:35Z [Bootstrapper::SetStatus] Starting {product}...
2024-10-22T14:46:37Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-22T14:46:37Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-22T14:46:37Z [App::FinalizeExceptionHandling] System.ComponentModel.Win32Exception (740): An error occurred trying to start process '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player'. The requested operation requires elevation.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by totallyrandom001** [comment]
i dont think i can help much but here's a wiki page that could possibly help: https://github.com/bloxstraplabs/bloxstrap/wiki/"The-requested-operation-requires-elevation"-error-when-launching-Roblox

**Comment by pizzaboxer** [comment]
Can you show a screenshot of what you see in the registry editor please?

**Comment by MrT-tak** [comment]
@Srivspeed Did you see Pizzaboxer's comment?

> Can you show a screenshot of what you see in the registry editor please?

**Comment by Srivspeed** [comment]
> i dont think i can help much but here's a wiki page that could possibly help: [https://github.com/bloxstraplabs/bloxstrap/wiki/"The-requested-operation-requires-elevation"-error-when-launching-Roblox](https://github.com/bloxstraplabs/bloxstrap/wiki/%22The-requested-operation-requires-elevation%22-error-when-launching-Roblox)

I said I already tried it...

**Comment by Srivspeed** [comment]
Ok I will try it again but if it doesn't work I will go mad

**Comment by Srivspeed** [comment]
It was my third time trying it and now it works... @pizzaboxer da hell is with registry

**Comment by Wanwood1** [comment]
I dont think your supposed to run it as administrator and delete its registry while its on your computer?

**Comment by MrT-tak** [comment]
> It was my third time trying it and now it works... @pizzaboxer da hell is with registry

The registry is where windows and other stuff keep some information.
It's where they keep track of file types(.jpeg .svg .zip .docx etc) or custom url protocols (I will edit later, i forgot what roblox uses to open games).

> Yes, I already have went to HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers and deleted the key and it won't work
Sorry to hear that, im not a c# dev so im on the same page as you. I have no clue.
