### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by ridwix** [bloxstraplabs/bloxstrap#3404]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

![Снимок экрана 2024-10-22 205401](https://github.com/user-attachments/assets/6eb5288b-48a8-4122-af66-581254641126)

### Bloxstrap Log

```text
2024-10-22T17:45:14Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-10-22T17:45:14Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 12:46:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-10-22T17:45:14Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.4.exe
2024-10-22T17:45:14Z [InstallChecker::FirstTimeRun] Running first-time install
2024-10-22T17:45:14Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20241022T174514Z.log
2024-10-22T17:45:14Z [Logger::Initialize] Finished initializing!
2024-10-22T17:45:14Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-10-22T17:45:14Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-10-22T17:45:14Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\Downloads\ClientSettings\ClientAppSettings.json'.
2024-10-22T17:45:14Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-10-22T17:45:14Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-22T17:45:14Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '144' is pending
2024-10-22T17:45:14Z [MainWindow::MainWindow] Initializing menu
2024-10-22T17:45:24Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-10-22T17:45:24Z [App::OnStartup] Initializing bootstrapper
2024-10-22T17:45:24Z [App::OnStartup] Initializing bootstrapper dialog
2024-10-22T17:45:24Z [Bootstrapper::Run] Running bootstrapper
2024-10-22T17:45:24Z [Bootstrapper::Run] Performing connectivity check...
2024-10-22T17:45:24Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-22T17:45:24Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-22T17:45:24Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-22T17:45:25Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-10-22T17:45:26Z [Bootstrapper::Run] Connectivity check finished
2024-10-22T17:45:26Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-10-22T17:45:26Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-10-22T17:45:26Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-10-22T17:45:26Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-10-22T17:45:26Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-10-22T17:45:26Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-10-22T17:45:26Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-22T17:45:26Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-22T17:45:26Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxManifest.txt
2024-10-22T17:45:27Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxManifest.txt
2024-10-22T17:45:27Z [Bootstrapper::SetStatus] Installing Roblox...
2024-10-22T17:45:27Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-10-22T17:45:27Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-RobloxApp.zip
2024-10-22T17:45:27Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-RobloxApp.zip
2024-10-22T17:47:42Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (86444867 bytes total)
2024-10-22T17:47:42Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-10-22T17:47:42Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-10-22T17:47:42Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-content-avatar.zip
2024-10-22T17:47:42Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1...
2024-10-22T17:47:42Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-content-avatar.zip
2024-10-22T17:47:42Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-22T17:47:42Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (402097 bytes total)
2024-10-22T17:47:42Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-10-22T17:47:42Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-10-22T17:47:42Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\avatar\...
2024-10-22T17:47:42Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-content-configs.zip
2024-10-22T17:47:43Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-22T17:47:43Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-content-configs.zip
2024-10-22T17:47:43Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (256192 bytes total)
2024-10-22T17:47:43Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-10-22T17:47:43Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-10-22T17:47:43Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\configs\...
2024-10-22T17:47:43Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-content-fonts.zip
2024-10-22T17:47:43Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-22T17:47:44Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-content-fonts.zip
2024-10-22T17:47:52Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-10-22T17:47:52Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-10-22T17:47:52Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-10-22T17:47:52Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\fonts\...
2024-10-22T17:47:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-content-models.zip
2024-10-22T17:47:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-content-models.zip
2024-10-22T17:47:52Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-22T17:47:53Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (488968 bytes total)
2024-10-22T17:47:53Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-10-22T17:47:53Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-10-22T17:47:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-content-sky.zip
2024-10-22T17:47:53Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\models\...
2024-10-22T17:47:53Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-22T17:47:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-content-sky.zip
2024-10-22T17:47:57Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-10-22T17:47:57Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-10-22T17:47:57Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\sky\...
2024-10-22T17:47:57Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-10-22T17:47:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-content-sounds.zip
2024-10-22T17:47:57Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-22T17:47:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-content-sounds.zip
2024-10-22T17:47:57Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (373629 bytes total)
2024-10-22T17:47:57Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-10-22T17:47:57Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\sounds\...
2024-10-22T17:47:57Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-10-22T17:47:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-shaders.zip
2024-10-22T17:47:57Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-22T17:47:58Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-shaders.zip
2024-10-22T17:48:12Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (9165141 bytes total)
2024-10-22T17:48:12Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-10-22T17:48:12Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\shaders\...
2024-10-22T17:48:12Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-10-22T17:48:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-ssl.zip
2024-10-22T17:48:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-ssl.zip
2024-10-22T17:48:12Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (135951 bytes total)
2024-10-22T17:48:12Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-10-22T17:48:12Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-10-22T17:48:12Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ssl\...
2024-10-22T17:48:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-content-textures2.zip
2024-10-22T17:48:12Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-22T17:48:12Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-22T17:48:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-content-textures2.zip
2024-10-22T17:48:31Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (12448624 bytes total)
2024-10-22T17:48:31Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-10-22T17:48:31Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\content\textures\...
2024-10-22T17:48:31Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-10-22T17:48:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-content-textures3.zip
2024-10-22T17:48:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-content-textures3.zip
2024-10-22T17:48:35Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-22T17:48:37Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-10-22T17:48:37Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-10-22T17:48:37Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\PlatformContent\pc\textures\...
2024-10-22T17:48:37Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-10-22T17:48:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-content-terrain.zip
2024-10-22T17:48:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-content-terrain.zip
2024-10-22T17:48:37Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-10-22T17:48:37Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-10-22T17:48:37Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\PlatformContent\pc\terrain\...
2024-10-22T17:48:37Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-10-22T17:48:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-content-platform-fonts.zip
2024-10-22T17:48:37Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-22T17:48:37Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-22T17:48:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-content-platform-fonts.zip
2024-10-22T17:48:58Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-10-22T17:48:58Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-10-22T17:48:58Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\PlatformContent\pc\fonts\...
2024-10-22T17:48:58Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-10-22T17:48:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-extracontent-places.zip
2024-10-22T17:48:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-extracontent-places.zip
2024-10-22T17:48:59Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-22T17:49:00Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1267329 bytes total)
2024-10-22T17:49:00Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-10-22T17:49:00Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ExtraContent\places\...
2024-10-22T17:49:00Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-10-22T17:49:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-extracontent-luapackages.zip
2024-10-22T17:49:01Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-22T17:49:01Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-extracontent-luapackages.zip
2024-10-22T17:49:15Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (9549818 bytes total)
2024-10-22T17:49:15Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-10-22T17:49:15Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-10-22T17:49:15Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ExtraContent\LuaPackages\...
2024-10-22T17:49:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-extracontent-translations.zip
2024-10-22T17:49:15Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-22T17:49:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-extracontent-translations.zip
2024-10-22T17:49:16Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (483710 bytes total)
2024-10-22T17:49:16Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-10-22T17:49:16Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ExtraContent\translations\...
2024-10-22T17:49:16Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-10-22T17:49:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-extracontent-models.zip
2024-10-22T17:49:16Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-22T17:49:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-extracontent-models.zip
2024-10-22T17:49:32Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (10111741 bytes total)
2024-10-22T17:49:32Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-10-22T17:49:32Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ExtraContent\models\...
2024-10-22T17:49:32Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-10-22T17:49:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-extracontent-textures.zip
2024-10-22T17:49:32Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-22T17:49:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-extracontent-textures.zip
2024-10-22T17:49:59Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (16874222 bytes total)
2024-10-22T17:49:59Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-10-22T17:49:59Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-10-22T17:49:59Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1\ExtraContent\textures\...
2024-10-22T17:49:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-WebView2.zip
2024-10-22T17:49:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-WebView2.zip
2024-10-22T17:49:59Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-10-22T17:49:59Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-10-22T17:49:59Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-10-22T17:49:59Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-9dbf9780562444e1...
2024-10-22T17:49:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-WebView2RuntimeInstaller.zip
2024-10-22T17:49:59Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-22T17:49:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-WebView2RuntimeInstaller.zip
2024-10-22T17:50:00Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-22T17:50:01Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-10-22T17:50:01Z [Bootstrapper::DownloadPackage.redist.zip] Downloading...
2024-10-22T17:50:01Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-redist.zip
2024-10-22T17:50:01Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-redist.zip
2024-10-22T17:50:03Z [Bootstrapper::DownloadPackage.redist.zip] Finished downloading! (1372275 bytes total)
2024-10-22T17:50:03Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting redist.zip'
2024-10-22T17:50:03Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-10-22T17:50:04Z [Bootstrapper::SetStatus] Configuring Roblox...
```

**Comment by NabHeyka22** [comment]
update
