### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\vinegar crimson\AppData\Local\Bloxstrap\State.json' is denied.

### ISSUE THREAD

**Issue by autist31** [bloxstraplabs/bloxstrap#3407]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.0

### What problem did you encounter?

2024-10-22T20:36:39Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-22T20:36:39Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 12:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-22T20:36:39Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-22T20:36:39Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-22T20:36:39Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-22T20:36:39Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241022T203639Z.log
2024-10-22T20:36:39Z [Logger::Initialize] Failed to initialize because Bloxstrap cannot write to %UserProfile%\AppData\Local\Bloxstrap\Logs
2024-10-22T20:36:39Z [Frontend::ShowMessageBox] Файл журнала не будет написан для этого запуска, потому что Bloxstrap не может записать в папку в '%UserProfile%\AppData\Local\Bloxstrap\Logs'
2024-10-22T20:36:45Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-22T20:36:45Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-22T20:36:45Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-22T20:36:45Z [JsonManager<State>::Load] Loaded successfully!
2024-10-22T20:36:45Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-22T20:36:45Z [FastFlagManager::Load] Loaded successfully!
2024-10-22T20:36:45Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-22T20:36:55Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-22T20:36:55Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-22T20:36:55Z [Bootstrapper::Run] Running bootstrapper
2024-10-22T20:36:55Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-22T20:36:55Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-22T20:36:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-22T20:36:55Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-22T20:36:55Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-22T20:36:55Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-22T20:36:55Z [Bootstrapper::Run] Connectivity check finished
2024-10-22T20:36:55Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-22T20:36:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-22T20:36:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-22T20:36:56Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-22T20:36:56Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-22T20:36:56Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-22T20:36:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-22T20:36:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-22T20:36:56Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-22T20:36:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-22T20:36:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-22T20:36:56Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-22T20:36:56Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-22T20:36:56Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-10-22T20:36:56Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-22T20:36:56Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-22T20:36:56Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-22T20:36:56Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\State.json' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Bloxstrap.JsonManager`1.Save()
   at Bloxstrap.Bootstrapper.ApplyModifications()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()

### Bloxstrap Log

```text
2024-10-22T20:36:39Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-22T20:36:39Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 12:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-22T20:36:39Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-22T20:36:39Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-22T20:36:39Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-22T20:36:39Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241022T203639Z.log
2024-10-22T20:36:39Z [Logger::Initialize] Failed to initialize because Bloxstrap cannot write to %UserProfile%\AppData\Local\Bloxstrap\Logs
2024-10-22T20:36:39Z [Frontend::ShowMessageBox] Файл журнала не будет написан для этого запуска, потому что Bloxstrap не может записать в папку в '%UserProfile%\AppData\Local\Bloxstrap\Logs'
2024-10-22T20:36:45Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-22T20:36:45Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-22T20:36:45Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-22T20:36:45Z [JsonManager<State>::Load] Loaded successfully!
2024-10-22T20:36:45Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-22T20:36:45Z [FastFlagManager::Load] Loaded successfully!
2024-10-22T20:36:45Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-22T20:36:55Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-22T20:36:55Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-22T20:36:55Z [Bootstrapper::Run] Running bootstrapper
2024-10-22T20:36:55Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-22T20:36:55Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-22T20:36:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-22T20:36:55Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-22T20:36:55Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-22T20:36:55Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-22T20:36:55Z [Bootstrapper::Run] Connectivity check finished
2024-10-22T20:36:55Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-22T20:36:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-22T20:36:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-22T20:36:56Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-22T20:36:56Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-22T20:36:56Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-22T20:36:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-22T20:36:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-22T20:36:56Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-22T20:36:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-22T20:36:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-9dbf9780562444e1-rbxPkgManifest.txt
2024-10-22T20:36:56Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-22T20:36:56Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-22T20:36:56Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-10-22T20:36:56Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-22T20:36:56Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-22T20:36:56Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-22T20:36:56Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\State.json' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Bloxstrap.JsonManager`1.Save()
   at Bloxstrap.Bootstrapper.ApplyModifications()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by pizzaboxer** [comment]
Check your antivirus to ensure it's not restricting Bloxstrap's ability to write files to disk
