### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\hhoa0.GBN\AppData\Local\Roblox\logs' is denied.

### ISSUE THREAD

**Issue by Ellopeople543** [bloxstraplabs/bloxstrap#3434]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v1.1

### What problem did you encounter?

I can't open my roblox with and without blox strap, please need help fixing.

### Bloxstrap Log

```text
2024-10-24T06:03:58Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-24T06:03:58Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 7:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-24T06:03:58Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-24T06:03:58Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-24T06:03:58Z [App::OnStartup] WindowsStartMenu path is D:\hhoa0\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-24T06:03:58Z [LaunchSettings] Identifier 'player' is active with data
2024-10-24T06:03:58Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241024T060358Z.log
2024-10-24T06:03:58Z [Logger::Initialize] Finished initializing!
2024-10-24T06:03:58Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-24T06:03:58Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-24T06:03:58Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-24T06:03:58Z [JsonManager<State>::Load] Loaded successfully!
2024-10-24T06:03:58Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-24T06:03:58Z [FastFlagManager::Load] Loaded successfully!
2024-10-24T06:03:58Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-24T06:03:58Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-24T06:03:58Z [Bootstrapper::Run] Running bootstrapper
2024-10-24T06:03:58Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-24T06:03:58Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-24T06:03:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-24T06:03:58Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-24T06:04:00Z [Deployment::TestConnection<https://setup-ak.rbxcdn.com>] Connecting...
2024-10-24T06:04:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/versionStudio
2024-10-24T06:04:00Z [Deployment::TestConnection<https://setup-aws.rbxcdn.com>] Connecting...
2024-10-24T06:04:00Z [Deployment::TestConnection<https://roblox-setup.cachefly.net>] Connecting...
2024-10-24T06:04:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://roblox-setup.cachefly.net/versionStudio
2024-10-24T06:04:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-aws.rbxcdn.com/versionStudio
2024-10-24T06:04:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup-aws.rbxcdn.com/versionStudio
2024-10-24T06:04:00Z [Deployment::TestConnection<https://roblox-setup.cachefly.net>] Connectivity test cancelled.
2024-10-24T06:04:00Z [Deployment::InitializeConnectivity] Got https://setup-aws.rbxcdn.com as the optimal base URL
2024-10-24T06:04:00Z [Bootstrapper::Run] Connectivity check finished
2024-10-24T06:04:00Z [Deployment::TestConnection<https://setup-ak.rbxcdn.com>] Connectivity test cancelled.
2024-10-24T06:04:00Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connectivity test cancelled.
2024-10-24T06:04:00Z [Bootstrapper::CheckForUpdates] More than one Bloxstrap instance running, aborting update check
2024-10-24T06:04:00Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-24T06:04:00Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-24T06:04:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-24T06:04:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-24T06:04:00Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-24T06:04:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-aws.rbxcdn.com/version-4e3b062d6e584043-rbxPkgManifest.txt
2024-10-24T06:04:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup-aws.rbxcdn.com/version-4e3b062d6e584043-rbxPkgManifest.txt
2024-10-24T06:04:00Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-24T06:04:00Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-24T06:04:00Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-10-24T06:04:00Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-24T06:04:00Z [JsonManager<State>::Save] Save complete!
2024-10-24T06:04:00Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-10-24T06:04:00Z [Bootstrapper::SetStatus] Starting {product}...
2024-10-24T06:04:00Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-24T06:04:00Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-24T06:04:00Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Roblox\logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by Ellopeople543** [comment]
I just need my roblox to work again I didn't have issue with opening it this morning.

**Comment by Thisisdevif** [comment]
try reinstall it

**Comment by pizzaboxer** [comment]
Are you trying to install Roblox on your school computer?
