### ISSUE TITLE
[BUG] cant open roblox

### ISSUE THREAD

**Issue by alchemistGuy** [bloxstraplabs/bloxstrap#3446]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

when i launch roblox i get this 
![i](https://github.com/user-attachments/assets/599c6088-bac8-45d8-8f74-05d4b6ed77e1)

i cant play roblox at all unless i uninstall bloxstrap 
this only started happening today after i got an issue about roblox graphics changing on its own 

### Bloxstrap Log

```text
2024-10-24T15:13:23Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-24T15:13:23Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 10:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-24T15:13:23Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-24T15:13:23Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-24T15:13:23Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-24T15:13:23Z [LaunchSettings] Identifier 'player' is active
2024-10-24T15:13:23Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241024T151323Z.log
2024-10-24T15:13:23Z [Logger::Initialize] Finished initializing!
2024-10-24T15:13:23Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-24T15:13:23Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-24T15:13:23Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-24T15:13:23Z [JsonManager<State>::Load] Loaded successfully!
2024-10-24T15:13:23Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-24T15:13:23Z [FastFlagManager::Load] Loaded successfully!
2024-10-24T15:13:23Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-24T15:13:23Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-24T15:13:23Z [Bootstrapper::Run] Running bootstrapper
2024-10-24T15:13:23Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-24T15:13:23Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-24T15:13:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-24T15:13:23Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-24T15:13:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-24T15:13:24Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-24T15:13:24Z [Bootstrapper::Run] Connectivity check finished
2024-10-24T15:13:24Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-24T15:13:24Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-24T15:13:24Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-24T15:13:24Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-24T15:13:24Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-24T15:13:24Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-24T15:13:24Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-24T15:13:24Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-24T15:13:24Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-24T15:13:24Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-4e3b062d6e584043-rbxPkgManifest.txt
2024-10-24T15:13:24Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-4e3b062d6e584043-rbxPkgManifest.txt
2024-10-24T15:13:24Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-10-24T15:13:28Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-24T15:13:28Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-24T15:13:28Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-24T15:13:28Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-24T15:13:28Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-24T15:13:28Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-24T15:13:28Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-24T15:13:28Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-10-24T15:13:28Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-24T15:13:28Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-24T15:13:29Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-24T15:13:29Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-24T15:13:29Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-24T15:13:29Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-24T15:13:29Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-24T15:13:30Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-24T15:13:30Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-24T15:13:30Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-10-24T15:13:30Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-10-24T15:13:31Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-24T15:13:31Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-24T15:13:31Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-10-24T15:13:32Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-24T15:13:32Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-10-24T15:13:32Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-10-24T15:13:32Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-24T15:13:32Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-24T15:13:32Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-10-24T15:13:32Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-24T15:13:33Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-24T15:13:33Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-24T15:13:33Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-24T15:13:33Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-24T15:13:33Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-24T15:13:33Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-24T15:13:35Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-24T15:13:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-24T15:13:35Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-24T15:13:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-24T15:13:36Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-24T15:13:36Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-24T15:13:36Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-24T15:13:36Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-24T15:13:36Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-24T15:13:36Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-24T15:13:36Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-24T15:13:36Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-24T15:13:42Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-24T15:13:48Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-24T15:13:48Z [Bootstrapper::UpgradeRoblox] Writing AppSettings.xml...
2024-10-24T15:13:48Z [Bootstrapper::UpgradeRoblox] Registering approximate program size...
2024-10-24T15:13:48Z [RegistryKeyEx::SetValueSafe] Writing '445495' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\EstimatedSize
2024-10-24T15:13:48Z [Bootstrapper::UpgradeRoblox] Registered as 445495 KB
2024-10-24T15:13:48Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-24T15:13:48Z [JsonManager<State>::Save] Save complete!
2024-10-24T15:13:48Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] Begin font check
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] End font check
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json has been copied to the version folder
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] content\fonts\CustomFont.ttf has been copied to the version folder
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg has been copied to the version folder
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] content\fonts\families\AccanthisADFStd.json has been copied to the version folder
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] content\fonts\families\AmaticSC.json has been copied to the version folder
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Arimo.json has been copied to the version folder
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Balthazar.json has been copied to the version folder
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Bangers.json has been copied to the version folder
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] content\fonts\families\BuilderSans.json has been copied to the version folder
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] content\fonts\families\ComicNeueAngular.json has been copied to the version folder
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] content\fonts\families\Creepster.json has been copied to the version folder
2024-10-24T15:13:48Z [Bootstrapper::ApplyModifications] content\fonts\families\DenkOne.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Fondamento.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\FredokaOne.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\GrenzeGotisch.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Guru.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\HighwayGothic.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Inconsolata.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\IndieFlower.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\JosefinSans.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Jura.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Kalam.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\LegacyArial.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\LegacyArimo.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\LuckiestGuy.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Merriweather.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Michroma.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Montserrat.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Nunito.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Oswald.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\PatrickHand.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\PermanentMarker.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\PressStart2P.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Roboto.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\RobotoCondensed.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\RobotoMono.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\RomanAntique.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Sarpanch.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\SourceSansPro.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\SpecialElite.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\TitilliumWeb.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Ubuntu.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\fonts\families\Zekton.json has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\textures\Cursors\KeyboardMouse\ArrowCursor.png has been copied to the version folder
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] content\textures\Cursors\KeyboardMouse\ArrowFarCursor.png has been copied to the version folder
2024-10-24T15:13:49Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-24T15:13:49Z [JsonManager<State>::Save] Save complete!
2024-10-24T15:13:49Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-10-24T15:13:49Z [Bootstrapper::SetStatus] Starting {product}...
2024-10-24T15:13:49Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-24T15:13:49Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-24T15:13:49Z [App::FinalizeExceptionHandling] System.ComponentModel.Win32Exception (740): An error occurred trying to start process '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player'. The requested operation requires elevation.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by pizzaboxer** [comment]
Issue addressed in Wiki
