### ISSUE TITLE
[BUG] not possible to finish operation because file contains a virus or pottentially unwanted software

### ISSUE THREAD

**Issue by EnzoCamilo** [bloxstraplabs/bloxstrap#3456]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

while attempting to open roblox i was greeted with the error 
`System.IO.IOException: Não foi possível concluir a operação com êxito porque o arquivo contém um vírus ou software possivelmente indesejado. : 'C:\Users\User\AppData\Local\Bloxstrap\Downloads\50e0fc0c3acbc05c24281840f541418f'`
which roughly translates to
`System.IO.IOException: it was not possible to conclude the operation because the file contains a virus or potentially unwanted software. : 'C:\Users\User\AppData\Local\Bloxstrap\Downloads\50e0fc0c3acbc05c24281840f541418f'`

### Bloxstrap Log

```text
2024-10-24T21:30:47Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-24T21:30:47Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 6:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-24T21:30:47Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-24T21:30:47Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-24T21:30:47Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-24T21:30:47Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241024T213047Z.log
2024-10-24T21:30:47Z [Logger::Initialize] Finished initializing!
2024-10-24T21:30:47Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-24T21:30:47Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-24T21:30:47Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-24T21:30:47Z [JsonManager<State>::Load] Loaded successfully!
2024-10-24T21:30:47Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-24T21:30:47Z [FastFlagManager::Load] Loaded successfully!
2024-10-24T21:30:49Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-24T21:30:49Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-24T21:30:49Z [Bootstrapper::Run] Running bootstrapper
2024-10-24T21:30:49Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-24T21:30:49Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-24T21:30:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-24T21:30:49Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-24T21:30:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-24T21:30:49Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-24T21:30:49Z [Bootstrapper::Run] Connectivity check finished
2024-10-24T21:30:49Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-24T21:30:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-24T21:30:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-24T21:30:50Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-24T21:30:50Z [Bootstrapper::GetLatestVersionInfo] Got channel as zchunkexperimenteight
2024-10-24T21:30:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zchunkexperimenteight
2024-10-24T21:30:50Z [Deployment::GetInfo] Getting deploy info for channel zchunkexperimenteight
2024-10-24T21:30:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zchunkexperimenteight
2024-10-24T21:30:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zchunkexperimenteight
2024-10-24T21:30:50Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-24T21:30:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-24T21:30:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-24T21:30:50Z [RegistryKeyEx::SetValueSafe] Writing 'zchunkexperimenteight' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-24T21:30:50Z [ApplicationSettings::Fetch.PCClientBootstrapper.zchunkexperimenteight] Fetching fast flags
2024-10-24T21:30:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zchunkexperimenteight
2024-10-24T21:30:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zchunkexperimenteight
2024-10-24T21:30:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-bfeaf56d23524684-rbxPkgManifest.txt
2024-10-24T21:30:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-bfeaf56d23524684-rbxPkgManifest.txt
2024-10-24T21:30:50Z [Bootstrapper::SetStatus] Installing {product}...
2024-10-24T21:30:50Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zchunkexperimenteight
2024-10-24T21:30:51Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-10-24T21:30:51Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-bfeaf56d23524684-RobloxApp.zip
2024-10-24T21:30:51Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-bfeaf56d23524684-RobloxApp.zip
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (87219790 bytes total)
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-10-24T21:30:54Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-24T21:30:54Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-24T21:30:55Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-24T21:30:55Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-24T21:30:55Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-24T21:30:55Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-24T21:30:55Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-24T21:30:55Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-24T21:30:55Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-24T21:30:55Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-24T21:30:55Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-24T21:30:55Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-24T21:30:55Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-24T21:30:56Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-24T21:30:56Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-24T21:30:56Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-24T21:30:57Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-24T21:31:00Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-24T21:31:04Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-24T21:31:04Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-24T21:31:04Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-24T21:31:04Z [App::FinalizeExceptionHandling] System.IO.IOException: Não foi possível concluir a operação com êxito porque o arquivo contém um vírus ou software possivelmente indesejado. : '%UserProfile%\AppData\Local\Bloxstrap\Downloads\50e0fc0c3acbc05c24281840f541418f'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass33_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by joeythebugle** [comment]
Seems to be a new issues considering I cant find anything else on it. Hopefully theres a fix soon but for now we gotta use the Roblox launcher :(

**Comment by EnzoCamilo** [comment]
i can't use the normal one either bc for some reason mine just keeps reinstalling every time i press play lol

**Comment by howevernonetheless** [comment]
exact same problem here, even same windows language. every time i run bloxstrap it gives the exact same error

**Comment by EvilJason123** [comment]
same here my roblox legit just updated and i wanted to play a game and bloxstrap just gave like hey we cant complete this cuz they may be a virus or unwanted thingy in the downloads of bloxstrap of this number 50e0fc0c3acbc05c24281840f541418f

**Comment by pizzaboxer** [comment]
Your antivirus is detecting Roblox as malware, for some reason. What antivirus are you using? Are you just using Windows Defender?

**Comment by EvilJason123** [comment]
> Your antivirus is detecting Roblox as malware, for some reason. What antivirus are you using? Are you just using Windows Defender?

just windows defender and even if i uninstalled bloxstrap and tried it with regular roblox player launcher my window defender still identify it as a virus

**Comment by EnzoCamilo** [comment]
Only bitdefender, oddly enough it is detecting it as ransomware or
something like that

Em qui., 24 de out. de 2024, 20:44, EvilJason123 ***@***.***>
escreveu:

**Comment by EvilJason123** [comment]
> > Your antivirus is detecting Roblox as malware, for some reason. What antivirus are you using? Are you just using Windows Defender?
> 
> just windows defender and even if i uninstalled bloxstrap and tried it with regular roblox player launcher my window defender still identify it as a virus

so whats the plan should i just let it allow on windows defender or shall i just wait til an fix is out or something cuz this is really spooky

**Comment by pizzaboxer** [comment]
I'd recommend you add Roblox/Bloxstrap's download folder as a folder exception in your antivirus.

Roblox's is at `%localappdata%\Roblox\Downloads\`
Ourss is at `%localappdata%\Bloxstrap\Downloads\` (depends where you've installed bloxstrap to)

**Comment by EvilJason123** [comment]
NVM to fix it just Allow it on your windows defender and it is safe i tested it and it worked le bloxstrap is running as normal !
SAFE

**Comment by EnzoCamilo** [comment]
the issue seems to have fixed itself, though i do not know if i should close this issue or not lol

**Comment by pizzaboxer** [comment]
Okay no it's still happening for a bunch of people, but whatever

**Comment by DesignerTea** [comment]
man i tried everything and its still not fixed

**Comment by dimakliuev** [comment]
i tried everything nothing helped if you guys find a way pls add me on discord: dimsupr

**Comment by abdalrhmanf1** [comment]
a
