### ISSUE TITLE
[BUG] an exception occurred while running bloxstrap

### ISSUE THREAD

**Issue by Woxihuanzonghesepifudejiahuo** [bloxstraplabs/bloxstrap#3457]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

![Screenshot 2024-10-25 054708](https://github.com/user-attachments/assets/e2a140cc-a89a-472a-88d5-7dc689320d32)

### Bloxstrap Log

```text
2024-10-24T14:09:57Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-24T14:09:57Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 5:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-24T14:09:57Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-24T14:09:57Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-24T14:09:57Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-24T14:09:57Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241024T140957Z.log
2024-10-24T14:09:57Z [Logger::Initialize] Finished initializing!
2024-10-24T14:09:57Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-24T14:09:57Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-24T14:09:57Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-24T14:09:57Z [JsonManager<State>::Load] Loaded successfully!
2024-10-24T14:09:57Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-24T14:09:57Z [FastFlagManager::Load] Loaded successfully!
2024-10-24T14:10:00Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-24T14:10:00Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-24T14:10:00Z [Bootstrapper::Run] Running bootstrapper
2024-10-24T14:10:00Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-24T14:10:00Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-24T14:10:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-24T14:10:00Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-24T14:10:02Z [Deployment::TestConnection<https://roblox-setup.cachefly.net>] Connecting...
2024-10-24T14:10:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://roblox-setup.cachefly.net/versionStudio
2024-10-24T14:10:02Z [Deployment::TestConnection<https://setup-ak.rbxcdn.com>] Connecting...
2024-10-24T14:10:02Z [Deployment::TestConnection<https://setup-aws.rbxcdn.com>] Connecting...
2024-10-24T14:10:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/versionStudio
2024-10-24T14:10:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-aws.rbxcdn.com/versionStudio
2024-10-24T14:10:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup-ak.rbxcdn.com/versionStudio
2024-10-24T14:10:03Z [Deployment::TestConnection<https://setup-aws.rbxcdn.com>] Connectivity test cancelled.
2024-10-24T14:10:03Z [Deployment::InitializeConnectivity] Got https://setup-ak.rbxcdn.com as the optimal base URL
2024-10-24T14:10:03Z [Bootstrapper::Run] Connectivity check finished
2024-10-24T14:10:03Z [Deployment::TestConnection<https://roblox-setup.cachefly.net>] Connectivity test cancelled.
2024-10-24T14:10:03Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connectivity test cancelled.
2024-10-24T14:10:03Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-24T14:10:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-24T14:10:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-24T14:10:11Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-24T14:10:11Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-24T14:10:11Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-24T14:10:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-24T14:10:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-24T14:10:12Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-24T14:10:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-rbxPkgManifest.txt
2024-10-24T14:10:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-rbxPkgManifest.txt
2024-10-24T14:10:12Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-10-24T14:10:12Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-10-24T14:10:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-RobloxApp.zip
2024-10-24T14:10:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-RobloxApp.zip
2024-10-24T14:14:11Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (86805923 bytes total)
2024-10-24T14:14:11Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-24T14:14:11Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-24T14:14:11Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-24T14:14:11Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-10-24T14:14:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-content-configs.zip
2024-10-24T14:14:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-content-configs.zip
2024-10-24T14:14:11Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-24T14:14:11Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (256192 bytes total)
2024-10-24T14:14:11Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-24T14:14:11Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-24T14:14:11Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-24T14:14:11Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-24T14:14:11Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-24T14:14:11Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-24T14:14:11Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-24T14:14:11Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-24T14:14:11Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-10-24T14:14:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-shaders.zip
2024-10-24T14:14:11Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-24T14:14:11Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-24T14:14:11Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-24T14:14:11Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-24T14:14:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-shaders.zip
2024-10-24T14:14:12Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-24T14:14:12Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-24T14:14:14Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-24T14:14:23Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (9165172 bytes total)
2024-10-24T14:14:23Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-24T14:14:23Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-24T14:14:23Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-24T14:14:23Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-24T14:14:23Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-24T14:14:23Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-24T14:14:23Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-24T14:14:23Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-24T14:14:23Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-24T14:14:23Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-24T14:14:23Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-24T14:14:23Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-24T14:14:23Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-24T14:14:23Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-24T14:14:23Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-10-24T14:14:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-extracontent-luapackages.zip
2024-10-24T14:14:23Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-24T14:14:24Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-24T14:14:24Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-24T14:14:24Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-extracontent-luapackages.zip
2024-10-24T14:14:24Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-24T14:14:24Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-24T14:14:35Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-24T14:14:35Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (9548798 bytes total)
2024-10-24T14:14:35Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-10-24T14:14:35Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-extracontent-translations.zip
2024-10-24T14:14:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-24T14:14:35Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-extracontent-translations.zip
2024-10-24T14:14:36Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-24T14:14:36Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (484128 bytes total)
2024-10-24T14:14:36Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-24T14:14:36Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-10-24T14:14:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-extracontent-models.zip
2024-10-24T14:14:36Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-24T14:14:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup-ak.rbxcdn.com/version-4e3b062d6e584043-extracontent-models.zip
2024-10-24T14:15:01Z [Bootstrapper::DownloadPackage.extracontent-models.zip] An exception occurred after downloading 9197507 bytes. (1/5)
2024-10-24T14:15:01Z [Bootstrapper::DownloadPackage.extracontent-models.zip] System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-10-24T14:15:01Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Retrying download over HTTP...
2024-10-24T14:15:01Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup-ak.rbxcdn.com/version-4e3b062d6e584043-extracontent-models.zip
2024-10-24T14:15:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK http://setup-ak.rbxcdn.com/version-4e3b062d6e584043-extracontent-models.zip
2024-10-24T14:34:18Z [Bootstrapper::DownloadPackage.extracontent-models.zip] An exception occurred after downloading 9188387 bytes. (2/5)
2024-10-24T14:34:18Z [Bootstrapper::DownloadPackage.extracontent-models.zip] System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-10-24T14:34:19Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup-ak.rbxcdn.com/version-4e3b062d6e584043-extracontent-models.zip
2024-10-24T14:34:19Z [Bootstrapper::DownloadPackage.extracontent-models.zip] An exception occurred after downloading 0 bytes. (3/5)
2024-10-24T14:34:19Z [Bootstrapper::DownloadPackage.extracontent-models.zip] System.Net.Http.HttpRequestException: No such host is known. (setup-ak.rbxcdn.com:80)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-10-24T14:34:19Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup-ak.rbxcdn.com/version-4e3b062d6e584043-extracontent-models.zip
2024-10-24T14:34:19Z [Bootstrapper::DownloadPackage.extracontent-models.zip] An exception occurred after downloading 0 bytes. (4/5)
2024-10-24T14:34:19Z [Bootstrapper::DownloadPackage.extracontent-models.zip] System.Net.Http.HttpRequestException: No such host is known. (setup-ak.rbxcdn.com:80)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-10-24T14:34:19Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup-ak.rbxcdn.com/version-4e3b062d6e584043-extracontent-models.zip
2024-10-24T14:34:19Z [Bootstrapper::DownloadPackage.extracontent-models.zip] An exception occurred after downloading 0 bytes. (5/5)
2024-10-24T14:34:19Z [Bootstrapper::DownloadPackage.extracontent-models.zip] System.Net.Http.HttpRequestException: No such host is known. (setup-ak.rbxcdn.com:80)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-10-24T14:34:19Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-24T14:34:19Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-24T14:34:19Z [App::FinalizeExceptionHandling] System.Net.Http.HttpRequestException: No such host is known. (setup-ak.rbxcdn.com:80)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by pizzaboxer** [comment]
Antivirus firewall issue. Please check to make sure there's no restrictions being placed on Bloxstrap's ability to connect to the internet.
