### ISSUE TITLE
[BUG] Roblox game is not showing on my discord profile because of an error.

### ISSUE THREAD

**Issue by wouzers** [bloxstraplabs/bloxstrap#3461]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

Every time that I opened up a Roblox game there was an error saying the following: 

"Your current game will not show on your Discord presence because an error occurred when loading the game information."
"The requested address is not valid in its context. (games.roblox.com:443)"

![image_2024-10-24_210453905](https://github.com/user-attachments/assets/d0a80d47-db6f-4fbb-818a-36cd84c62f38)

Note: All privacy settings on Discord are enabled

### Bloxstrap Log

```text
2024-10-25T01:04:27Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-25T01:04:27Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 5:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-25T01:04:27Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-25T01:04:27Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-25T01:04:27Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-25T01:04:27Z [LaunchSettings] Identifier 'watcher' is active with data
2024-10-25T01:04:27Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241025T010427Z.log
2024-10-25T01:04:28Z [Logger::Initialize] Finished initializing!
2024-10-25T01:04:28Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-25T01:04:28Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-25T01:04:28Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-25T01:04:28Z [JsonManager<State>::Load] Loaded successfully!
2024-10-25T01:04:28Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-25T01:04:28Z [FastFlagManager::Load] Loaded successfully!
2024-10-25T01:04:28Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-10-25T01:04:28Z [DiscordRichPresence] Established connection with Discord RPC
2024-10-25T01:04:28Z [ActivityWatcher::Start] Opened %UserProfile%\AppData\Local\Roblox\logs\0.648.0.6480781_20241025T010426Z_Player_53566_last.log
2024-10-25T01:04:28Z [ActivityWatcher::ReadLogEntry] Read 50 log entries
2024-10-25T01:04:29Z [DiscordRichPresence] Received ready from user _wouzers (730600109720600618)
2024-10-25T01:04:29Z [ActivityWatcher::ReadLogEntry] Read 100 log entries
2024-10-25T01:04:29Z [ActivityWatcher::ReadLogEntry] Joining Game (13621938427/447c8588-4013-4e4b-8590-99465a0c96b8)
2024-10-25T01:04:29Z [ActivityWatcher::ReadLogEntry] Server is UDMUX protected (13621938427/447c8588-4013-4e4b-8590-99465a0c96b8)
2024-10-25T01:04:29Z [ActivityWatcher::ReadLogEntry] Joined Game (13621938427/447c8588-4013-4e4b-8590-99465a0c96b8)
2024-10-25T01:04:29Z [ActivityWatcher::ReadLogEntry] Read 150 log entries
2024-10-25T01:04:29Z [DiscordRichPresence::SetCurrentGame] Setting presence for Place ID 13621938427
2024-10-25T01:04:29Z [HttpClientLoggingHandler::ProcessRequest] GET https://games.roblox.com/v1/games?universeIds=4730278139
2024-10-25T01:04:29Z [DiscordRichPresence::SetCurrentGame] System.Net.Http.HttpRequestException: The requested address is not valid in its context. (games.roblox.com:443)
 ---> System.Net.Sockets.SocketException (10049): The requested address is not valid in its context.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.Models.Entities.UniverseDetails.FetchBulk(String ids)
   at Bloxstrap.Integrations.DiscordRichPresence.SetCurrentGame()
2024-10-25T01:04:29Z [Frontend::ShowMessageBox] Your current game will not show on your Discord presence because an error occurred when loading the game information.

The requested address is not valid in its context. (games.roblox.com:443)
2024-10-25T01:04:49Z [ActivityWatcher::ReadLogEntry] Read 200 log entries
2024-10-25T01:04:49Z [ActivityWatcher::ReadLogEntry] Read 250 log entries
2024-10-25T01:04:49Z [ActivityWatcher::ReadLogEntry] Read 300 log entries
2024-10-25T01:04:50Z [ActivityWatcher::ReadLogEntry] Read 350 log entries
```

**Comment by MrT-tak** [comment]
DNS? Roblox down? 
Please let us know if it's fixed now.

**Comment by wouzers** [comment]
No, it is still giving me the same error.
![image_2024-10-25_152213896](https://github.com/user-attachments/assets/a2793f6e-a3cb-4b49-84d1-45200e7359c6)

**Comment by wouzers** [comment]
this is the recent log file
[Bloxstrap_20241025T192029Z.log](https://github.com/user-attachments/files/17526681/Bloxstrap_20241025T192029Z.log)

**Comment by pizzaboxer** [comment]
This is an issue with your internet connection. Could be a VPN configuration issue, could be an antivirus firewall causing issues.
