### ISSUE TITLE
[BUG] System.IO.IOException: Não foi possível concluir a operação com êxito porque o arquivo contém um vírus ou software possivelmente indesejado. : 'C:\Users\\AppData\Local\Bloxstrap\Downloads\34b53a6e6c2540f8699e50ac9f2cfed6'

### ISSUE THREAD

**Issue by lSynax** [bloxstraplabs/bloxstrap#3472]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

![Capturar2](https://github.com/user-attachments/assets/ee55edae-2158-4a85-b109-e69bcc3af63a)
![Capturar](https://github.com/user-attachments/assets/00e93cf7-3781-4ed4-aca7-d95c8ac3f2e6)

### Bloxstrap Log

```text
2024-10-25T19:20:02Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-25T19:20:02Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 6:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-25T19:20:02Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-25T19:20:02Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-25T19:20:02Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-25T19:20:02Z [LaunchSettings] Identifier 'player' is active with data
2024-10-25T19:20:02Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241025T192002Z.log
2024-10-25T19:20:02Z [Logger::Initialize] Finished initializing!
2024-10-25T19:20:02Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-25T19:20:03Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-25T19:20:03Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-25T19:20:03Z [JsonManager<State>::Load] Loaded successfully!
2024-10-25T19:20:03Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-25T19:20:03Z [FastFlagManager::Load] Loaded successfully!
2024-10-25T19:20:03Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-25T19:20:03Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-25T19:20:03Z [BootstrapperIconEx::GetIcon] Warning: custom icon is not set.
2024-10-25T19:20:03Z [BootstrapperIconEx::GetIcon] Warning: custom icon is not set.
2024-10-25T19:20:03Z [Bootstrapper::Run] Running bootstrapper
2024-10-25T19:20:03Z [Bootstrapper::SetStatus] Conectando-se ao Roblox...
2024-10-25T19:20:03Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-25T19:20:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-25T19:20:03Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-25T19:20:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-25T19:20:05Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-25T19:20:05Z [Bootstrapper::Run] Connectivity check finished
2024-10-25T19:20:05Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-25T19:20:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-25T19:20:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-25T19:20:05Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-25T19:20:05Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-25T19:20:05Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-25T19:20:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-25T19:20:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-25T19:20:05Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-25T19:20:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-4ffdeb3e393e469e-rbxPkgManifest.txt
2024-10-25T19:20:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-4ffdeb3e393e469e-rbxPkgManifest.txt
2024-10-25T19:20:05Z [Bootstrapper::SetStatus] Instalando {product}...
2024-10-25T19:20:07Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-25T19:20:07Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-25T19:20:07Z [App::FinalizeExceptionHandling] System.IO.IOException: Não foi possível concluir a operação com êxito porque o arquivo contém um vírus ou software possivelmente indesejado. : '%UserProfile%\AppData\Local\Bloxstrap\Downloads\34b53a6e6c2540f8699e50ac9f2cfed6'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at Bloxstrap.Utility.MD5Hash.FromFile(String filename)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by ygxrr** [comment]
Not bloxstrap issue, that's a false-positive.

**Comment by pizzaboxer** [comment]
Not Bloxstrap issue.
