### ISSUE TITLE
Potential Virus Detected

### ISSUE THREAD

**Issue by v1rinhus** [bloxstraplabs/bloxstrap#3479]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.0

### What problem did you encounter?

System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\Xeep6\AppData\Local\Bloxstrap\Downloads\50e0fc0c3acbc05c24281840f541418f'

### Bloxstrap Log

```text
2024-10-25T23:09:11Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-25T23:09:11Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 6:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-25T23:09:11Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-25T23:09:11Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-25T23:09:11Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-25T23:09:11Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241025T230911Z.log
2024-10-25T23:09:11Z [Logger::Initialize] Finished initializing!
2024-10-25T23:09:11Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-25T23:09:12Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-25T23:09:12Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-25T23:09:12Z [JsonManager<State>::Load] Loaded successfully!
2024-10-25T23:09:12Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-25T23:09:12Z [FastFlagManager::Load] Loaded successfully!
2024-10-25T23:10:17Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-25T23:10:17Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-25T23:10:17Z [Bootstrapper::Run] Running bootstrapper
2024-10-25T23:10:17Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-25T23:10:17Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-25T23:10:17Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-25T23:10:17Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-25T23:10:17Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-25T23:10:17Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-25T23:10:17Z [Bootstrapper::Run] Connectivity check finished
2024-10-25T23:10:17Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-25T23:10:17Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-25T23:10:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-25T23:10:18Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-25T23:10:18Z [Bootstrapper::GetLatestVersionInfo] Got channel as zchunkexperimenteight
2024-10-25T23:10:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zchunkexperimenteight
2024-10-25T23:10:18Z [Deployment::GetInfo] Getting deploy info for channel zchunkexperimenteight
2024-10-25T23:10:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zchunkexperimenteight
2024-10-25T23:10:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zchunkexperimenteight
2024-10-25T23:10:18Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-25T23:10:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-25T23:10:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-25T23:10:18Z [RegistryKeyEx::SetValueSafe] Writing 'zchunkexperimenteight' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-25T23:10:18Z [ApplicationSettings::Fetch.PCClientBootstrapper.zchunkexperimenteight] Fetching fast flags
2024-10-25T23:10:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zchunkexperimenteight
2024-10-25T23:10:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zchunkexperimenteight
2024-10-25T23:10:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-bfeaf56d23524684-rbxPkgManifest.txt
2024-10-25T23:10:18Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zchunkexperimenteight
2024-10-25T23:10:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-bfeaf56d23524684-rbxPkgManifest.txt
2024-10-25T23:10:18Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-10-25T23:10:19Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-10-25T23:10:19Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-bfeaf56d23524684-RobloxApp.zip
2024-10-25T23:10:19Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-bfeaf56d23524684-RobloxApp.zip
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (87219790 bytes total)
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-25T23:10:27Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-25T23:10:27Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-25T23:10:27Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-25T23:10:28Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-25T23:10:28Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-25T23:10:28Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-25T23:10:28Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-25T23:10:28Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-25T23:10:29Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-25T23:10:32Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-25T23:10:32Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-25T23:10:32Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-25T23:10:32Z [App::FinalizeExceptionHandling] System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. : '%UserProfile%\AppData\Local\Bloxstrap\Downloads\50e0fc0c3acbc05c24281840f541418f'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass33_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by pizzaboxer** [comment]
[False positive, and not a Bloxstrap issue.](https://github.com/bloxstraplabs/bloxstrap/wiki/Malware-detected-when-trying-to-upgrade-Roblox)
