### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'RobloxCrashHandler.exe' is denied.

### ISSUE THREAD

**Issue by ryujinlovely** [bloxstraplabs/bloxstrap#3489]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.80

### What problem did you encounter?

Bom o problema é o seguinte, eu não consigo entrar no bloxtrap, por incrível que pareça. Por favor arrumem este problema, minha filha de 5 anos está a querer jogar faz tempo, resolvam logo.

### Bloxstrap Log

```text
2024-10-26T20:16:54Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-26T20:16:54Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 6:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-26T20:16:54Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-26T20:16:54Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-26T20:16:54Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-26T20:16:54Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241026T201654Z.log
2024-10-26T20:16:54Z [Logger::Initialize] Finished initializing!
2024-10-26T20:16:54Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-26T20:16:54Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-26T20:16:54Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-26T20:16:54Z [JsonManager<State>::Load] Loaded successfully!
2024-10-26T20:16:54Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-26T20:16:54Z [FastFlagManager::Load] Loaded successfully!
2024-10-26T20:16:55Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-26T20:16:55Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-26T20:16:55Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-10-26T20:16:55Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Argument 'picture' must be a picture that can be used as a Icon.
   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-10-26T20:16:55Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-10-26T20:16:55Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Argument 'picture' must be a picture that can be used as a Icon.
   at System.Drawing.Icon.Initialize(Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-10-26T20:16:55Z [Bootstrapper::Run] Running bootstrapper
2024-10-26T20:16:55Z [Bootstrapper::SetStatus] Conectando-se ao Roblox...
2024-10-26T20:16:55Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-26T20:16:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-26T20:16:56Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-26T20:16:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-26T20:16:56Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-26T20:16:56Z [Bootstrapper::Run] Connectivity check finished
2024-10-26T20:16:56Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-26T20:16:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-26T20:16:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-26T20:16:56Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-26T20:16:56Z [Bootstrapper::GetLatestVersionInfo] Got channel as zchunkexperimenteight
2024-10-26T20:16:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zchunkexperimenteight
2024-10-26T20:16:56Z [Deployment::GetInfo] Getting deploy info for channel zchunkexperimenteight
2024-10-26T20:16:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zchunkexperimenteight
2024-10-26T20:16:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zchunkexperimenteight
2024-10-26T20:16:57Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-26T20:16:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-26T20:16:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-26T20:16:57Z [RegistryKeyEx::SetValueSafe] Writing 'zchunkexperimenteight' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-26T20:16:57Z [ApplicationSettings::Fetch.PCClientBootstrapper.zchunkexperimenteight] Fetching fast flags
2024-10-26T20:16:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zchunkexperimenteight
2024-10-26T20:16:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zchunkexperimenteight
2024-10-26T20:16:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-bfeaf56d23524684-rbxPkgManifest.txt
2024-10-26T20:16:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-bfeaf56d23524684-rbxPkgManifest.txt
2024-10-26T20:16:57Z [Bootstrapper::SetStatus] Atualizando {product}...
2024-10-26T20:16:57Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-26T20:16:57Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-26T20:16:57Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path 'RobloxCrashHandler.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by pizzaboxer** [comment]
Fixed in 2.8.1 (assuming so, reopen if not)
