### ISSUE TITLE
[BUG] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by opphunt** [bloxstraplabs/bloxstrap#3537]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

![Screenshot_255](https://github.com/user-attachments/assets/cdacbb70-6e46-4d6f-a150-10bb4537a4ba)

### Bloxstrap Log

```text
2024-10-29T21:35:53Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-29T21:35:53Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 2:44:37 PM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-29T21:35:53Z [App::OnStartup] Loaded from D:\Bloxstrap\Bloxstrap.exe
2024-10-29T21:35:53Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-29T21:35:53Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-29T21:35:53Z [Logger::Initialize] Initializing at D:\Bloxstrap\Logs\Bloxstrap_20241029T213553Z.log
2024-10-29T21:35:53Z [Logger::Initialize] Finished initializing!
2024-10-29T21:35:53Z [JsonManager<Settings>::Load] Loading from D:\Bloxstrap\Settings.json...
2024-10-29T21:35:53Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-29T21:35:53Z [JsonManager<State>::Load] Loading from D:\Bloxstrap\State.json...
2024-10-29T21:35:53Z [JsonManager<State>::Load] Loaded successfully!
2024-10-29T21:35:53Z [FastFlagManager::Load] Loading from D:\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-29T21:35:53Z [FastFlagManager::Load] Loaded successfully!
2024-10-29T21:35:53Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-10-29T21:35:55Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-29T21:35:55Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-29T21:35:55Z [Bootstrapper::Run] Running bootstrapper
2024-10-29T21:35:55Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-29T21:35:55Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-29T21:35:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-29T21:35:55Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-29T21:35:57Z [Deployment::TestConnection<https://setup-ak.rbxcdn.com>] Connecting...
2024-10-29T21:35:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/versionStudio
2024-10-29T21:35:57Z [Deployment::TestConnection<https://setup-aws.rbxcdn.com>] Connecting...
2024-10-29T21:35:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-aws.rbxcdn.com/versionStudio
2024-10-29T21:35:57Z [Deployment::TestConnection<https://roblox-setup.cachefly.net>] Connecting...
2024-10-29T21:35:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://roblox-setup.cachefly.net/versionStudio
2024-10-29T21:35:58Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-29T21:35:58Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-29T21:35:58Z [Bootstrapper::Run] Connectivity check finished
2024-10-29T21:35:58Z [Deployment::TestConnection<https://setup-aws.rbxcdn.com>] Connectivity test cancelled.
2024-10-29T21:35:58Z [Deployment::TestConnection<https://setup-ak.rbxcdn.com>] Connectivity test cancelled.
2024-10-29T21:35:58Z [Deployment::TestConnection<https://roblox-setup.cachefly.net>] Connectivity test cancelled.
2024-10-29T21:35:58Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-29T21:35:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-29T21:35:58Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-29T21:35:58Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-29T21:35:58Z [Bootstrapper::GetLatestVersionInfo] Got channel as zbeta
2024-10-29T21:35:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zbeta
2024-10-29T21:35:58Z [Deployment::GetInfo] Getting deploy info for channel zbeta
2024-10-29T21:35:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta
2024-10-29T21:35:58Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zbeta
2024-10-29T21:35:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta
2024-10-29T21:35:59Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-29T21:35:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-29T21:35:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-29T21:35:59Z [RegistryKeyEx::SetValueSafe] Writing 'zbeta' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-29T21:35:59Z [ApplicationSettings::Fetch.PCClientBootstrapper.zbeta] Fetching fast flags
2024-10-29T21:35:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zbeta
2024-10-29T21:35:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zbeta
2024-10-29T21:35:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-29T21:35:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-29T21:35:59Z [Bootstrapper::SetStatus] Installing {product}...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-10-29T21:36:00Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-29T21:36:00Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-29T21:36:01Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-29T21:36:01Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-29T21:36:01Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-29T21:36:01Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-29T21:36:01Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-29T21:36:01Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-29T21:36:01Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-29T21:36:01Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-29T21:36:02Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-29T21:36:02Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-29T21:36:02Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-29T21:36:02Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-29T21:36:02Z [App::FinalizeExceptionHandling] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass33_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by mathiameatie** [comment]
same here

**Comment by aqcz** [comment]
same

**Comment by nvrfia** [comment]
same problem for me

**Comment by Polegonic** [comment]
same

**Comment by vibcerr** [comment]
same same same same hi chat lets all eat something while we wait. popcorn or twizzlers anyone?

**Comment by aqcz** [comment]
its been 30 minutes without Dahood and im about to go crazy

**Comment by vibcerr** [comment]
NO DH FR IMA GO CRAZY ASWELL> if u really play dh tho use normal roblox

**Comment by vibcerr** [comment]
> its been 30 minutes without Dahood and im about to go crazy

roblox-player:1+launchmode:app+channel:production

DO THIS IN GOOGLE OR WHATEVER BROWSER

**Comment by aqcz** [comment]
why

**Comment by vibcerr** [comment]
> why
it fixes it

**Comment by aqcz** [comment]
i smell a rat

**Comment by vibcerr** [comment]
> why

hop on dh whats ur discord

**Comment by vibcerr** [comment]
> i smell a rat

add me; vibcerr. is my dc ill show

**Comment by Mikethemonkey08** [comment]
roblox-player:1+launchmode:app+channel:production // paste this into ur brower it fixes bloxstrap

**Comment by rekitrelt** [comment]
did not fix it

**Comment by Avuury** [comment]
just reinstall bloxtrap

**Comment by danyad22** [comment]
![1687985618_new_preview_603265_1592489701](https://github.com/user-attachments/assets/d14532ef-f98d-4761-b700-b1eee50edf0f)

**Comment by rekitrelt** [comment]
> just reinstall bloxtrap

Tried that, had to get 2.8.1

**Comment by neednovitec** [comment]
anyone find a fix?

**Comment by gavin252** [comment]
same

**Comment by gavin252** [comment]
no problem
