### ISSUE TITLE
[BUG] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by mino-max** [bloxstraplabs/bloxstrap#3540]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

Well hi i was about to play roblox when i ran into an era and obviously i went to find out what was the issue so i done that and downloaded v2.8.0 then i was going to play roblox again but another exception came up saying The given key 'content-platform-dictionaries.zip' was not present in the dictionary. And i do not know what this is so if you could please help me it would be much appreciated.

### Bloxstrap Log

```text
2024-10-29T21:40:02Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-29T21:40:02Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 10:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-29T21:40:02Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-29T21:40:02Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-29T21:40:02Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-29T21:40:02Z [LaunchSettings] Identifier 'player' is active with data
2024-10-29T21:40:02Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241029T214002Z.log
2024-10-29T21:40:02Z [Logger::Initialize] Finished initializing!
2024-10-29T21:40:02Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-29T21:40:02Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-29T21:40:02Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-29T21:40:02Z [JsonManager<State>::Load] Loaded successfully!
2024-10-29T21:40:02Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-29T21:40:02Z [FastFlagManager::Load] Loaded successfully!
2024-10-29T21:40:02Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-29T21:40:02Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-29T21:40:02Z [Bootstrapper::Run] Running bootstrapper
2024-10-29T21:40:02Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-29T21:40:02Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-29T21:40:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-29T21:40:02Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-29T21:40:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-29T21:40:02Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-29T21:40:02Z [Bootstrapper::Run] Connectivity check finished
2024-10-29T21:40:02Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-29T21:40:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-29T21:40:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-29T21:40:02Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-29T21:40:02Z [Bootstrapper::GetLatestVersionInfo] Got channel as zbeta
2024-10-29T21:40:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zbeta
2024-10-29T21:40:02Z [Deployment::GetInfo] Getting deploy info for channel zbeta
2024-10-29T21:40:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta
2024-10-29T21:40:02Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zbeta
2024-10-29T21:40:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta
2024-10-29T21:40:02Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-29T21:40:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-29T21:40:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-29T21:40:03Z [RegistryKeyEx::SetValueSafe] Writing 'zbeta' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-29T21:40:03Z [ApplicationSettings::Fetch.PCClientBootstrapper.zbeta] Fetching fast flags
2024-10-29T21:40:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zbeta
2024-10-29T21:40:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zbeta
2024-10-29T21:40:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-29T21:40:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-29T21:40:03Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-10-29T21:40:03Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-29T21:40:03Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-29T21:40:03Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-29T21:40:03Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-29T21:40:03Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-29T21:40:03Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-29T21:40:03Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-29T21:40:03Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-29T21:40:03Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-29T21:40:03Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-29T21:40:03Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-29T21:40:04Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-29T21:40:04Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-29T21:40:05Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-29T21:40:05Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-29T21:40:06Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-29T21:40:06Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-29T21:40:06Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-29T21:40:06Z [App::FinalizeExceptionHandling] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass33_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by pizzamuncher-cmyk** [comment]
ive got the same issue. great.

**Comment by newaccountonplace** [comment]
same issue as well!

**Comment by MendanSmiles** [comment]
Same issue!

**Comment by Mikethemonkey08** [comment]
Same here

**Comment by xisablehx** [comment]
same here :l

**Comment by Runer2343** [comment]
same

**Comment by hanstrav** [comment]
seems like its viral. hope they get a fix on it soon

**Comment by vibcerr** [comment]
same same

**Comment by vibcerr** [comment]
wait the messages show in the discord server. wsg hi guys

**Comment by Mikethemonkey08** [comment]
![fix](https://github.com/user-attachments/assets/e666c082-f839-4c39-8160-e3cc861997bb)

**Comment by Mikethemonkey08** [comment]
> wait the messages show in the discord server. wsg hi guys

can i get the discord of Bloxstrap pls and ty

**Comment by vibcerr** [comment]
https://discord.gg/nKjV3mGq6R

**Comment by Mikethemonkey08** [comment]
> https://discord.gg/nKjV3mGq6R

ty ty

**Comment by Mikethemonkey08** [comment]
> https://discord.gg/nKjV3mGq6R

roblox-player:1+launchmode:app+channel:production // paste this into ur brower it fixes bloxstrap

**Comment by WolfLapps** [comment]
> > https://discord.gg/nKjV3mGq6R
> 
> roblox-player:1+launchmode:app+channel:production // paste this into ur brower it fixes bloxstrap

After pasting, bloxstrap crashes with same error code anyway
