### ISSUE TITLE
[BUG] i can't install bloxstrap v2.8.1

### ISSUE THREAD

**Issue by Lexcoupeur** [bloxstraplabs/bloxstrap#3563]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

now its v2.8.0 but i want to install 2.8.1 but i can't

### What problem did you encounter?

i can't Install bloxstrap v2.8.1

### Bloxstrap Log

```text
N/A
```

**Comment by pizzaboxer** [comment]
Can you elaborate? Any error messages, strange behaviour?

**Comment by JaiBeeps** [comment]
Same here it wont let me install auto update didnt work and when I tried to install and said the file had a virus 
![Screenshot 2024-10-30 160909](https://github.com/user-attachments/assets/1387df3f-4b46-4104-b58c-0225052ef7de)

**Comment by pizzaboxer** [comment]
Auto update didn't work likely because of the antivirus detection. See if you can whitelist it in your antivirus.

**Comment by JaiBeeps** [comment]
2024-10-30T22:40:16Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-30T22:40:16Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 4:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-30T22:40:16Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-30T22:40:16Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-30T22:40:16Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-30T22:40:16Z [LaunchSettings] Identifier 'player' is active with data
2024-10-30T22:40:16Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241030T224016Z.log
2024-10-30T22:40:16Z [Logger::Initialize] Finished initializing!
2024-10-30T22:40:16Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-30T22:40:16Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-30T22:40:16Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-30T22:40:16Z [JsonManager<State>::Load] Loaded successfully!
2024-10-30T22:40:16Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-30T22:40:16Z [FastFlagManager::Load] Loaded successfully!
2024-10-30T22:40:16Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-30T22:40:16Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-30T22:40:16Z [Bootstrapper::Run] Running bootstrapper
2024-10-30T22:40:16Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-30T22:40:16Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-30T22:40:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-30T22:40:16Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-30T22:40:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-30T22:40:16Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-30T22:40:16Z [Bootstrapper::Run] Connectivity check finished
2024-10-30T22:40:16Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-30T22:40:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-30T22:40:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-30T22:40:16Z [Bootstrapper::SetStatus] Getting the latest Bloxstrap...
2024-10-30T22:40:16Z [Bootstrapper::CheckForUpdates] Downloading v2.8.1...
2024-10-30T22:40:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://github.com/bloxstraplabs/bloxstrap/releases/download/v2.8.1/Bloxstrap-v2.8.1.exe
2024-10-30T22:40:17Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://objects.githubusercontent.com/github-production-release-asset-2e65be/520583586/bfc2bb9d-a10d-4327-a723-532cc1d0f8eb?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20241030%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241030T223827Z&X-Amz-Expires=300&X-Amz-Signature=1b55d847cfcc74423775fcf17c69135a9829e9ec53432944663fd16b28b98cf0&X-Amz-SignedHeaders=host&response-content-disposition=attachment%3B filename%3DBloxstrap-v2.8.1.exe&response-content-type=application%2Foctet-stream
2024-10-30T22:40:31Z [Bootstrapper::CheckForUpdates] Starting v2.8.1...
2024-10-30T22:40:31Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-30T22:40:31Z [JsonManager<Settings>::Save] Save complete!
2024-10-30T22:40:31Z [Bootstrapper::CheckForUpdates] An exception occurred when running the auto-updater
2024-10-30T22:40:31Z [Bootstrapper::CheckForUpdates] System.ComponentModel.Win32Exception (225): An error occurred trying to start process '%UserProfile%\AppData\Local\Temp\Bloxstrap\Updates\Bloxstrap-v2.8.1.exe' with working directory 'C:\WINDOWS\system32'. Operation did not complete successfully because the file contains a virus or potentially unwanted software.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.CheckForUpdates()
2024-10-30T22:40:31Z [Frontend::ShowMessageBox] Bloxstrap was unable to automatically update to version v2.8.1. Please update it manually by downloading and running it from the website.
2024-10-30T22:40:34Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-30T22:40:34Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-30T22:40:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-30T22:40:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-30T22:40:34Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-30T22:40:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-30T22:40:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-30T22:40:34Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-10-30T22:40:35Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-30T22:40:35Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-30T22:40:36Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-30T22:40:36Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-30T22:40:36Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-30T22:40:36Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-30T22:40:36Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-30T22:40:36Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-30T22:40:36Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-30T22:40:36Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-30T22:40:36Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-30T22:40:36Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-30T22:40:36Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-30T22:40:36Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-30T22:40:36Z [App::FinalizeExceptionHandling] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass33_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()

**Comment by Thatonefnfguy** [comment]
uhh suggestion disable antivirus while downloading (idk i havent installed either so its not 100% guarenteed)

**Comment by bluepilledgreat** [comment]
No information provided by OP.
