### ISSUE TITLE
[BUG] System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. : 'C:\Users\jayde\AppData\Local\Bloxstrap\Downloads\f806bdcfd32ec64de061292e1d02f151'

### ISSUE THREAD

**Issue by jaydenganjiajie** [bloxstraplabs/bloxstrap#3564]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/8793257e-5036-4f33-8cec-8e281814992c)

### Bloxstrap Log

```text
2024-10-30T14:44:59Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-10-30T14:44:59Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 6:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-10-30T14:44:59Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-30T14:44:59Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-30T14:44:59Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-30T14:44:59Z [LaunchSettings] Identifier 'player' is active with data
2024-10-30T14:44:59Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241030T144459Z.log
2024-10-30T14:44:59Z [Logger::Initialize] Finished initializing!
2024-10-30T14:44:59Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-30T14:44:59Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-30T14:44:59Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-30T14:44:59Z [JsonManager<State>::Load] Loaded successfully!
2024-10-30T14:44:59Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-30T14:44:59Z [FastFlagManager::Load] Loaded successfully!
2024-10-30T14:44:59Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-30T14:44:59Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-30T14:44:59Z [Bootstrapper::Run] Running bootstrapper
2024-10-30T14:44:59Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-30T14:44:59Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-30T14:44:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-30T14:44:59Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-30T14:45:00Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-30T14:45:00Z [Bootstrapper::Run] Connectivity check finished
2024-10-30T14:45:00Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-30T14:45:00Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-30T14:45:00Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zbeta
2024-10-30T14:45:00Z [Deployment::GetInfo] Getting deploy info for channel zbeta
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta
2024-10-30T14:45:00Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-30T14:45:00Z [RegistryKeyEx::SetValueSafe] Writing 'zbeta' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-30T14:45:00Z [ApplicationSettings::Fetch.PCClientBootstrapper.zbeta] Fetching fast flags
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zbeta
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zbeta
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-30T14:45:00Z [Bootstrapper::SetStatus] Installing {product}...
2024-10-30T14:45:00Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zbeta
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-30T14:45:01Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-30T14:45:01Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-30T14:45:01Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-30T14:45:01Z [App::FinalizeExceptionHandling] (0x800700E1) System.IO.IOException: Operation did not complete successfully because the file contains a virus or potentially unwanted software. : '%UserProfile%\AppData\Local\Bloxstrap\Downloads\f806bdcfd32ec64de061292e1d02f151'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at Bloxstrap.Utility.MD5Hash.FromFile(String filename)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-10-30T14:45:01Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-30T14:45:01Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-30T14:45:02Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
2024-10-30T14:45:02Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-30T14:45:02Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-30T14:45:02Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-30T14:45:03Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-30T14:45:03Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip

```

**Comment by Error-Cezar** [comment]
Imagine not answering truthfully to all the above checkboxes.

**Comment by jaydenganjiajie** [comment]
> Imagine not answering truthfully to all the above checkboxes.
> 
> Ok buddy I saw that edit
sry abt that so how should i fix it?

**Comment by theletron** [comment]
> sry abt that so how should i fix it?

Maybe actually read the wiki next time?

https://github.com/bloxstraplabs/bloxstrap/wiki/Malware-detected-when-trying-to-upgrade-Roblox

**Comment by Error-Cezar** [comment]
Bro did NOT  answer truthfully to all the above checkboxes
