### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'RobloxPlayerBeta.exe' is denied.

### ISSUE THREAD

**Issue by Potata33** [bloxstraplabs/bloxstrap#3567]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [x] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.81

### What problem did you encounter?

Ever since I downloaded v2.81 I just started to get this problem.

### Bloxstrap Log

```text
2024-10-30T19:51:39Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-10-30T19:51:39Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 5:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-10-30T19:51:39Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-30T19:51:39Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-30T19:51:39Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-30T19:51:39Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241030T195139Z.log
2024-10-30T19:51:39Z [Logger::Initialize] Finished initializing!
2024-10-30T19:51:39Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-30T19:51:39Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-30T19:51:39Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-30T19:51:39Z [JsonManager<State>::Load] Loaded successfully!
2024-10-30T19:51:39Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-30T19:51:39Z [FastFlagManager::Load] Loaded successfully!
2024-10-30T19:51:41Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-30T19:51:41Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-30T19:51:41Z [Bootstrapper::Run] Running bootstrapper
2024-10-30T19:51:41Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-30T19:51:41Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-30T19:51:41Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-30T19:51:41Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-30T19:51:41Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-30T19:51:41Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-30T19:51:41Z [Bootstrapper::Run] Connectivity check finished
2024-10-30T19:51:41Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-30T19:51:41Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-30T19:51:42Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-30T19:51:42Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-30T19:51:42Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-30T19:51:42Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-30T19:51:42Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-30T19:51:42Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-30T19:51:42Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-30T19:51:42Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-4ffdeb3e393e469e-rbxPkgManifest.txt
2024-10-30T19:51:43Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-4ffdeb3e393e469e-rbxPkgManifest.txt
2024-10-30T19:51:43Z [Bootstrapper::SetStatus] Installing {product}...
2024-10-30T19:51:43Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-30T19:51:43Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-30T19:51:43Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'RobloxPlayerBeta.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-10-30T19:51:43Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
System.UnauthorizedAccessException: Access to the path 'RobloxPlayerBeta.exe' is denied.
```

**Comment by Potata33** [comment]
Is there a fix to this or no I just have to wait for a new one to release?

**Comment by pizzaboxer** [comment]
Oh I forgot to ask, can you confirm this happens even when Roblox isn't running in the background in Task Manager?

**Comment by Potata33** [comment]
Yes, this does happens even when Roblox isn't running in the background in Task Manager. Whenever I go to Bloxstrap and Roblox isn't running, I press "Launch Roblox" then that error pops up.

**Comment by Potata33** [comment]
Hey! Its fixed now and I don't know if it was yall that fixed it or what, but thank you so much if you did!!
