### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Windows\Temp\Bloxstrap\Logs' is denied.

### ISSUE THREAD

**Issue by T56135** [bloxstraplabs/bloxstrap#3569]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Bloxstrap not downloading

### Bloxstrap Log

```text
2024-10-30T21:41:31Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-10-30T21:41:31Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 3:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-10-30T21:41:31Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.1.exe
2024-10-30T21:41:31Z [App::OnStartup] Temp path is C:\Windows\Temp\Bloxstrap
2024-10-30T21:41:31Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-30T21:41:32Z [Logger::Initialize] Initializing at C:\Windows\Temp\Bloxstrap\Logs\Bloxstrap_20241030T214132Z.log
2024-10-30T21:41:32Z [App::GlobalExceptionHandler] An exception occurred
2024-10-30T21:41:32Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'C:\Windows\Temp\Bloxstrap\Logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-10-30T21:41:32Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by T56135** [comment]
Help

**Comment by pizzaboxer** [comment]
How are you opening/running Bloxstrap?

**Comment by T56135** [comment]
I download as usual through downloads

**Comment by T56135** [comment]
![image](https://github.com/user-attachments/assets/d29e8e83-4b7e-425a-b2d0-423bec53678d)

**Comment by pizzaboxer** [comment]
Would you know why the temp directory is being set to `C:\Windows\Temp\`?

**Comment by T56135** [comment]
![image](https://github.com/user-attachments/assets/6d5e9d78-b97b-4f80-baa4-da39937edce3)

**Comment by T56135** [comment]
> Would you know why the temp directory is being set to `C:\Windows\Temp\`?

Dont know

**Comment by pizzaboxer** [comment]
Open your system properties (open the Run dialog with Windows Key + R), type in `sysdm.cpl`, go to the 'Advanced' tab, click 'Environment Variables'.

In the window that opens, scroll to the bottom. Take a screenshot of what you see, send it here.

![image](https://github.com/user-attachments/assets/fa362fa2-5d9d-45a0-9940-a374c32898f0)

**Comment by T56135** [comment]
![image](https://github.com/user-attachments/assets/7ef63e03-c9ac-4652-bfba-1764791e66e4)

**Comment by pizzaboxer** [comment]
Can you change the values of both TEMP and TMP to be:
`C:\Users\Kkkq\AppData\Roaming\Temp`

Then try and launch?

**Comment by T56135** [comment]
![image](https://github.com/user-attachments/assets/4f7256b1-63ca-4150-ab6f-913e16137d6c)

**Comment by T56135** [comment]
A window appeared with the inscription register may be damaged

**Comment by pizzaboxer** [comment]
What happened to the entries in the bottom pane?

**Comment by T56135** [comment]
> Can you change the values of both TEMP and TMP to be: `C:\Users\Kkkq\AppData\Local\Temp`
> 
> Then try and launch?

I do not know, I changed how it is here and they disappeared

**Comment by T56135** [comment]
I'm not opening sysdm.cpl right now and the sound on my laptop is not working, maybe I have problems with the registry

**Comment by T56135** [comment]
I returned to the recovery point a day ago and rebooted the laptop, at first there was a black screen, then it started

**Comment by T56135** [comment]
![image](https://github.com/user-attachments/assets/f4d9afd5-2dcb-48fc-a34c-93453541cd51)

**Comment by T56135** [comment]
![image](https://github.com/user-attachments/assets/fd0d28c2-1bc9-4ddb-a70e-f69eedb5a6b8)

**Comment by pizzaboxer** [comment]
I'm not sure what you've done or what's happening but your system has quite literally crapped itself. It's doing this even after a system restore?

**Comment by T56135** [comment]
Yes, I went back to the restore point, but it looks the same
