### ISSUE TITLE
bug? "System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary."

### ISSUE THREAD

**Issue by PixeldValk** [bloxstraplabs/bloxstrap#3570]
2024-10-30T22:09:24Z [App::OnStartup] Starting Bloxstrap v4.2.0
2024-10-30T22:09:24Z [App::OnStartup] Compiled Thursday, 17 October 2024 at 1:46:36 AM from LUKECOMPUTER\minet
2024-10-30T22:09:24Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-30T22:09:24Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-30T22:09:24Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-30T22:09:24Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241030T220924Z.log
2024-10-30T22:09:24Z [Logger::Initialize] Finished initializing!
2024-10-30T22:09:24Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241023T212739Z.log'
2024-10-30T22:09:24Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241023T220842Z.log'
2024-10-30T22:09:24Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-30T22:09:24Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-30T22:09:24Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-30T22:09:24Z [JsonManager<State>::Load] Loaded successfully!
2024-10-30T22:09:24Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-30T22:09:24Z [FastFlagManager::Load] Loaded successfully!
2024-10-30T22:09:25Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-30T22:09:25Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-30T22:09:25Z [Bootstrapper::Run] Running bootstrapper
2024-10-30T22:09:25Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-30T22:09:25Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-30T22:09:25Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-30T22:09:25Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-30T22:09:26Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-30T22:09:26Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-30T22:09:26Z [Bootstrapper::Run] Connectivity check finished
2024-10-30T22:09:26Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-30T22:09:26Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-30T22:09:26Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-30T22:09:26Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-30T22:09:26Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-30T22:09:26Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-30T22:09:26Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-30T22:09:26Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-10-30T22:09:27Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-30T22:09:27Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-30T22:09:28Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-30T22:09:29Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-30T22:09:29Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-30T22:09:29Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-30T22:09:29Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-30T22:09:29Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-30T22:09:29Z [App::FinalizeExceptionHandling] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass33_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()

**Comment by pizzaboxer** [comment]
we only handle issue reports for original bloxstrap versions
