### ISSUE TITLE
[BUG] issueception: reporting an issue leads to a page saying my request url is too long

### ISSUE THREAD

**Issue by noobiii** [bloxstraplabs/bloxstrap#3572]
### Acknowledgement of preliminary instructions

- [ ] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [ ] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [ ] I am using the latest version of Bloxstrap.
- [x] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![image}](https://github.com/user-attachments/assets/58fa2b21-2b49-4705-bc14-c6142a1e9ec1)
NOTE: the original error [here](https://github.com/user-attachments/assets/efb15d42-6de4-4e69-bf5b-5822e94fbdbc) may be a cause, i looked in the url and the entire log file is in it lol

### Bloxstrap Log

```text
N/A
```

**Comment by PewcioS** [comment]
Yep same issue here

```
2024-10-30T22:36:55Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-30T22:36:55Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-30T22:36:55Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-30T22:36:56Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-30T22:36:56Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-30T22:36:56Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-30T22:36:57Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-30T22:36:58Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-30T22:37:00Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-30T22:37:00Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-30T22:37:00Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-30T22:37:00Z [App::FinalizeExceptionHandling] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass33_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by pizzaboxer** [comment]
You're not using 2.8.1. Go upgrade.

**Comment by noobiii** [comment]
on v2.8.1 it's still here
![{B91989F2-0ACA-4017-805B-32F31079BD46}](https://github.com/user-attachments/assets/9027deb9-fb93-47dc-9bef-1d43f5196b47)
the bloxstrap error itself looks to be entirely unrelated, the url is just way too long
