### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by dylansahacker** [bloxstraplabs/bloxstrap#3575]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [ ] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.0

### What problem did you encounter?

all i tried doing was attempting to run a roblox game, but than the error occured
![image](https://github.com/user-attachments/assets/f9c38b81-c203-4c7a-8558-db8b0998b561)

### Bloxstrap Log

```text
2024-10-30T23:01:14Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-10-30T23:01:14Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 2:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-10-30T23:01:14Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-30T23:01:14Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-30T23:01:14Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-30T23:01:14Z [LaunchSettings] Identifier 'player' is active with data
2024-10-30T23:01:14Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241030T230114Z.log
2024-10-30T23:01:14Z [Logger::Initialize] Finished initializing!
2024-10-30T23:01:14Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241023T003440Z.log'
2024-10-30T23:01:14Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241023T022841Z.log'
2024-10-30T23:01:14Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241023T022843Z.log'
2024-10-30T23:01:14Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241023T033959Z.log'
2024-10-30T23:01:14Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241023T034001Z.log'
2024-10-30T23:01:14Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241023T034558Z.log'
2024-10-30T23:01:14Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241023T034602Z.log'
2024-10-30T23:01:14Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241023T042630Z.log'
2024-10-30T23:01:14Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241023T042633Z.log'
2024-10-30T23:01:14Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-30T23:01:14Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-30T23:01:14Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-30T23:01:14Z [JsonManager<State>::Load] Loaded successfully!
2024-10-30T23:01:14Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-30T23:01:14Z [FastFlagManager::Load] Loaded successfully!
2024-10-30T23:01:14Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-30T23:01:14Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-30T23:01:14Z [Bootstrapper::Run] Running bootstrapper
2024-10-30T23:01:14Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-30T23:01:14Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-30T23:01:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-30T23:01:14Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-30T23:01:14Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-30T23:01:14Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-30T23:01:14Z [Bootstrapper::Run] Connectivity check finished
2024-10-30T23:01:14Z [Bootstrapper::GetLatestVersionInfo] Got channel as zliveforbeta
2024-10-30T23:01:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zliveforbeta
2024-10-30T23:01:14Z [Deployment::GetInfo] Getting deploy info for channel zliveforbeta
2024-10-30T23:01:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zliveforbeta
2024-10-30T23:01:15Z [HttpClientLoggingHandler::ProcessResponse] 401 Unauthorized https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zliveforbeta
2024-10-30T23:01:15Z [Deployment::GetInfo] Failed to contact clientsettingscdn! Falling back to clientsettings...
2024-10-30T23:01:15Z [Deployment::GetInfo] System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.RobloxInterfaces.Deployment.GetInfo(String channel)
2024-10-30T23:01:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettings.roblox.com/v2/client-version/WindowsPlayer/channel/zliveforbeta
2024-10-30T23:01:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zliveforbeta
2024-10-30T23:01:15Z [HttpClientLoggingHandler::ProcessResponse] 401 Unauthorized https://clientsettings.roblox.com/v2/client-version/WindowsPlayer/channel/zliveforbeta
2024-10-30T23:01:15Z [Bootstrapper::GetLatestVersionInfo] Changing channel from zliveforbeta to production because HTTP 401
2024-10-30T23:01:15Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-30T23:01:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-30T23:01:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-30T23:01:15Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-30T23:01:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-30T23:01:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-30T23:01:15Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-10-30T23:01:15Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-10-30T23:01:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-RobloxApp.zip
2024-10-30T23:01:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-RobloxApp.zip
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (87283571 bytes total)
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-10-30T23:01:17Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-content-configs.zip
2024-10-30T23:01:17Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-content-configs.zip
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (256195 bytes total)
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-10-30T23:01:17Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-shaders.zip
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-30T23:01:17Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-shaders.zip
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (9132866 bytes total)
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-10-30T23:01:17Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-30T23:01:17Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Downloading...
2024-10-30T23:01:17Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-content-platform-dictionaries.zip
2024-10-30T23:01:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-content-platform-dictionaries.zip
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Finished downloading! (152263 bytes total)
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-10-30T23:01:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-extracontent-places.zip
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-30T23:01:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-extracontent-places.zip
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1267431 bytes total)
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-10-30T23:01:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-extracontent-luapackages.zip
2024-10-30T23:01:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-extracontent-luapackages.zip
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (6601175 bytes total)
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-10-30T23:01:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-extracontent-translations.zip
2024-10-30T23:01:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-extracontent-translations.zip
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (484147 bytes total)
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-10-30T23:01:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-extracontent-models.zip
2024-10-30T23:01:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-extracontent-models.zip
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (10331949 bytes total)
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-10-30T23:01:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-WebView2.zip
2024-10-30T23:01:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-WebView2.zip
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-10-30T23:01:18Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-30T23:01:18Z [Bootstrapper::SetStatus] Configuring {product}...
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-30T23:01:18Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-30T23:01:20Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-10-30T23:01:20Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-30T23:01:20Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-30T23:01:20Z [App::FinalizeExceptionHandling] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass33_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-10-30T23:01:52Z [App::Terminate] Terminating with exit code 1603 (ERROR_INSTALL_FAILURE)
```

**Comment by cowboy-1337** [comment]
Update to [v2.8.1](https://github.com/bloxstraplabs/bloxstrap/releases/tag/v2.8.1)

**Comment by Orliminecraft** [comment]
You vill use shitty UI and you vill be happy

**Comment by JustSayy** [comment]
> Update to [v2.8.1](https://github.com/bloxstraplabs/bloxstrap/releases/tag/v2.8.1)

I updated the Bloxstrap but still have the same issue.

**Comment by MassiveHubs** [comment]
> Update to [v2.8.1](https://github.com/bloxstraplabs/bloxstrap/releases/tag/v2.8.1)

thanks for solving issue!
