### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'RobloxCrashHandler.exe' is denied.

### ISSUE THREAD

**Issue by CoolColyn24** [bloxstraplabs/bloxstrap#3594]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

Roblox launcher can open but bloxstrap cant

### Bloxstrap Log

```text
2024-10-31T14:28:46Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-10-31T14:28:47Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 5:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-10-31T14:28:47Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-31T14:28:47Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-31T14:28:47Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-31T14:28:47Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241031T142847Z.log
2024-10-31T14:28:47Z [Logger::Initialize] Finished initializing!
2024-10-31T14:28:47Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-31T14:28:47Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-31T14:28:47Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-31T14:28:47Z [JsonManager<State>::Load] Loaded successfully!
2024-10-31T14:28:47Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-31T14:28:47Z [FastFlagManager::Load] Loaded successfully!
2024-10-31T14:28:50Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-31T14:28:50Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-31T14:28:50Z [Bootstrapper::Run] Running bootstrapper
2024-10-31T14:28:50Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-10-31T14:28:50Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-31T14:28:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-31T14:28:50Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-31T14:28:52Z [Deployment::TestConnection<https://roblox-setup.cachefly.net>] Connecting...
2024-10-31T14:28:52Z [Deployment::TestConnection<https://setup-aws.rbxcdn.com>] Connecting...
2024-10-31T14:28:52Z [Deployment::TestConnection<https://setup-ak.rbxcdn.com>] Connecting...
2024-10-31T14:28:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-aws.rbxcdn.com/versionStudio
2024-10-31T14:28:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/versionStudio
2024-10-31T14:28:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://roblox-setup.cachefly.net/versionStudio
2024-10-31T14:28:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://roblox-setup.cachefly.net/versionStudio
2024-10-31T14:28:53Z [Deployment::InitializeConnectivity] Got https://roblox-setup.cachefly.net as the optimal base URL
2024-10-31T14:28:53Z [Bootstrapper::Run] Connectivity check finished
2024-10-31T14:28:53Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connectivity test cancelled.
2024-10-31T14:28:53Z [Deployment::TestConnection<https://setup-aws.rbxcdn.com>] Connectivity test cancelled.
2024-10-31T14:28:53Z [Deployment::TestConnection<https://setup-ak.rbxcdn.com>] Connectivity test cancelled.
2024-10-31T14:28:53Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-31T14:28:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-31T14:28:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-31T14:28:55Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-31T14:28:55Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-31T14:28:55Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-31T14:28:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-31T14:28:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-31T14:28:56Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-31T14:28:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://roblox-setup.cachefly.net/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-31T14:28:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://roblox-setup.cachefly.net/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-10-31T14:28:56Z [Bootstrapper::SetStatus] Installing {product}...
2024-10-31T14:28:56Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-31T14:28:56Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-31T14:28:56Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'RobloxCrashHandler.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-10-31T14:28:56Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
I'm assuming this has been fixed with v2.8.2. If not, please open a new issue.
