### ISSUE TITLE
[BUG] System.IO.IOException: Impossible de terminer l’opération, car le fichier contient un virus ou un logiciel potentiellement indésirable. : 'C:\Users\masym\AppData\Local\Bloxstrap\Downloads\bd66b334d77a078de7fe1266e6b38d4b'

### ISSUE THREAD

**Issue by Mathiasx37** [bloxstraplabs/bloxstrap#3603]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Impossible de terminer l’opération, car le fichier contient un virus ou un logiciel potentiellement indésirable. 

### Bloxstrap Log

```text
024-10-31T20:42:46Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-10-31T20:42:46Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 11:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-10-31T20:42:46Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-31T20:42:46Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-31T20:42:46Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-31T20:42:46Z [LaunchSettings] Identifier 'player' is active
2024-10-31T20:42:46Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241031T204246Z.log
2024-10-31T20:42:46Z [Logger::Initialize] Finished initializing!
2024-10-31T20:42:46Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-31T20:42:46Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-31T20:42:46Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-31T20:42:46Z [JsonManager<State>::Load] Loaded successfully!
2024-10-31T20:42:46Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-31T20:42:46Z [FastFlagManager::Load] Loaded successfully!
2024-10-31T20:42:46Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-10-31T20:42:46Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-10-31T20:42:46Z [Bootstrapper::Run] Running bootstrapper
2024-10-31T20:42:46Z [Bootstrapper::SetStatus] Connexion à Roblox...
2024-10-31T20:42:46Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-10-31T20:42:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-10-31T20:42:46Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-10-31T20:42:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-10-31T20:42:46Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-10-31T20:42:46Z [Bootstrapper::Run] Connectivity check finished
2024-10-31T20:42:46Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-10-31T20:42:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-10-31T20:42:47Z [Bootstrapper::CheckForUpdates] No updates found
2024-10-31T20:42:47Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zprojectuwpua
2024-10-31T20:42:47Z [Deployment::GetInfo] Getting deploy info for channel zprojectuwpua
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zprojectuwpua
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zprojectuwpua
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zprojectuwpua
2024-10-31T20:42:47Z [Deployment::GetInfo] Getting deploy info for channel production
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-10-31T20:42:47Z [RegistryKeyEx::SetValueSafe] Writing 'zprojectuwpua' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-10-31T20:42:47Z [ApplicationSettings::Fetch.PCClientBootstrapper.zprojectuwpua] Fetching fast flags
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zprojectuwpua
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zprojectuwpua
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-rbxPkgManifest.txt
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-rbxPkgManifest.txt
2024-10-31T20:42:47Z [Bootstrapper::SetStatus] Installation de {product}...
2024-10-31T20:42:47Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-RobloxApp.zip
2024-10-31T20:42:47Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-RobloxApp.zip
2024-10-31T20:42:49Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (87074486 bytes total)
2024-10-31T20:42:49Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-10-31T20:42:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-avatar.zip
2024-10-31T20:42:49Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-10-31T20:42:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-avatar.zip
2024-10-31T20:42:49Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (402097 bytes total)
2024-10-31T20:42:49Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-10-31T20:42:49Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-10-31T20:42:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-configs.zip
2024-10-31T20:42:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-configs.zip
2024-10-31T20:42:49Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (256195 bytes total)
2024-10-31T20:42:49Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-10-31T20:42:49Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-10-31T20:42:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-fonts.zip
2024-10-31T20:42:49Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-10-31T20:42:49Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-10-31T20:42:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-fonts.zip
2024-10-31T20:42:50Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-10-31T20:42:50Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-10-31T20:42:50Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-10-31T20:42:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-models.zip
2024-10-31T20:42:50Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-10-31T20:42:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-models.zip
2024-10-31T20:42:51Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (488968 bytes total)
2024-10-31T20:42:51Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-10-31T20:42:51Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-10-31T20:42:51Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-sky.zip
2024-10-31T20:42:51Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-10-31T20:42:51Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-sky.zip
2024-10-31T20:42:52Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-10-31T20:42:52Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-10-31T20:42:52Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-10-31T20:42:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-sounds.zip
2024-10-31T20:42:52Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-10-31T20:42:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-sounds.zip
2024-10-31T20:42:52Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (373629 bytes total)
2024-10-31T20:42:52Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-10-31T20:42:52Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-10-31T20:42:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-shaders.zip
2024-10-31T20:42:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-shaders.zip
2024-10-31T20:42:52Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-10-31T20:42:53Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (9132866 bytes total)
2024-10-31T20:42:53Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-10-31T20:42:53Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-10-31T20:42:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-ssl.zip
2024-10-31T20:42:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-ssl.zip
2024-10-31T20:42:53Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (135951 bytes total)
2024-10-31T20:42:53Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-10-31T20:42:53Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-10-31T20:42:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-textures2.zip
2024-10-31T20:42:53Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-10-31T20:42:53Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-10-31T20:42:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-textures2.zip
2024-10-31T20:42:54Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (12448624 bytes total)
2024-10-31T20:42:54Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-10-31T20:42:54Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-10-31T20:42:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-textures3.zip
2024-10-31T20:42:55Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-textures3.zip
2024-10-31T20:42:55Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-10-31T20:42:55Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-10-31T20:42:55Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-10-31T20:42:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-terrain.zip
2024-10-31T20:42:56Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-10-31T20:42:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-terrain.zip
2024-10-31T20:42:56Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-10-31T20:42:56Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-10-31T20:42:56Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-10-31T20:42:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-platform-fonts.zip
2024-10-31T20:42:56Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-10-31T20:42:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-platform-fonts.zip
2024-10-31T20:42:57Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-10-31T20:42:57Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-10-31T20:42:57Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-10-31T20:42:57Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Downloading...
2024-10-31T20:42:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-platform-dictionaries.zip
2024-10-31T20:42:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-content-platform-dictionaries.zip
2024-10-31T20:42:57Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Finished downloading! (152263 bytes total)
2024-10-31T20:42:57Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-10-31T20:42:57Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-10-31T20:42:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-extracontent-places.zip
2024-10-31T20:42:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-extracontent-places.zip
2024-10-31T20:42:57Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-10-31T20:42:57Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1267431 bytes total)
2024-10-31T20:42:57Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-10-31T20:42:57Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-10-31T20:42:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-extracontent-luapackages.zip
2024-10-31T20:42:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-extracontent-luapackages.zip
2024-10-31T20:42:57Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-10-31T20:42:57Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (6601175 bytes total)
2024-10-31T20:42:57Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-10-31T20:42:57Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-10-31T20:42:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-extracontent-translations.zip
2024-10-31T20:42:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-extracontent-translations.zip
2024-10-31T20:42:57Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (484147 bytes total)
2024-10-31T20:42:57Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-10-31T20:42:57Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-10-31T20:42:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-extracontent-models.zip
2024-10-31T20:42:57Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-extracontent-models.zip
2024-10-31T20:42:57Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-10-31T20:42:57Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-10-31T20:42:57Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-10-31T20:42:58Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (10272509 bytes total)
2024-10-31T20:42:58Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-10-31T20:42:58Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-10-31T20:42:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-extracontent-textures.zip
2024-10-31T20:42:58Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-extracontent-textures.zip
2024-10-31T20:42:58Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-10-31T20:42:58Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (16874222 bytes total)
2024-10-31T20:42:58Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-10-31T20:42:58Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-10-31T20:42:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-WebView2.zip
2024-10-31T20:42:58Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-WebView2.zip
2024-10-31T20:42:58Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-10-31T20:42:58Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-10-31T20:42:58Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-10-31T20:42:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-WebView2RuntimeInstaller.zip
2024-10-31T20:42:58Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-10-31T20:42:58Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-WebView2RuntimeInstaller.zip
2024-10-31T20:42:59Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-10-31T20:43:00Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-10-31T20:43:00Z [Bootstrapper::DownloadPackage.redist.zip] Downloading...
2024-10-31T20:43:00Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-redist.zip
2024-10-31T20:43:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-9d6e57c0e9b74e5f-redist.zip
2024-10-31T20:43:00Z [Bootstrapper::DownloadPackage.redist.zip] Finished downloading! (1372275 bytes total)
2024-10-31T20:43:00Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-10-31T20:43:00Z [Bootstrapper::SetStatus] Configuration de {product}...
2024-10-31T20:43:00Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-10-31T20:43:00Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-10-31T20:43:00Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-10-31T20:43:00Z [App::FinalizeExceptionHandling] (0x800700E1) System.IO.IOException: Impossible de terminer l’opération, car le fichier contient un virus ou un logiciel potentiellement indésirable. : '%UserProfile%\AppData\Local\Bloxstrap\Downloads\bd66b334d77a078de7fe1266e6b38d4b'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass34_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-10-31T20:43:00Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-10-31T20:43:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://bloxstraplabs.com/metrics/post-exception
```

**Comment by pizzaboxer** [comment]
https://github.com/bloxstraplabs/bloxstrap/wiki/Malware-detected-when-trying-to-upgrade-Roblox
