### ISSUE TITLE
[BUG] System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by benj1021** [bloxstraplabs/bloxstrap#3605]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1 / v2.8.0 - afnfork

### What problem did you encounter?

When trying to install the latest forks, it comes up with this exception. 
![image](https://github.com/user-attachments/assets/c1cfb365-37ef-41af-a17d-d7d50a244374)
I do not know what this issue is exactly though. I have to use regular bloxstrap as a workaround for this., but it prevents me from being able to do most of Project Afternight's mechanics / features.

### Bloxstrap Log

```text
2024-10-31T21:49:01Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-10-31T21:49:01Z [App::OnStartup] Compiled Thursday, 31 October 2024 at 5:39:40 PM from commit aa6795aa1764874f45df92139a803aa9861b17c6 (branch/main)
2024-10-31T21:49:01Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.1-afnfork.exe
2024-10-31T21:49:01Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-31T21:49:01Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-31T21:49:01Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap\Logs\Bloxstrap_20241031T214901Z.log
2024-10-31T21:49:01Z [Logger::Initialize] Finished initializing!
2024-10-31T21:49:02Z [MainWindow] Initializing installer window
2024-10-31T21:49:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/Adrigamer278/bloxstrap/releases/latest
2024-10-31T21:49:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/Adrigamer278/bloxstrap/releases/latest
2024-10-31T21:49:02Z [Utilities::CompareVersions] An exception occurred when comparing versions
2024-10-31T21:49:02Z [Utilities::CompareVersions] versionStr1=2.8.1 versionStr2=v2.8.1-afnfork
2024-10-31T21:49:02Z [App::GlobalExceptionHandler] An exception occurred
2024-10-31T21:49:02Z [App::FinalizeExceptionHandling] (0x80131537) System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Version.TryParseComponent(ReadOnlySpan`1 component, String componentName, Boolean throwOnFailure, Int32& parsedComponent)
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Bloxstrap.Utilities.CompareVersions(String versionStr1, String versionStr2)
   at Bloxstrap.UI.ViewModels.Installer.WelcomeViewModel.DoChecks()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by benj1021** [comment]
Update, I opened the issue on the offical comms server for Project: Afternight, so it's being looked into.

**Comment by benj1021** [comment]
Ok. Been told to close it as it was an issue from the fork itself by a developer.
