### ISSUE TITLE
[BUG] Discord Rich Presence Not Working

### ISSUE THREAD

**Issue by PolarZer0** [bloxstraplabs/bloxstrap#3606]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

When I join the game, I get a popup saying Discord Rich Presence won't work. The normal Roblox Rich Presence shows up on my Discord. I'm not using any RPC extensions, and I only have one Discord client open.

### Bloxstrap Log

```text
2024-10-31T22:36:08Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-10-31T22:36:08Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 6:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-10-31T22:36:08Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-10-31T22:36:08Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-10-31T22:36:08Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-10-31T22:36:08Z [LaunchSettings] Identifier 'watcher' is active with data
2024-10-31T22:36:08Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241031T223608Z.log
2024-10-31T22:36:08Z [Logger::Initialize] Finished initializing!
2024-10-31T22:36:08Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-10-31T22:36:08Z [JsonManager<Settings>::Load] Loaded successfully!
2024-10-31T22:36:08Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-10-31T22:36:08Z [JsonManager<State>::Load] Loaded successfully!
2024-10-31T22:36:08Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-10-31T22:36:08Z [FastFlagManager::Load] Loaded successfully!
2024-10-31T22:36:08Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-10-31T22:36:08Z [DiscordRichPresence] Established connection with Discord RPC
2024-10-31T22:36:08Z [ActivityWatcher::Start] Opened %UserProfile%\AppData\Local\Roblox\logs\0.649.0.6490878_20241031T223607Z_Player_0851F_last.log
2024-10-31T22:36:08Z [ActivityWatcher::ReadLogEntry] Read 50 log entries
2024-10-31T22:36:09Z [DiscordRichPresence] Received ready from user Polar (338450855399391232)
2024-10-31T22:36:09Z [ActivityWatcher::ReadLogEntry] Read 100 log entries
2024-10-31T22:36:16Z [ActivityWatcher::ReadLogEntry] Joining Game (13772394625/06559b33-6a2e-46af-90ae-9b009a33fa3e)
2024-10-31T22:36:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://ipinfo.io/128.116.53.33/json
2024-10-31T22:36:16Z [ActivityWatcher::ReadLogEntry] Server is UDMUX protected (13772394625/06559b33-6a2e-46af-90ae-9b009a33fa3e)
2024-10-31T22:36:16Z [ActivityWatcher::ReadLogEntry] Joined Game (13772394625/06559b33-6a2e-46af-90ae-9b009a33fa3e)
2024-10-31T22:36:16Z [DiscordRichPresence::SetCurrentGame] Setting presence for Place ID 13772394625
2024-10-31T22:36:16Z [HttpClientLoggingHandler::ProcessRequest] GET https://games.roblox.com/v1/games?universeIds=0
2024-10-31T22:36:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://games.roblox.com/v1/games?universeIds=0
2024-10-31T22:36:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://ipinfo.io/128.116.53.33/json
2024-10-31T22:36:16Z [NotifyIconWrapper::ShowAlert.d0150517] Showing alert for 10 seconds (clickHandler=True)
2024-10-31T22:36:16Z [NotifyIconWrapper::ShowAlert.d0150517] Connected to public server: Location: Ashburn, Virginia, US
\nClick for more information
2024-10-31T22:36:16Z [DiscordRichPresence::SetCurrentGame] (0x80131500) Bloxstrap.Exceptions.InvalidHTTPResponseException: Roblox API for Game Details returned invalid data
   at Bloxstrap.Models.Entities.UniverseDetails.FetchBulk(String ids)
   at Bloxstrap.Integrations.DiscordRichPresence.SetCurrentGame()
2024-10-31T22:36:16Z [Frontend::ShowMessageBox] Your current game will not show on your Discord presence because an error occurred when loading the game information.

Roblox API for Game Details returned invalid data
2024-10-31T22:36:20Z [ActivityWatcher::ReadLogEntry] Read 150 log entries
2024-10-31T22:36:20Z [ActivityWatcher::ReadLogEntry] Read 200 log entries
2024-10-31T22:36:20Z [ActivityWatcher::ReadLogEntry] Read 250 log entries
2024-10-31T22:36:20Z [ActivityWatcher::ReadLogEntry] Read 300 log entries
2024-10-31T22:36:20Z [ActivityWatcher::ReadLogEntry] Read 350 log entries
2024-10-31T22:36:21Z [ActivityWatcher::ReadLogEntry] Read 400 log entries
2024-10-31T22:36:26Z [NotifyIconWrapper::ShowAlert.d0150517] Duration over, erasing current click handler
2024-10-31T22:36:41Z [ActivityWatcher::ReadLogEntry] Read 450 log entries
2024-10-31T22:36:54Z [ActivityWatcher::ReadLogEntry] User is back into the desktop app
2024-10-31T22:36:54Z [ActivityWatcher::ReadLogEntry] Read 500 log entries
2024-10-31T22:36:54Z [ActivityWatcher::ReadLogEntry] Disconnected from Game (13772394625/06559b33-6a2e-46af-90ae-9b009a33fa3e)
2024-10-31T22:36:54Z [DiscordRichPresence::SetCurrentGame] Not in game, clearing presence
2024-10-31T22:36:54Z [DiscordRichPresence::UpdatePresence] Presence is empty, clearing
2024-10-31T22:36:56Z [ActivityWatcher::ReadLogEntry] Read 550 log entries
2024-10-31T22:36:57Z [LaunchHandler::LaunchWatcher] Watcher task has finished
2024-10-31T22:36:57Z [Watcher::Dispose] Disposing Watcher
2024-10-31T22:36:57Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
2024-10-31T22:36:57Z [MenuContainer::Window_Closed] Context menu container closed
2024-10-31T22:36:57Z [DiscordRichPresence::Dispose] Cleaning up Discord RPC and Presence
2024-10-31T22:36:57Z [App::Terminate] Terminating with exit code 0 (ERROR_SUCCESS)
```

**Comment by Wanwood1** [comment]
2.8.2 doesnt exist

**Comment by PolarZer0** [comment]
> 2.8.2 doesnt exist

sorry, i made a typo i'm on 2.8.1 i believe it also says that in the logs
