### ISSUE TITLE
[BUG] System.IO.IOException: El archivo o directorio está dañado o es ilegible. : '\\?\C:\Users\ChronicTheCat\AppData\Local\Bloxstrap\Roblox\Player.old\content\textures\ui\Controls\PlayStationController'

### ISSUE THREAD

**Issue by SumiOnGithub** [bloxstraplabs/bloxstrap#3618]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

launcher couldn't boot up roblox, i don't know how but it has to be about the Playstation buttonsd not loading or the textures for the buttons not being found

### Bloxstrap Log

```text
2024-11-01T17:53:57Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-01T17:53:57Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 5:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-01T17:53:57Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Temp\Bloxstrap\Updates\Bloxstrap-v2.8.1.exe
2024-11-01T17:53:57Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-01T17:53:57Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-01T17:53:57Z [LaunchSettings] Identifier 'upgrade' is active
2024-11-01T17:53:57Z [LaunchSettings] Identifier 'player' is active
2024-11-01T17:53:57Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241101T175357Z.log
2024-11-01T17:53:57Z [Logger::Initialize] Finished initializing!
2024-11-01T17:53:57Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-01T17:53:57Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-01T17:53:57Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-01T17:53:57Z [JsonManager<State>::Load] Loaded successfully!
2024-11-01T17:53:57Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-01T17:53:57Z [FastFlagManager::Load] Loaded successfully!
2024-11-01T17:53:57Z [Installer::HandleUpgrade] Doing upgrade
2024-11-01T17:53:57Z [RegistryKeyEx::SetValueSafe] Writing '2.8.1' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\DisplayVersion
2024-11-01T17:53:57Z [RegistryKeyEx::SetValueSafe] Writing 'Bloxstrap' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\Publisher
2024-11-01T17:53:57Z [RegistryKeyEx::SetValueSafe] Writing 'https://github.com/bloxstraplabs/bloxstrap/wiki' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\HelpLink
2024-11-01T17:53:57Z [RegistryKeyEx::SetValueSafe] Writing 'https://github.com/bloxstraplabs/bloxstrap/issues/new' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\URLInfoAbout
2024-11-01T17:53:57Z [RegistryKeyEx::SetValueSafe] Writing 'https://bloxstraplabs.com' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\URLUpdateInfo
2024-11-01T17:53:57Z [FastFlagManager::SetValue] Deletion of 'FIntNewInGameMenuPercentRollout3' is pending
2024-11-01T17:53:57Z [FastFlagManager::SetValue] Deletion of 'FFlagEnableInGameMenuControls' is pending
2024-11-01T17:53:57Z [FastFlagManager::SetValue] Deletion of 'FFlagEnableInGameMenuModernization' is pending
2024-11-01T17:53:57Z [FastFlagManager::SetValue] Deletion of 'FFlagEnableInGameMenuChrome' is pending
2024-11-01T17:53:57Z [FastFlagManager::SetValue] Deletion of 'FFlagEnableMenuControlsABTest' is pending
2024-11-01T17:53:57Z [FastFlagManager::SetValue] Deletion of 'FFlagEnableV3MenuABTest3' is pending
2024-11-01T17:53:57Z [FastFlagManager::SetValue] Deletion of 'FFlagEnableInGameMenuChromeABTest3' is pending
2024-11-01T17:53:57Z [FastFlagManager::SetValue] Deletion of 'FFlagEnableInGameMenuChromeABTest4' is pending
2024-11-01T17:53:57Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-01T17:53:57Z [JsonManager<Settings>::Save] Save complete!
2024-11-01T17:53:57Z [FastFlagManager::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-01T17:53:57Z [FastFlagManager::Save] Save complete!
2024-11-01T17:53:57Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=installAction&value=upgrade
2024-11-01T17:53:58Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-01T17:53:58Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-01T17:53:58Z [Bootstrapper::Run] Running bootstrapper
2024-11-01T17:53:58Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-01T17:53:58Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-01T17:53:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-01T17:53:58Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-01T17:53:58Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-01T17:53:58Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-01T17:53:58Z [Bootstrapper::Run] Connectivity check finished
2024-11-01T17:53:58Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-11-01T17:53:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zflag
2024-11-01T17:53:58Z [Deployment::GetInfo] Getting deploy info for channel zflag
2024-11-01T17:53:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zflag
2024-11-01T17:53:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zflag
2024-11-01T17:53:59Z [Deployment::GetInfo] Getting deploy info for channel production
2024-11-01T17:53:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-01T17:53:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-01T17:53:59Z [RegistryKeyEx::SetValueSafe] Writing 'zflag' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-11-01T17:53:59Z [ApplicationSettings::Fetch.PCClientBootstrapper.zflag] Fetching fast flags
2024-11-01T17:53:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zflag
2024-11-01T17:53:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zflag
2024-11-01T17:53:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-01T17:53:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-01T17:53:59Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-11-01T17:54:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://bloxstraplabs.com/metrics/post?key=installAction&value=upgrade
2024-11-01T17:54:00Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zflag
2024-11-01T17:54:02Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-11-01T17:54:02Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-11-01T17:54:02Z [App::FinalizeExceptionHandling] (0x80070570) System.IO.IOException: El archivo o directorio está dañado o es ilegible. : '\\?\%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player.old\content\textures\ui\Controls\PlayStationController'
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-11-01T17:54:02Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-11-01T17:54:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
I'm assuming this has been fixed with v2.8.2. If not, please open a new issue.
