### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Users\games\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory 'C:\Users\games\AppData\Local\Bloxstrap\Roblox\Player'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by jasminchi** [bloxstraplabs/bloxstrap#3622]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

The log shows up every time i try to launch it after downloading it

### Bloxstrap Log

```text
2024-11-01T22:32:26Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-01T22:32:26Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 6:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-01T22:32:26Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-11-01T22:32:26Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-01T22:32:26Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-01T22:32:26Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241101T223226Z.log
2024-11-01T22:32:26Z [Logger::Initialize] Finished initializing!
2024-11-01T22:32:26Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-01T22:32:26Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-01T22:32:26Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-01T22:32:26Z [JsonManager<State>::Load] Loaded successfully!
2024-11-01T22:32:26Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-01T22:32:26Z [FastFlagManager::Load] Loaded successfully!
2024-11-01T22:32:26Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-11-01T22:32:26Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-11-01T22:32:28Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-01T22:32:28Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-01T22:32:28Z [Bootstrapper::Run] Running bootstrapper
2024-11-01T22:32:28Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-01T22:32:28Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-01T22:32:28Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-01T22:32:28Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-01T22:32:28Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-01T22:32:28Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-01T22:32:28Z [Bootstrapper::Run] Connectivity check finished
2024-11-01T22:32:28Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-11-01T22:32:28Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-01T22:32:28Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-01T22:32:28Z [Bootstrapper::CheckForUpdates] No updates found
2024-11-01T22:32:28Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-11-01T22:32:28Z [Deployment::GetInfo] Getting deploy info for channel production
2024-11-01T22:32:28Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-01T22:32:28Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-01T22:32:28Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-11-01T22:32:28Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-01T22:32:28Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-01T22:32:28Z [Bootstrapper::SetStatus] Installing {product}...
2024-11-01T22:32:28Z [Bootstrapper::UpgradeRoblox] Could not clear old files, aborting update.
2024-11-01T22:32:28Z [Bootstrapper::UpgradeRoblox] (0x80070020) System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
2024-11-01T22:32:28Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-11-01T22:32:28Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-11-01T22:32:28Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-11-01T22:32:28Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-01T22:32:28Z [JsonManager<State>::Save] Save complete!
2024-11-01T22:32:28Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-11-01T22:32:28Z [Bootstrapper::SetStatus] Starting {product}...
2024-11-01T22:32:28Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-11-01T22:32:28Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-11-01T22:32:28Z [App::FinalizeExceptionHandling] (0x80004005) System.ComponentModel.Win32Exception (2): An error occurred trying to start process '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player\RobloxPlayerBeta.exe' with working directory '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-11-01T22:32:28Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
I'm assuming this has been fixed with v2.8.2. If not, please open a new issue.
