### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\PC\Desktop\Bloxstraps\Bloxstrap\Roblox\Player\content\sounds\ouch.ogg' is denied.

### ISSUE THREAD

**Issue by younes1623** [bloxstraplabs/bloxstrap#3646]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

they wont let me play

### Bloxstrap Log

```text
2024-11-03T11:54:48Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-03T11:54:48Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 1:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-03T11:54:48Z [App::OnStartup] Loaded from %UserProfile%\Desktop\Bloxstraps\Bloxstrap\Bloxstrap.exe
2024-11-03T11:54:48Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-03T11:54:48Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-03T11:54:48Z [LaunchSettings] Identifier 'player' is active with data
2024-11-03T11:54:48Z [Logger::Initialize] Initializing at %UserProfile%\Desktop\Bloxstraps\Bloxstrap\Logs\Bloxstrap_20241103T115448Z.log
2024-11-03T11:54:48Z [Logger::Initialize] Finished initializing!
2024-11-03T11:54:48Z [JsonManager<Settings>::Load] Loading from %UserProfile%\Desktop\Bloxstraps\Bloxstrap\Settings.json...
2024-11-03T11:54:48Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-03T11:54:48Z [JsonManager<State>::Load] Loading from %UserProfile%\Desktop\Bloxstraps\Bloxstrap\State.json...
2024-11-03T11:54:48Z [JsonManager<State>::Load] Loaded successfully!
2024-11-03T11:54:48Z [FastFlagManager::Load] Loading from %UserProfile%\Desktop\Bloxstraps\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-03T11:54:48Z [FastFlagManager::Load] Loaded successfully!
2024-11-03T11:54:48Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-03T11:54:48Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-03T11:54:49Z [Bootstrapper::Run] Running bootstrapper
2024-11-03T11:54:49Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-03T11:54:49Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-03T11:54:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-03T11:54:49Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-03T11:54:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-03T11:54:49Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-03T11:54:49Z [Bootstrapper::Run] Connectivity check finished
2024-11-03T11:54:49Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-11-03T11:54:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-03T11:54:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-03T11:54:49Z [Bootstrapper::CheckForUpdates] No updates found
2024-11-03T11:54:49Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-11-03T11:54:49Z [Deployment::GetInfo] Getting deploy info for channel production
2024-11-03T11:54:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-03T11:54:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-03T11:54:50Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-11-03T11:54:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-03T11:54:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-03T11:54:50Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-11-03T11:54:50Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-11-03T11:54:50Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-11-03T11:54:51Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-11-03T11:54:51Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-11-03T11:54:51Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path '%UserProfile%\Desktop\Bloxstraps\Bloxstrap\Roblox\Player\content\sounds\ouch.ogg' is denied.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Bloxstrap.Bootstrapper.ApplyModifications()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-11-03T11:54:51Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
I'm assuming this has been fixed with v2.8.2. If not, please open a new issue.
