### ISSUE TITLE
[BUG] Wonky Behavior With VPN

### ISSUE THREAD

**Issue by AssemblyLangFTW** [bloxstraplabs/bloxstrap#3654]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

When using a VPN (Specifically Mullvad VPN on us-chi-wg-002 with the issue across several servers), some things break. Initially Roblox refused to launch at all, leading me to think it was Byfron blocking it. But, now it seems to launch properly (albeit with the basic lag expected with a VPN) with the newer Bloxstrap versions. However, Bloxstrap updated just today, and, now every time I launch Roblox whilst connected to any VPN server, Discord Rich Presence and server info do not work properly. I have attached a screenshot and log of this.

EDIT: Now it appears to say "Bloxstrap is unable to connect to Roblox" but connects and then shows the two error popups in the screenshot below.

![image](https://github.com/user-attachments/assets/4d37ba45-e429-48b7-9635-ab3cf55076c9)

### Bloxstrap Log

```text
2024-11-03T22:54:10Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-03T22:54:10Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 6:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-03T22:54:10Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-11-03T22:54:10Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-03T22:54:10Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-03T22:54:10Z [LaunchSettings] Identifier 'watcher' is active with data
2024-11-03T22:54:10Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241103T225410Z.log
2024-11-03T22:54:10Z [Logger::Initialize] Finished initializing!
2024-11-03T22:54:10Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-03T22:54:10Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-03T22:54:10Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-03T22:54:10Z [JsonManager<State>::Load] Loaded successfully!
2024-11-03T22:54:10Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-03T22:54:10Z [FastFlagManager::Load] Loaded successfully!
2024-11-03T22:54:10Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-11-03T22:54:11Z [ActivityWatcher::Start] Opened %UserProfile%\AppData\Local\Roblox\logs\0.649.0.6490878_20241103T225410Z_Player_11DA6_last.log
2024-11-03T22:54:11Z [ActivityWatcher::ReadLogEntry] Read 50 log entries
2024-11-03T22:54:13Z [ActivityWatcher::ReadLogEntry] Joining Game (18256976639/7a243426-60f0-4cb3-91ac-fdde1db4629b)
2024-11-03T22:54:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://ipinfo.io/128.116.95.33/json
2024-11-03T22:54:13Z [ActivityWatcher::ReadLogEntry] Server is UDMUX protected (18256976639/7a243426-60f0-4cb3-91ac-fdde1db4629b)
2024-11-03T22:54:13Z [ActivityWatcher::ReadLogEntry] Read 100 log entries
2024-11-03T22:54:13Z [ActivityWatcher::ReadLogEntry] Joined Game (18256976639/7a243426-60f0-4cb3-91ac-fdde1db4629b)
2024-11-03T22:54:13Z [DiscordRichPresence::SetCurrentGame] Setting presence for Place ID 18256976639
2024-11-03T22:54:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://games.roblox.com/v1/games?universeIds=6188934843
2024-11-03T22:54:13Z [DiscordRichPresence::SetCurrentGame] (0x80004005) System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (games.roblox.com:443)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.Models.Entities.UniverseDetails.FetchBulk(String ids)
   at Bloxstrap.Integrations.DiscordRichPresence.SetCurrentGame()
2024-11-03T22:54:13Z [Frontend::ShowMessageBox] Your current game will not show on your Discord presence because an error occurred when loading the game information.

An attempt was made to access a socket in a way forbidden by its access permissions. (games.roblox.com:443)
2024-11-03T22:54:13Z [ActivityData::QueryServerLocation] Failed to get server location for 128.116.95.33
2024-11-03T22:54:13Z [ActivityData::QueryServerLocation] (0x80004005) System.Net.Http.HttpRequestException: An attempt was made to access a socket in a way forbidden by its access permissions. (ipinfo.io:443)
 ---> System.Net.Sockets.SocketException (10013): An attempt was made to access a socket in a way forbidden by its access permissions.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.Models.Entities.ActivityData.QueryServerLocation()
2024-11-03T22:54:15Z [ActivityWatcher::ReadLogEntry] Read 150 log entries
2024-11-03T22:54:15Z [ActivityWatcher::ReadLogEntry] Read 200 log entries
2024-11-03T22:54:15Z [ActivityWatcher::ReadLogEntry] Read 250 log entries
2024-11-03T22:54:15Z [ActivityWatcher::ReadLogEntry] Read 300 log entries
2024-11-03T22:58:50Z [ActivityWatcher::ReadLogEntry] Read 350 log entries
```

**Comment by bluepilledgreat** [comment]
what did you expect?
