### ISSUE TITLE
[BUG] Showing (unexpected occured while running Bloxstrap)

### ISSUE THREAD

**Issue by Northenation** [bloxstraplabs/bloxstrap#3670]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### Bloxstrap Log

```text
024-11-05T14:16:43Z [App::OnStartup] Starting Bloxstrap v2.5.3
2024-11-05T14:16:43Z [App::OnStartup] Compiled Tuesday, 18 June 2024 at 11:09:08 PM from DESKTOP-FGF6DO8\User
2024-11-05T14:16:43Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-11-05T14:16:43Z [InstallChecker::FirstTimeRun] Running first-time install
2024-11-05T14:16:43Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20241105T141643Z.log
2024-11-05T14:16:43Z [Logger::Initialize] Finished initializing!
2024-11-05T14:16:43Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-11-05T14:16:43Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-11-05T14:16:43Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\Desktop\ClientSettings\ClientAppSettings.json'.
2024-11-05T14:16:43Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-11-05T14:16:43Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-11-05T14:16:43Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '144' is pending
2024-11-05T14:16:43Z [MainWindow::MainWindow] Initializing menu
2024-11-05T14:16:50Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-11-05T14:16:50Z [App::OnStartup] Initializing bootstrapper
2024-11-05T14:16:50Z [App::OnStartup] Initializing bootstrapper dialog
2024-11-05T14:16:50Z [App::OnStartup] Creating singleton mutex
2024-11-05T14:16:50Z [Bootstrapper::Run] Running bootstrapper
2024-11-05T14:16:50Z [Bootstrapper::Run] Performing connectivity check...
2024-11-05T14:16:50Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-05T14:16:50Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-11-05T14:16:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-11-05T14:17:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-11-05T14:17:11Z [Bootstrapper::Run] Connectivity check finished
2024-11-05T14:17:11Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-11-05T14:17:11Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-11-05T14:17:11Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-11-05T14:17:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-11-05T14:17:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-11-05T14:17:13Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-11-05T14:17:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-05T14:17:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-05T14:17:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxManifest.txt
2024-11-05T14:17:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxManifest.txt
2024-11-05T14:17:14Z [Bootstrapper::SetStatus] Installing Roblox...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\avatar\...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\configs\...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\fonts\...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\models\...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\sky\...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\sounds\...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\shaders\...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ssl\...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\textures\...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\PlatformContent\pc\textures\...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\PlatformContent\pc\terrain\...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\PlatformContent\pc\fonts\...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting content-platform-dictionaries.zip'
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ExtraContent\places\...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-11-05T14:17:14Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ExtraContent\LuaPackages\...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ExtraContent\translations\...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ExtraContent\models\...
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is corrupted (85335c6f0633d43eb4a4b611c760ca2b != 13150b8d1755d575674b7ac3eceda275)! Deleting and re-downloading...
2024-11-05T14:17:14Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-11-05T14:17:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-extracontent-textures.zip
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-11-05T14:17:14Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-extracontent-textures.zip
2024-11-05T14:17:14Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-11-05T14:17:21Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (16874222 bytes total)
2024-11-05T14:17:21Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-11-05T14:17:21Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-11-05T14:17:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-WebView2.zip
2024-11-05T14:17:21Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ExtraContent\textures\...
2024-11-05T14:17:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-WebView2.zip
2024-11-05T14:17:21Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-11-05T14:17:21Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-11-05T14:17:21Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-11-05T14:17:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-WebView2RuntimeInstaller.zip
2024-11-05T14:17:21Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a...
2024-11-05T14:17:21Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-11-05T14:17:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-WebView2RuntimeInstaller.zip
2024-11-05T14:17:22Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-11-05T14:17:22Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-11-05T14:17:22Z [Bootstrapper::DownloadPackage.redist.zip] Downloading...
2024-11-05T14:17:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-redist.zip
2024-11-05T14:17:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-redist.zip
2024-11-05T14:17:22Z [Bootstrapper::DownloadPackage.redist.zip] Finished downloading! (1372275 bytes total)
2024-11-05T14:17:22Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting redist.zip'
2024-11-05T14:17:22Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-11-05T14:17:23Z [Bootstrapper::SetStatus] Configuring Roblox...
```

**Comment by red-nt** [comment]
hey bud you're using 2.5.3 not 2.8.1
