### ISSUE TITLE
Content is denied?

### ISSUE THREAD

**Issue by F3DIC0** [bloxstraplabs/bloxstrap#3675]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Every time I try to open up ROBLOX using Bloxstrap the error message Access to the path "'\\?\C:\Users\censoredforprivacyreasons<3\AppData\Local\Bloxstrap\Roblox\Player.old\content\textures\Cursors\KeyboardMouse' is denied." keeps on popping up and I don't know what to do, can someone help me?

### Bloxstrap Log

```text
2024-11-05T22:44:00Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-05T22:44:00Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 6:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-05T22:44:00Z [App::OnStartup] Loaded from C:\Users\JUSTI_~1\AppData\Local\Temp\scoped_dir11684_969296325\Bloxstrap-v2.8.1.exe
2024-11-05T22:44:00Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-05T22:44:00Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-05T22:44:00Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap\Logs\Bloxstrap_20241105T224400Z.log
2024-11-05T22:44:00Z [Logger::Initialize] Finished initializing!
2024-11-05T22:44:07Z [MainWindow] Initializing installer window
2024-11-05T22:44:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-05T22:44:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-05T22:44:20Z [Installer::DoInstall] Beginning installation
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe,0' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\DisplayIcon
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing 'Bloxstrap' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\DisplayName
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '2.8.1' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\DisplayVersion
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '20241105' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\InstallDate
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '%UserProfile%\AppData\Local\Bloxstrap' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\InstallLocation
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '1' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\NoRepair
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing 'Bloxstrap' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\Publisher
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '"%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe" -settings' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\ModifyPath
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '"%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe" -uninstall -quiet' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\QuietUninstallString
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '"%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe" -uninstall' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\UninstallString
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing 'https://github.com/bloxstraplabs/bloxstrap/wiki' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\HelpLink
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing 'https://github.com/bloxstraplabs/bloxstrap/issues/new' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\URLInfoAbout
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing 'https://bloxstraplabs.com' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\URLUpdateInfo
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' to HKEY_CURRENT_USER\Software\Classes\roblox\DefaultIcon\
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '"%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe" -player "%1"' to HKEY_CURRENT_USER\Software\Classes\roblox\shell\open\command\
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' to HKEY_CURRENT_USER\Software\Classes\roblox-player\DefaultIcon\
2024-11-05T22:44:20Z [RegistryKeyEx::SetValueSafe] Writing '"%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe" -player "%1"' to HKEY_CURRENT_USER\Software\Classes\roblox-player\shell\open\command\
2024-11-05T22:44:20Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-05T22:44:20Z [JsonManager<Settings>::Load] Failed to load!
2024-11-05T22:44:20Z [JsonManager<Settings>::Load] (0x80070002) System.IO.FileNotFoundException: Could not find file '%UserProfile%\AppData\Local\Bloxstrap\Settings.json'.
File name: '%UserProfile%\AppData\Local\Bloxstrap\Settings.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Bloxstrap.JsonManager`1.Load(Boolean alertFailure)
2024-11-05T22:44:20Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-05T22:44:20Z [JsonManager<Settings>::Save] Save complete!
2024-11-05T22:44:20Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-05T22:44:20Z [JsonManager<State>::Load] Failed to load!
2024-11-05T22:44:20Z [JsonManager<State>::Load] (0x80070002) System.IO.FileNotFoundException: Could not find file '%UserProfile%\AppData\Local\Bloxstrap\State.json'.
File name: '%UserProfile%\AppData\Local\Bloxstrap\State.json'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Bloxstrap.JsonManager`1.Load(Boolean alertFailure)
2024-11-05T22:44:20Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-05T22:44:20Z [JsonManager<State>::Save] Save complete!
2024-11-05T22:44:20Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-05T22:44:20Z [FastFlagManager::Load] Failed to load!
2024-11-05T22:44:20Z [FastFlagManager::Load] (0x80070003) System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.File.InternalReadAllText(String path, Encoding encoding)
   at System.IO.File.ReadAllText(String path)
   at Bloxstrap.JsonManager`1.Load(Boolean alertFailure)
2024-11-05T22:44:20Z [FastFlagManager::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-05T22:44:20Z [FastFlagManager::Save] Save complete!
2024-11-05T22:44:20Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-11-05T22:44:20Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-11-05T22:44:20Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-05T22:44:20Z [JsonManager<Settings>::Save] Save complete!
2024-11-05T22:44:20Z [Installer::DoInstall] Installation finished
2024-11-05T22:44:20Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=installAction&value=install
2024-11-05T22:44:20Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://bloxstraplabs.com/metrics/post?key=installAction&value=install
2024-11-05T22:44:30Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-05T22:44:30Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-05T22:44:30Z [Bootstrapper::Run] Running bootstrapper
2024-11-05T22:44:30Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-05T22:44:30Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-05T22:44:30Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-05T22:44:30Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-05T22:44:30Z [Bootstrapper::Run] Connectivity check finished
2024-11-05T22:44:30Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-05T22:44:30Z [Bootstrapper::CheckForUpdates] No updates found
2024-11-05T22:44:30Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zbeta
2024-11-05T22:44:30Z [Deployment::GetInfo] Getting deploy info for channel zbeta
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zbeta
2024-11-05T22:44:30Z [Deployment::GetInfo] Getting deploy info for channel production
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zbeta
2024-11-05T22:44:30Z [RegistryKeyEx::SetValueSafe] Writing 'zbeta' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-11-05T22:44:30Z [ApplicationSettings::Fetch.PCClientBootstrapper.zbeta] Fetching fast flags
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zbeta
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zbeta
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-1ab005bd4b0844c1-rbxPkgManifest.txt
2024-11-05T22:44:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-1ab005bd4b0844c1-rbxPkgManifest.txt
2024-11-05T22:44:31Z [Bootstrapper::SetStatus] Installing {product}...
2024-11-05T22:44:31Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-11-05T22:44:31Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-11-05T22:44:31Z [App::FinalizeExceptionHandling] (0x80131620) System.IO.IOException: Access to the path '\\?\%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player.old\content\textures\Cursors\KeyboardMouse' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-11-05T22:44:31Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-11-05T22:44:31Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
```

**Comment by F3DIC0** [comment]
nevermind i fixed the issue!
