### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'RobloxCrashHandler.exe' is denied.

### ISSUE THREAD

**Issue by nisttarch** [bloxstraplabs/bloxstrap#3682]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

when i played a game my roblox client instantly crashed, i thought this was just no bother since this usually happens with high part count games, but when i tried to reopen bloxstrap it popped up with this error.

### Bloxstrap Log

```text
2024-11-06T19:50:28Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-06T19:50:28Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 6:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-06T19:50:28Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-11-06T19:50:28Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-06T19:50:28Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-06T19:50:28Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241106T195028Z.log
2024-11-06T19:50:28Z [Logger::Initialize] Finished initializing!
2024-11-06T19:50:28Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-06T19:50:28Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-06T19:50:28Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-06T19:50:28Z [JsonManager<State>::Load] Loaded successfully!
2024-11-06T19:50:28Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-06T19:50:28Z [FastFlagManager::Load] Loaded successfully!
2024-11-06T19:50:29Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-06T19:50:29Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-06T19:50:29Z [Bootstrapper::Run] Running bootstrapper
2024-11-06T19:50:29Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-06T19:50:29Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-06T19:50:29Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-06T19:50:29Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-06T19:50:30Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-06T19:50:30Z [Bootstrapper::Run] Connectivity check finished
2024-11-06T19:50:30Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-06T19:50:30Z [Bootstrapper::CheckForUpdates] No updates found
2024-11-06T19:50:30Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zprojectuwpua
2024-11-06T19:50:30Z [Deployment::GetInfo] Getting deploy info for channel zprojectuwpua
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zprojectuwpua
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zprojectuwpua
2024-11-06T19:50:30Z [Deployment::GetInfo] Getting deploy info for channel production
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-06T19:50:30Z [RegistryKeyEx::SetValueSafe] Writing 'zprojectuwpua' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-11-06T19:50:30Z [ApplicationSettings::Fetch.PCClientBootstrapper.zprojectuwpua] Fetching fast flags
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zprojectuwpua
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zprojectuwpua
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zprojectuwpua
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-5a857124208c404c-rbxPkgManifest.txt
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-5a857124208c404c-rbxPkgManifest.txt
2024-11-06T19:50:30Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-11-06T19:50:30Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-11-06T19:50:30Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-11-06T19:50:30Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'RobloxCrashHandler.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-11-06T19:50:30Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
I'm assuming this has been fixed with v2.8.2. If not, please open a new issue.
