### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\jacob\AppData\Local\Bloxstrap\Settings.json' is denied.

### ISSUE THREAD

**Issue by Naaodl** [bloxstraplabs/bloxstrap#3686]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.0

### What problem did you encounter?

I tried to save my settings, then this popped up! 
![a](https://github.com/user-attachments/assets/f3a9d8fc-2c95-4b86-968f-2ec062fe7fe0)

### Bloxstrap Log

```text
2024-11-07T03:12:26Z [App::OnStartup] Starting Bloxstrap v2.8.0
2024-11-07T03:12:26Z [App::OnStartup] Compiled Wednesday, 16 October 2024 at 10:44:37 AM from commit 42ffec26cf2e080fe22210305a08fcb286aeb577 (tag/v2.8.0)
2024-11-07T03:12:26Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Temp\scoped_dir13500_968446929\Bloxstrap-v2.8.0.exe
2024-11-07T03:12:26Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-07T03:12:26Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-07T03:12:26Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241107T031226Z.log
2024-11-07T03:12:26Z [Logger::Initialize] Finished initializing!
2024-11-07T03:12:26Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-07T03:12:26Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-07T03:12:26Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-07T03:12:26Z [JsonManager<State>::Load] Loaded successfully!
2024-11-07T03:12:26Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-07T03:12:26Z [FastFlagManager::Load] Loaded successfully!
2024-11-07T03:12:26Z [Installer::HandleUpgrade] Doing upgrade
2024-11-07T03:12:26Z [Installer::HandleUpgrade] Waiting for write permissions to update version
2024-11-07T03:12:31Z [Installer::HandleUpgrade] Failed to update! (Could not get write permissions after 10 tries/5 seconds)
2024-11-07T03:12:31Z [Installer::HandleUpgrade] System.IO.IOException: The process cannot access the file '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Bloxstrap.Installer.HandleUpgrade()
2024-11-07T03:12:35Z [MainWindow] Initializing settings window
2024-11-07T03:13:06Z [FastFlagManager::SetValue] Setting of 'FIntDebugForceMSAASamples' to '4' is pending
2024-11-07T03:13:15Z [FastFlagManager::SetValue] Setting of 'DFFlagTextureQualityOverrideEnabled' to 'True' is pending
2024-11-07T03:13:15Z [FastFlagManager::SetValue] Setting of 'DFIntTextureQualityOverride' to '3' is pending
2024-11-07T03:13:22Z [FastFlagManager::SetValue] Setting of 'FIntFullscreenTitleBarTriggerDelayMillis' to '3600000' is pending
2024-11-07T03:14:19Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-07T03:14:19Z [App::GlobalExceptionHandler] An exception occurred
2024-11-07T03:14:19Z [App::FinalizeExceptionHandling] System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Settings.json' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Bloxstrap.JsonManager`1.Save()
   at Bloxstrap.UI.ViewModels.Settings.MainWindowViewModel.SaveSettings()
   at CommunityToolkit.Mvvm.Input.RelayCommand.Execute(Object parameter)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by bluepilledgreat** [comment]
This bug has not been seen since 2.8.1, assumed fixed
