### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\Admin\AppData\Local\Bloxstrap\State.json' is denied.

### ISSUE THREAD

**Issue by ShogunplayzRoblox** [bloxstraplabs/bloxstrap#3726]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

I just encountered this now 

### Bloxstrap Log

```text
2024-11-09T06:48:31Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-09T06:48:31Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 6:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-09T06:48:31Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-11-09T06:48:31Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-09T06:48:31Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-09T06:48:31Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241109T064831Z.log
2024-11-09T06:48:31Z [Logger::Initialize] Finished initializing!
2024-11-09T06:48:31Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-09T06:48:31Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-09T06:48:31Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-09T06:48:31Z [JsonManager<State>::Load] Loaded successfully!
2024-11-09T06:48:31Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-09T06:48:31Z [FastFlagManager::Load] Loaded successfully!
2024-11-09T06:48:32Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-09T06:48:32Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-09T06:48:32Z [Bootstrapper::Run] Running bootstrapper
2024-11-09T06:48:32Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-09T06:48:32Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-09T06:48:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-09T06:48:33Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-09T06:48:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-09T06:48:34Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-09T06:48:34Z [Bootstrapper::Run] Connectivity check finished
2024-11-09T06:48:34Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-11-09T06:48:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-09T06:48:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-09T06:48:34Z [Bootstrapper::CheckForUpdates] No updates found
2024-11-09T06:48:34Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-11-09T06:48:34Z [Deployment::GetInfo] Getting deploy info for channel production
2024-11-09T06:48:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-09T06:48:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-09T06:48:34Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-11-09T06:48:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-09T06:48:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-09T06:48:34Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-11-09T06:48:34Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-11-09T06:48:34Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-11-09T06:48:34Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg already exists in the version folder, and is a match
2024-11-09T06:48:34Z [Bootstrapper::ApplyModifications] content\textures\Cursors\KeyboardMouse\ArrowCursor.png already exists in the version folder, and is a match
2024-11-09T06:48:34Z [Bootstrapper::ApplyModifications] content\textures\Cursors\KeyboardMouse\ArrowFarCursor.png already exists in the version folder, and is a match
2024-11-09T06:48:34Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-09T06:48:34Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-11-09T06:48:34Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-11-09T06:48:34Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\State.json' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Bloxstrap.JsonManager`1.Save()
   at Bloxstrap.Bootstrapper.ApplyModifications()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-11-09T06:48:34Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by MADARAshot** [comment]
хах тоже самое и у меня помогите плз
