### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'RobloxCrashHandler.exe' is denied.

### ISSUE THREAD

**Issue by IxGamerXL** [bloxstraplabs/bloxstrap#3731]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Upon starting Bloxstrap and launching Roblox, it immediately gives this error upon attempting to load. This doesn't occur if I play Roblox without Bloxstrap.

![Bloxstrap Exception - 2024-11-09 09_44_07](https://github.com/user-attachments/assets/189cffc4-961e-4bff-b1b9-b2522e15e8cf)

### Bloxstrap Log

```text
2024-11-09T15:42:08Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-09T15:42:08Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 5:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-09T15:42:08Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-11-09T15:42:08Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-09T15:42:08Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-09T15:42:08Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241109T154208Z.log
2024-11-09T15:42:08Z [Logger::Initialize] Finished initializing!
2024-11-09T15:42:08Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-09T15:42:08Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-09T15:42:08Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-09T15:42:08Z [JsonManager<State>::Load] Loaded successfully!
2024-11-09T15:42:08Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-09T15:42:08Z [FastFlagManager::Load] Loaded successfully!
2024-11-09T15:42:11Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-09T15:42:11Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-09T15:42:11Z [Bootstrapper::Run] Running bootstrapper
2024-11-09T15:42:11Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-09T15:42:11Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-09T15:42:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-09T15:42:11Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-09T15:42:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-09T15:42:11Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-09T15:42:11Z [Bootstrapper::Run] Connectivity check finished
2024-11-09T15:42:11Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-11-09T15:42:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-09T15:42:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-09T15:42:11Z [Bootstrapper::CheckForUpdates] No updates found
2024-11-09T15:42:11Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-11-09T15:42:11Z [Deployment::GetInfo] Getting deploy info for channel production
2024-11-09T15:42:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-09T15:42:12Z [Deployment::GetInfo] Failed to contact clientsettingscdn! Falling back to clientsettings...
2024-11-09T15:42:12Z [Deployment::GetInfo] (0x80131501) System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): The message received was unexpected or badly formatted.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.RobloxInterfaces.Deployment.GetInfo(String channel)
2024-11-09T15:42:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettings.roblox.com/v2/client-version/WindowsPlayer
2024-11-09T15:42:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettings.roblox.com/v2/client-version/WindowsPlayer
2024-11-09T15:42:12Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-11-09T15:42:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-09T15:42:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-09T15:42:12Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-11-09T15:42:12Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-11-09T15:42:12Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-11-09T15:42:12Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'RobloxCrashHandler.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-11-09T15:42:12Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-11-09T15:42:12Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
I'm assuming this has been fixed with v2.8.2. If not, please open a new issue.
