### ISSUE TITLE
(m  This is the exact message coming when I use a fast flag on 2.5.4 version. Please fix it and contact me via email, laddhanevaan@gmail.com if you have fixed it, I really hope you fix it as the fast flag i want to use is only available and best worked in this version. Please please fix this

### ISSUE THREAD

**Issue by ohlooka** [bloxstraplabs/bloxstrap#3732]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

![Screenshot 2024-11-09 234838](https://github.com/user-attachments/assets/441b42b8-74f5-459e-a7f2-7c81f12847c9)

### Bloxstrap Log

```text
2024-11-09T18:20:14Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-11-09T18:20:14Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 3:16:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-11-09T18:20:14Z [App::OnStartup] Loaded from %UserProfile%\OneDrive\Desktop\YT\Bloxstrap-v2.5.4.exe
2024-11-09T18:20:14Z [InstallChecker::FirstTimeRun] Running first-time install
2024-11-09T18:20:14Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20241109T182014Z.log
2024-11-09T18:20:14Z [Logger::Initialize] Finished initializing!
2024-11-09T18:20:14Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-11-09T18:20:14Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-11-09T18:20:14Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path 'C:\WINDOWS\system32\ClientSettings\ClientAppSettings.json'.
2024-11-09T18:20:14Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-11-09T18:20:14Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-11-09T18:20:14Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '120' is pending
2024-11-09T18:20:14Z [MainWindow::MainWindow] Initializing menu
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FFlagTaskSchedulerLimitTargetFpsTo2402' to 'False' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Changing of 'FFlagHandleAltEnterFullscreenManually' from 'False' to 'False' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Changing of 'FLogNetwork' from '7' to '7' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Changing of 'DFIntTaskSchedulerTargetFps' from '120' to '10000' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFFlagDisableDPIScale' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FFlagDisablePostFx' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FIntTerrainArraySliceSize' to '8' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FIntRenderShadowIntensity' to '0' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FFlagDebugGraphicsPreferD3D11FL10' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FFlagEnableInGameMenuChrome' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FIntFullscreenTitleBarTriggerDelayMillis' to '18000000' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FIntDebugForceMSAASamples' to '1' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FIntFontSizePadding' to '3' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FFlagEnableInGameMenuModernization' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFFlagTextureQualityOverrideEnabled' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntTextureQualityOverride' to '3' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFFlagEnableFmodErrorsTelemetry' to 'False' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntRakNetMtuValue3InBytes' to '1200' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FFlagReconnectDisabled' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntConnectionMTUSize' to '1472' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFFlagDebugPerfMode' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFStringRobloxAnalyticsURL' to 'http://opt-out.roblox.com/' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntCSGLevelOfDetailSwitchingDistanceL34' to '4' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FFlagBatchAssetApi' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntCSGLevelOfDetailSwitchingDistanceL12' to '2' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FIntFRMMinGrassDistance' to '0' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FFlagEnableChromePinnedChat' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntRaknetBandwidthPingSendEveryXSeconds' to '1' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntRakNetNakResendDelayRttPercent' to '50' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FFlagAdServiceEnabled' to 'False' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntRaknetBandwidthInfluxHundredthsPercentageV2' to '10000' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FIntMeshContentProviderForceCacheSize' to '268435456' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntCSGLevelOfDetailSwitchingDistance' to ' 1' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntRakNetMtuValue1InBytes' to '1280' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FFlagFastGPULightCulling3' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'FStringPerformanceSendMeasurementAPISubdomain' to 'opt-out' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFFlagDebugRenderForceTechnologyVoxel' to 'True' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFFlagGpuVsCpuBoundTelemetry' to 'False' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFStringAnalyticsEventStreamUrlEndpoint' to 'opt-out' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntAnimationLodFacsDistanceMax' to '0' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFStringHttpPointsReporterUrl' to 'http://opt-out.roblox.com/' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFIntCSGLevelOfDetailSwitchingDistanceL23' to '3' is pending
2024-11-09T18:20:27Z [FastFlagManager::SetValue] Setting of 'DFStringAltHttpPointsReporterUrl' to 'http://opt-out.roblox.com/' is pending
2024-11-09T18:20:34Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-11-09T18:20:34Z [App::OnStartup] Initializing bootstrapper
2024-11-09T18:20:34Z [App::OnStartup] Initializing bootstrapper dialog
2024-11-09T18:20:34Z [Bootstrapper::Run] Running bootstrapper
2024-11-09T18:20:34Z [Bootstrapper::Run] Performing connectivity check...
2024-11-09T18:20:34Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-09T18:20:34Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-11-09T18:20:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-11-09T18:20:35Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-11-09T18:20:35Z [Bootstrapper::Run] Connectivity check finished
2024-11-09T18:20:35Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-11-09T18:20:35Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-11-09T18:20:35Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-11-09T18:20:35Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-11-09T18:20:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-11-09T18:20:36Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-11-09T18:20:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-09T18:20:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxPkgManifest.txt
2024-11-09T18:20:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxManifest.txt
2024-11-09T18:20:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b7eebc919e96477a-rbxManifest.txt
2024-11-09T18:20:36Z [Bootstrapper::SetStatus] Installing Roblox...
2024-11-09T18:20:36Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-11-09T18:20:36Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-11-09T18:20:36Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a...
2024-11-09T18:20:36Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-11-09T18:20:36Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-11-09T18:20:36Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\avatar\...
2024-11-09T18:20:36Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-11-09T18:20:36Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-11-09T18:20:36Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\configs\...
2024-11-09T18:20:36Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-11-09T18:20:36Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-11-09T18:20:36Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\fonts\...
2024-11-09T18:20:36Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-11-09T18:20:36Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-11-09T18:20:36Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-11-09T18:20:36Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\models\...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\sky\...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\sounds\...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\shaders\...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ssl\...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\content\textures\...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\PlatformContent\pc\textures\...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\PlatformContent\pc\terrain\...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\PlatformContent\pc\fonts\...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-11-09T18:20:37Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting content-platform-dictionaries.zip'
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-11-09T18:20:37Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ExtraContent\places\...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ExtraContent\LuaPackages\...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ExtraContent\translations\...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ExtraContent\models\...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a\ExtraContent\textures\...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-b7eebc919e96477a...
2024-11-09T18:20:37Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-11-09T18:20:37Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting redist.zip'
2024-11-09T18:20:37Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-11-09T18:20:38Z [Bootstrapper::SetStatus] Configuring Roblox...
2024-11-09T18:20:39Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-11-09T18:20:41Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
```

**Comment by Naveandice** [comment]
Update your Bloxstrap. https://bloxstraplabs.com or https://github.com/bloxstraplabs/bloxstrap/releases/latest

**Comment by pizzaboxer** [comment]
there are so many things wrong here to unpack that i'm not even going to bother responding with a useful response
