### ISSUE TITLE
[BUG] Reinstalling Bloxstrap

### ISSUE THREAD

**Issue by Mizucchi** [bloxstraplabs/bloxstrap#3737]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Downloaded Bloxstrap since v2.5.4 and has been auto-updating just fine until the latest version v2.8.1. I uninstalled the Bloxstrapper and clicked on the button where it says to "keep previous settings" in the case where I were to reinstall Bloxstrap. I uninstalled at first to test some things out with the normal Roblox Player and then wanted to re-install, but encountered issues when re-installing. I've already uninstalled the normal Roblox Player at this point.

This was the Log I got from the only place where I could find anything about Bloxstrap left remaining. **C:\Users\AzryI\AppData\Local\Temp\Bloxstrap** , and it showed me quite a few Logs, first one being when I uninstalled:

2024-11-10T09:48:59Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-10T09:48:59Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 6:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-10T09:48:59Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-11-10T09:48:59Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-10T09:48:59Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-10T09:48:59Z [LaunchSettings] Identifier 'uninstall' is active
2024-11-10T09:48:59Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap\Logs\Bloxstrap_20241110T094859Z.log
2024-11-10T09:48:59Z [Logger::Initialize] Finished initializing!
2024-11-10T09:48:59Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-10T09:48:59Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-10T09:48:59Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-10T09:48:59Z [JsonManager<State>::Load] Loaded successfully!
2024-11-10T09:48:59Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-10T09:48:59Z [FastFlagManager::Load] Loaded successfully!
2024-11-10T09:49:07Z [Protocol::Unregister] Failed to unregister roblox-studio: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Bloxstrap.Utility.WindowsRegistry.Unregister(String key)
2024-11-10T09:49:07Z [Protocol::Unregister] Failed to unregister roblox-studio-auth: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Bloxstrap.Utility.WindowsRegistry.Unregister(String key)
2024-11-10T09:49:07Z [Protocol::Unregister] Failed to unregister Roblox.Place: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Bloxstrap.Utility.WindowsRegistry.Unregister(String key)
2024-11-10T09:49:07Z [Protocol::Unregister] Failed to unregister .rbxl: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Bloxstrap.Utility.WindowsRegistry.Unregister(String key)
2024-11-10T09:49:07Z [Protocol::Unregister] Failed to unregister .rbxlx: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Bloxstrap.Utility.WindowsRegistry.Unregister(String key)
2024-11-10T09:49:08Z [Installer::DoUninstall] Encountered exception when running cleanup sequence (#5)
2024-11-10T09:49:08Z [Installer::DoUninstall] (0x80070005) System.UnauthorizedAccessException: Access to the path 'Bloxstrap.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Bloxstrap.Installer.<>c.<DoUninstall>b__18_0()
   at Bloxstrap.Installer.DoUninstall(Boolean keepData)
2024-11-10T09:49:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=installAction&value=uninstall
2024-11-10T09:49:08Z [Frontend::ShowMessageBox] Bloxstrap has successfully uninstalled
2024-11-10T09:49:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://bloxstraplabs.com/metrics/post?key=installAction&value=uninstall
2024-11-10T09:49:09Z [App::Terminate] Terminating with exit code 0 (ERROR_SUCCESS)

Before this, my Bloxstrap was located on my Desktop, but after uninstalling it just vanished (obviously).
When re-installing using the latest installer - v2.8.1, it prompted me this:
"Bloxstrap does not have write access to the install location you've selected. Please use another location."
I've used this location before in my previous time installing Bloxstrap back in v2.5.4, and it worked fine, the only thing that remains from that install was the Bloxstrap destination folder I have which is only in my Temp file - **C:\Users\AzryI\AppData\Local\Temp\Bloxstrap**

![image](https://github.com/user-attachments/assets/92fc845f-09af-461c-8477-25b5b52250bc)

I tried to move the installation folder to my Desktop but it prompted me this instead:
"Bloxstrap cannot be installed here. Please choose a different location, or resort to using the default location by clicking the reset button."

![image](https://github.com/user-attachments/assets/61f0ef86-ad08-4b32-b056-59ede73eccac)

I tried to use the old installer as well - v2.5.4 to no avail.

I tried again and again but it only prompted more Logs in my Temp file in the Bloxstrap folder.
I've attempted to reinstall about 6 times but it shows similar logs to this one below:

2024-11-10T11:16:04Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-10T11:16:04Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 6:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-10T11:16:04Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.1.exe
2024-11-10T11:16:04Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-10T11:16:04Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-10T11:16:04Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap\Logs\Bloxstrap_20241110T111604Z.log
2024-11-10T11:16:04Z [Logger::Initialize] Finished initializing!
2024-11-10T11:16:05Z [MainWindow] Initializing installer window
2024-11-10T11:16:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-10T11:16:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-10T11:22:54Z [Frontend::ShowMessageBox] Are you sure you want to cancel the installation?
2024-11-10T11:22:56Z [App::Terminate] Terminating with exit code 1602 (ERROR_INSTALL_USEREXIT)

Any idea of what could be the issue?

Thank you.

### Bloxstrap Log

```text
N/A
```

**Comment by bluepilledgreat** [comment]
Maybe try to install Bloxstrap to somewhere other than your Desktop?
