### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'ArrowCursor.png' is denied.

### ISSUE THREAD

**Issue by F3DIC0** [bloxstraplabs/bloxstrap#3758]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

It keeps on telling me that "Access to the path 'ArrowCursor.png' is denied." and I've already tried deleting the file itself or replacing it but it still wont work, can someone please help me out.

### Bloxstrap Log

```text
2024-11-13T23:01:00Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-13T23:01:00Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 6:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-13T23:01:00Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-11-13T23:01:00Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-13T23:01:00Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-13T23:01:00Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241113T230100Z.log
2024-11-13T23:01:00Z [Logger::Initialize] Finished initializing!
2024-11-13T23:01:00Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-13T23:01:00Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-13T23:01:00Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-13T23:01:00Z [JsonManager<State>::Load] Loaded successfully!
2024-11-13T23:01:00Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-13T23:01:00Z [FastFlagManager::Load] Loaded successfully!
2024-11-13T23:01:01Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-13T23:01:01Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-13T23:01:01Z [Bootstrapper::Run] Running bootstrapper
2024-11-13T23:01:01Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-13T23:01:01Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-13T23:01:01Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-13T23:01:02Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-13T23:01:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-13T23:01:02Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-13T23:01:02Z [Bootstrapper::Run] Connectivity check finished
2024-11-13T23:01:02Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-11-13T23:01:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-13T23:01:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-13T23:01:02Z [Bootstrapper::CheckForUpdates] No updates found
2024-11-13T23:01:02Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-11-13T23:01:02Z [Deployment::GetInfo] Getting deploy info for channel production
2024-11-13T23:01:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-13T23:01:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-13T23:01:02Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-11-13T23:01:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-rbxPkgManifest.txt
2024-11-13T23:01:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-rbxPkgManifest.txt
2024-11-13T23:01:02Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-11-13T23:01:02Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-11-13T23:01:02Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-11-13T23:01:02Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'ArrowCursor.png' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-11-13T23:01:02Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by F3DIC0** [comment]
Update, I have uninstalled and reinstalled Bloxstrap, and yet it still gives me the same error message

**Comment by F3DIC0** [comment]
help why do i accidentally close this lol T-T

**Comment by F3DIC0** [comment]
Found out the issue, turns out the file it was trying to reach was in Player.Old instead of Player, I have fixed the issue!
