### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by grSPEC** [bloxstraplabs/bloxstrap#3764]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

what is this poopoo "System.IO.IOException: Access to the path '\\?\C:\Users\example\AppData\Local\Bloxstrap\Roblox\Player.old\content\textures\Cursors\KeyboardMouse' is denied."
can it be fixed

### Bloxstrap Log

```text
2024-11-14T20:11:16Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-14T20:11:16Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 7:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-14T20:11:16Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-11-14T20:11:16Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-14T20:11:16Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-14T20:11:16Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241114T201116Z.log
2024-11-14T20:11:16Z [Logger::Initialize] Finished initializing!
2024-11-14T20:11:16Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241105T175934Z.log'
2024-11-14T20:11:16Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241105T180045Z.log'
2024-11-14T20:11:16Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241105T213549Z.log'
2024-11-14T20:11:16Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241105T213557Z.log'
2024-11-14T20:11:16Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241106T121630Z.log'
2024-11-14T20:11:16Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241106T121726Z.log'
2024-11-14T20:11:16Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241106T121745Z.log'
2024-11-14T20:11:16Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-14T20:11:16Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-14T20:11:16Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-14T20:11:16Z [JsonManager<State>::Load] Loaded successfully!
2024-11-14T20:11:16Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-14T20:11:16Z [FastFlagManager::Load] Loaded successfully!
2024-11-14T20:15:01Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-14T20:15:01Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-14T20:15:01Z [Bootstrapper::Run] Running bootstrapper
2024-11-14T20:15:01Z [Bootstrapper::SetStatus] Conectando-se ao Roblox...
2024-11-14T20:15:02Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-14T20:15:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-14T20:15:02Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-14T20:15:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-14T20:15:02Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-14T20:15:02Z [Bootstrapper::Run] Connectivity check finished
2024-11-14T20:15:02Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-11-14T20:15:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-14T20:15:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-11-14T20:15:03Z [Bootstrapper::CheckForUpdates] No updates found
2024-11-14T20:15:03Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-11-14T20:15:03Z [Deployment::GetInfo] Getting deploy info for channel production
2024-11-14T20:15:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-14T20:15:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-14T20:15:03Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-11-14T20:15:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-rbxPkgManifest.txt
2024-11-14T20:15:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-rbxPkgManifest.txt
2024-11-14T20:15:03Z [Bootstrapper::SetStatus] Atualizando {product}...
2024-11-14T20:15:03Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-11-14T20:15:03Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-11-14T20:15:03Z [App::FinalizeExceptionHandling] (0x80131620) System.IO.IOException: Access to the path '\\?\%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player.old\content\textures\Cursors\KeyboardMouse' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-11-14T20:15:03Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by RyanLua** [comment]
Duplicate of #3592
