### ISSUE TITLE
[BUG] crashing downloading

### ISSUE THREAD

**Issue by 123eblan123** [bloxstraplabs/bloxstrap#3797]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.5.3

### What problem did you encounter?

cannot download(((

### Bloxstrap Log

```text
2024-11-20T16:41:41Z [App::OnStartup] Starting Bloxstrap v2.5.3
2024-11-20T16:41:41Z [App::OnStartup] Compiled Tuesday, 18 June 2024 at 7:39:08 PM from DESKTOP-FGF6DO8\User
2024-11-20T16:41:41Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-11-20T16:41:41Z [InstallChecker::FirstTimeRun] Running first-time install
2024-11-20T16:41:41Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20241120T164141Z.log
2024-11-20T16:41:41Z [Logger::Initialize] Finished initializing!
2024-11-20T16:41:41Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-11-20T16:41:41Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-11-20T16:41:41Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\ClientSettings\ClientAppSettings.json'.
2024-11-20T16:41:42Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-11-20T16:41:42Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-11-20T16:41:42Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '120' is pending
2024-11-20T16:41:43Z [MainWindow::MainWindow] Initializing menu
2024-11-20T16:42:31Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-11-20T16:42:31Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-11-20T16:42:31Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-11-20T16:42:31Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-11-20T16:42:34Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-11-20T16:42:34Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-11-20T16:42:34Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-11-20T16:42:34Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-11-20T16:42:39Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=True)
2024-11-20T16:42:39Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-11-20T16:42:40Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-11-20T16:42:40Z [RobloxDeployment::GetInfo] Getting extra information...
2024-11-20T16:42:40Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-11-20T16:42:40Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-11-20T16:42:41Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-11-20T16:42:41Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-11-20T16:42:41Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-rbxPkgManifest.txt
2024-11-20T16:42:42Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-rbxPkgManifest.txt
2024-11-20T16:42:42Z [RobloxDeployment::GetInfo] https://setup.rbxcdn.com/version-32f36ac944b34913-rbxPkgManifest.txt - Last-Modified: Tue, 12 Nov 2024 19:09:08 GMT
2024-11-20T16:42:54Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-11-20T16:42:54Z [App::OnStartup] Initializing bootstrapper
2024-11-20T16:42:54Z [App::OnStartup] Initializing bootstrapper dialog
2024-11-20T16:42:54Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-11-20T16:42:54Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-11-20T16:42:54Z [BootstrapperIconEx::GetIcon] Failed to load custom icon!
2024-11-20T16:42:54Z [BootstrapperIconEx::GetIcon] System.ArgumentException: Empty path name is not legal. (Parameter 'path')
   at System.IO.Strategies.FileStreamHelpers.ValidateArguments(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Drawing.Icon..ctor(String fileName, Int32 width, Int32 height)
   at System.Drawing.Icon..ctor(String fileName)
   at Bloxstrap.Extensions.BootstrapperIconEx.GetIcon(BootstrapperIcon icon)
2024-11-20T16:42:54Z [Bootstrapper::Run] Running bootstrapper
2024-11-20T16:42:54Z [Bootstrapper::Run] Performing connectivity check...
2024-11-20T16:42:54Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-20T16:42:54Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-11-20T16:42:54Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-11-20T16:42:54Z [Bootstrapper::Run] Connectivity check finished
2024-11-20T16:42:54Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-11-20T16:42:54Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-11-20T16:42:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-rbxPkgManifest.txt
2024-11-20T16:42:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-rbxPkgManifest.txt
2024-11-20T16:42:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-rbxManifest.txt
2024-11-20T16:42:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-rbxManifest.txt
2024-11-20T16:42:54Z [Bootstrapper::SetStatus] Installing Roblox...
2024-11-20T16:42:54Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-11-20T16:42:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-RobloxApp.zip
2024-11-20T16:42:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-RobloxApp.zip
2024-11-20T16:43:02Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (88649763 bytes total)
2024-11-20T16:43:02Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-11-20T16:43:02Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-11-20T16:43:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-content-avatar.zip
2024-11-20T16:43:02Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913...
2024-11-20T16:43:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-content-avatar.zip
2024-11-20T16:43:02Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (461291 bytes total)
2024-11-20T16:43:02Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-11-20T16:43:02Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-11-20T16:43:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-content-configs.zip
2024-11-20T16:43:02Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\content\avatar\...
2024-11-20T16:43:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-content-configs.zip
2024-11-20T16:43:03Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (256269 bytes total)
2024-11-20T16:43:03Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-11-20T16:43:03Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-11-20T16:43:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-content-fonts.zip
2024-11-20T16:43:03Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\content\configs\...
2024-11-20T16:43:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-content-fonts.zip
2024-11-20T16:43:03Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-11-20T16:43:03Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-11-20T16:43:03Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-11-20T16:43:04Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-11-20T16:43:04Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-11-20T16:43:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-content-models.zip
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\content\fonts\...
2024-11-20T16:43:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-content-models.zip
2024-11-20T16:43:04Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (491904 bytes total)
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-11-20T16:43:04Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-11-20T16:43:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-content-sky.zip
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\content\models\...
2024-11-20T16:43:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-content-sky.zip
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-11-20T16:43:04Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-11-20T16:43:04Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-11-20T16:43:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-content-sounds.zip
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\content\sky\...
2024-11-20T16:43:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-content-sounds.zip
2024-11-20T16:43:04Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (597244 bytes total)
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-11-20T16:43:04Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-11-20T16:43:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-shaders.zip
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\content\sounds\...
2024-11-20T16:43:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-shaders.zip
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-11-20T16:43:04Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-11-20T16:43:05Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (9323682 bytes total)
2024-11-20T16:43:05Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-11-20T16:43:05Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-11-20T16:43:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-ssl.zip
2024-11-20T16:43:05Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\shaders\...
2024-11-20T16:43:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-ssl.zip
2024-11-20T16:43:05Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (135951 bytes total)
2024-11-20T16:43:05Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-11-20T16:43:05Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-11-20T16:43:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-content-textures2.zip
2024-11-20T16:43:05Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\ssl\...
2024-11-20T16:43:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-content-textures2.zip
2024-11-20T16:43:05Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-11-20T16:43:06Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-11-20T16:43:07Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (12449423 bytes total)
2024-11-20T16:43:07Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-11-20T16:43:07Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-11-20T16:43:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-content-textures3.zip
2024-11-20T16:43:07Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\content\textures\...
2024-11-20T16:43:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-content-textures3.zip
2024-11-20T16:43:08Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-11-20T16:43:08Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-11-20T16:43:08Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-11-20T16:43:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-content-terrain.zip
2024-11-20T16:43:08Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\PlatformContent\pc\textures\...
2024-11-20T16:43:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-content-terrain.zip
2024-11-20T16:43:08Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-11-20T16:43:08Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-11-20T16:43:08Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-11-20T16:43:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-content-platform-fonts.zip
2024-11-20T16:43:08Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\PlatformContent\pc\terrain\...
2024-11-20T16:43:08Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-11-20T16:43:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-content-platform-fonts.zip
2024-11-20T16:43:08Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-11-20T16:43:09Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-11-20T16:43:09Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-11-20T16:43:09Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Downloading...
2024-11-20T16:43:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-content-platform-dictionaries.zip
2024-11-20T16:43:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-content-platform-dictionaries.zip
2024-11-20T16:43:09Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\PlatformContent\pc\fonts\...
2024-11-20T16:43:09Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Finished downloading! (152263 bytes total)
2024-11-20T16:43:09Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting content-platform-dictionaries.zip'
2024-11-20T16:43:09Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-11-20T16:43:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-extracontent-places.zip
2024-11-20T16:43:09Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-11-20T16:43:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-extracontent-places.zip
2024-11-20T16:43:10Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1267431 bytes total)
2024-11-20T16:43:10Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-11-20T16:43:10Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-11-20T16:43:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-extracontent-luapackages.zip
2024-11-20T16:43:10Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\ExtraContent\places\...
2024-11-20T16:43:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-extracontent-luapackages.zip
2024-11-20T16:43:10Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-11-20T16:43:10Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (6611684 bytes total)
2024-11-20T16:43:10Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-11-20T16:43:10Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-11-20T16:43:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-extracontent-translations.zip
2024-11-20T16:43:10Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\ExtraContent\LuaPackages\...
2024-11-20T16:43:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-extracontent-translations.zip
2024-11-20T16:43:10Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-11-20T16:43:10Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (484131 bytes total)
2024-11-20T16:43:10Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-11-20T16:43:10Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-11-20T16:43:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-extracontent-models.zip
2024-11-20T16:43:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-extracontent-models.zip
2024-11-20T16:43:11Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\ExtraContent\translations\...
2024-11-20T16:43:11Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-11-20T16:43:11Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-11-20T16:43:13Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (24517086 bytes total)
2024-11-20T16:43:13Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-11-20T16:43:13Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-11-20T16:43:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-extracontent-textures.zip
2024-11-20T16:43:13Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\ExtraContent\models\...
2024-11-20T16:43:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-extracontent-textures.zip
2024-11-20T16:43:13Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-11-20T16:43:15Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (17167435 bytes total)
2024-11-20T16:43:15Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-11-20T16:43:15Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-11-20T16:43:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-WebView2.zip
2024-11-20T16:43:15Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913\ExtraContent\textures\...
2024-11-20T16:43:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-WebView2.zip
2024-11-20T16:43:15Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-11-20T16:43:15Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-11-20T16:43:15Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-11-20T16:43:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-WebView2RuntimeInstaller.zip
2024-11-20T16:43:15Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-32f36ac944b34913...
2024-11-20T16:43:15Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-11-20T16:43:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-WebView2RuntimeInstaller.zip
2024-11-20T16:43:15Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-11-20T16:43:15Z [Bootstrapper::DownloadPackage.redist.zip] Downloading...
2024-11-20T16:43:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-32f36ac944b34913-redist.zip
2024-11-20T16:43:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-32f36ac944b34913-redist.zip
2024-11-20T16:43:15Z [Bootstrapper::DownloadPackage.redist.zip] Finished downloading! (1372275 bytes total)
2024-11-20T16:43:15Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting redist.zip'
2024-11-20T16:43:15Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-11-20T16:43:16Z [Bootstrapper::SetStatus] Configuring Roblox...
2024-11-20T16:43:18Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-11-20T16:43:22Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-11-20T16:43:47Z [App::Terminate] Terminating with exit code 1603 (ERROR_INSTALL_FAILURE)
2024-11-20T16:43:47Z [JsonManager<Settings>::Save] Save request ignored
2024-11-20T16:43:47Z [JsonManager<State>::Save] Save request ignored
2024-11-20T16:43:47Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
```

**Comment by DanGameZone** [comment]
and you arent even using the latest bloxstrap

**Comment by bluepilledgreat** [comment]
Update Bloxstrap.
