### ISSUE TITLE
[BUG] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)  [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

### ISSUE THREAD

**Issue by zen763** [bloxstraplabs/bloxstrap#3804]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.5.3

### What problem did you encounter?

2024-11-21T13:50:42Z [App::OnStartup] Starting Bloxstrap v2.5.3
2024-11-21T13:50:42Z [App::OnStartup] Compiled Wednesday, 11 October 2023 at 8:29:04 PM from commit a099d160726f4d5ac832f97a8e167ae0338193ad (tag/v2.5.3)
2024-11-21T13:50:42Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.5.3 (1).exe
2024-11-21T13:50:42Z [InstallChecker::FirstTimeRun] Running first-time install
2024-11-21T13:50:42Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20241121T135042Z.log
2024-11-21T13:50:42Z [Logger::Initialize] Finished initializing!
2024-11-21T13:50:42Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-11-21T13:50:42Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-11-21T13:50:42Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path 'C:\Windows\system32\ClientSettings\ClientAppSettings.json'.
2024-11-21T13:50:42Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-11-21T13:50:42Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-11-21T13:50:42Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '144' is pending
2024-11-21T13:50:43Z [MainWindow::MainWindow] Initializing menu
2024-11-21T13:50:50Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-11-21T13:50:50Z [App::OnStartup] Initializing bootstrapper
2024-11-21T13:50:50Z [App::OnStartup] Initializing bootstrapper dialog
2024-11-21T13:50:50Z [Bootstrapper::Run] Running bootstrapper
2024-11-21T13:50:50Z [Bootstrapper::Run] Performing connectivity check...
2024-11-21T13:50:50Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-11-21T13:50:50Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-11-21T13:50:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-11-21T13:50:51Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-11-21T13:50:51Z [Bootstrapper::Run] Connectivity check finished
2024-11-21T13:50:51Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-11-21T13:50:51Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-11-21T13:50:51Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-11-21T13:50:51Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-11-21T13:50:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-11-21T13:50:52Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-11-21T13:50:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-rbxPkgManifest.txt
2024-11-21T13:50:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-rbxPkgManifest.txt
2024-11-21T13:50:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-rbxManifest.txt
2024-11-21T13:50:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-rbxManifest.txt
2024-11-21T13:50:52Z [Bootstrapper::SetStatus] Installing Roblox...
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\avatar\...
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\configs\...
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\models\...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\fonts\...
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\sky\...
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\sounds\...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\shaders\...
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ssl\...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\textures\...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\PlatformContent\pc\textures\...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\PlatformContent\pc\terrain\...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\PlatformContent\pc\fonts\...
2024-11-21T13:50:53Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting content-platform-dictionaries.zip'
2024-11-21T13:50:53Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-11-21T13:50:53Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ExtraContent\places\...
2024-11-21T13:50:53Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-11-21T13:50:54Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ExtraContent\LuaPackages\...
2024-11-21T13:50:54Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ExtraContent\translations\...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-11-21T13:50:54Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ExtraContent\models\...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-11-21T13:50:54Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ExtraContent\textures\...
2024-11-21T13:50:54Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-11-21T13:50:54Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-11-21T13:50:54Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-11-21T13:50:54Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting redist.zip'
2024-11-21T13:50:54Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-11-21T13:50:54Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-11-21T13:50:55Z [Bootstrapper::SetStatus] Configuring Roblox...
2024-11-21T13:50:56Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-11-21T13:50:58Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
![Screenshot 2024-11-21 210042](https://github.com/user-attachments/assets/d9a629a0-d0f9-4697-8ee8-8d3d612ed6b1)

### Bloxstrap Log

```text
N/A
```

**Comment by theletron** [comment]
### Your version of Bloxstrap is out of date
Please update to the latest version. You can install the latest version from here:
https://github.com/bloxstraplabs/bloxstrap/releases/latest

**Comment by DanGameZone** [comment]
Update, and no we don’t give a shit about multi instance

**Comment by bluepilledgreat** [comment]
Update Bloxstrap.
