### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by an3377** [bloxstraplabs/bloxstrap#3806]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

when i go to settings it suddenly notify me, i previously installed bloxstrap and used it but because it was too laggy i deleted it, but when i fixed my computer i reinstalled it and it sent me that notification

### Bloxstrap Log

```text
2024-11-18T10:20:10Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-11-18T10:20:10Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 5:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-11-18T10:20:10Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.1.exe
2024-11-18T10:20:10Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-18T10:20:10Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-18T10:20:10Z [App::GlobalExceptionHandler] An exception occurred
2024-11-18T10:20:11Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'C:\Program Files\Bloxstrap.exe' is denied.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-11-18T10:20:11Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by SilverT4** [comment]
Where did you install Bloxstrap to? `C:\Program Files` is a protected directory of your Windows installation, so by default normal programs won't have access to it. Try running Bloxstrap as an administrator, or reinstalling Bloxstrap without changing its install directory.
