### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:\Users\Admin\AppData\Local\Programs\Wave\bin\Bloxstrap.exe' with working directory 'C:\Users\Admin\AppData\Local\Programs\Wave'. Access is denied.

### ISSUE THREAD

**Issue by hoanganh0909** [bloxstraplabs/bloxstrap#3820]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

what error is this admin

### Bloxstrap Log

```text
2024-11-23T05:51:07Z [App::OnStartup] Starting Bloxstrap v4.2.1
2024-11-23T05:51:07Z [App::OnStartup] Compiled Thursday, 31 October 2024 at 5:24:35 AM from LUKECOMPUTER\minet
2024-11-23T05:51:07Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Programs\Wave\bin\Bloxstrap.exe
2024-11-23T05:51:07Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-11-23T05:51:07Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-11-23T05:51:07Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241123T055107Z.log
2024-11-23T05:51:07Z [Logger::Initialize] Finished initializing!
2024-11-23T05:51:07Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-11-23T05:51:07Z [JsonManager<Settings>::Load] Loaded successfully!
2024-11-23T05:51:07Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-23T05:51:07Z [JsonManager<State>::Load] Loaded successfully!
2024-11-23T05:51:07Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-11-23T05:51:07Z [FastFlagManager::Load] Loaded successfully!
2024-11-23T05:51:07Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-11-23T05:51:07Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-11-23T05:51:14Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-11-23T05:51:14Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-11-23T05:51:14Z [Bootstrapper::Run] Running bootstrapper
2024-11-23T05:51:14Z [Bootstrapper::SetStatus] Đang kết nối đến Roblox...
2024-11-23T05:51:14Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-11-23T05:51:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-11-23T05:51:14Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-11-23T05:51:14Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-11-23T05:51:14Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-11-23T05:51:14Z [Bootstrapper::Run] Connectivity check finished
2024-11-23T05:51:14Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-11-23T05:51:14Z [Deployment::GetInfo] Getting deploy info for channel production
2024-11-23T05:51:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-23T05:51:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-11-23T05:51:15Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-11-23T05:51:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-rbxPkgManifest.txt
2024-11-23T05:51:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-rbxPkgManifest.txt
2024-11-23T05:51:15Z [Bootstrapper::SetStatus] Đang áp dụng những chỉnh sửa cho Roblox...
2024-11-23T05:51:15Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-11-23T05:51:15Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-11-23T05:51:15Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-11-23T05:51:15Z [JsonManager<State>::Save] Save complete!
2024-11-23T05:51:15Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-11-23T05:51:15Z [Bootstrapper::SetStatus] Đang khởi động {product}...
2024-11-23T05:51:15Z [Bootstrapper::StartRoblox] Started Roblox (PID 4312), waiting for log file
2024-11-23T05:51:16Z [Bootstrapper::StartRoblox] Got log file as %UserProfile%\AppData\Local\Roblox\logs\0.652.0.6520764_20241123T055116Z_Player_F4728_last.log
2024-11-23T05:51:19Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-11-23T05:51:19Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-11-23T05:51:19Z [App::FinalizeExceptionHandling] (0x80004005) System.ComponentModel.Win32Exception (5): An error occurred trying to start process '%UserProfile%\AppData\Local\Programs\Wave\bin\Bloxstrap.exe' with working directory '%UserProfile%\AppData\Local\Programs\Wave'. Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by SQQ2019** [comment]
not sure

**Comment by moyaimoment** [comment]
You are actually braindead LMFAOO.
