### ISSUE TITLE
[BUG] content-platform-dictionaries.zip

### ISSUE THREAD

**Issue by luke1for1** [bloxstraplabs/bloxstrap#3888]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.3

### What problem did you encounter?

When I install it just gives me a error :

System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)

[Inner Exception]
System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.

![image](https://github.com/user-attachments/assets/f52f8419-750a-4515-af46-09d746499c5e)

### Bloxstrap Log

```text
2024-12-03T02:24:00Z [App::OnStartup] Starting Bloxstrap v2.5.3
2024-12-03T02:24:00Z [App::OnStartup] Compiled Tuesday, 18 June 2024 at 12:39:08 PM from DESKTOP-FGF6DO8\User
2024-12-03T02:24:00Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-03T02:24:00Z [InstallChecker::FirstTimeRun] Running first-time install
2024-12-03T02:24:00Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20241203T022400Z.log
2024-12-03T02:24:00Z [Logger::Initialize] Finished initializing!
2024-12-03T02:24:00Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-12-03T02:24:00Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-12-03T02:24:00Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\AppData\Local\Wave\ClientSettings\ClientAppSettings.json'.
2024-12-03T02:24:00Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-12-03T02:24:00Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-12-03T02:24:00Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '144' is pending
2024-12-03T02:24:00Z [MainWindow::MainWindow] Initializing menu
2024-12-03T02:26:05Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-12-03T02:26:05Z [App::OnStartup] Initializing bootstrapper
2024-12-03T02:26:05Z [App::OnStartup] Initializing bootstrapper dialog
2024-12-03T02:26:05Z [Bootstrapper::Run] Running bootstrapper
2024-12-03T02:26:05Z [Bootstrapper::Run] Performing connectivity check...
2024-12-03T02:26:05Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-03T02:26:05Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-12-03T02:26:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-12-03T02:26:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-12-03T02:26:05Z [Bootstrapper::Run] Connectivity check finished
2024-12-03T02:26:05Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-12-03T02:26:05Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-12-03T02:26:05Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-12-03T02:26:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-12-03T02:26:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-12-03T02:26:05Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-12-03T02:26:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-rbxPkgManifest.txt
2024-12-03T02:26:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-rbxPkgManifest.txt
2024-12-03T02:26:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-rbxManifest.txt
2024-12-03T02:26:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-rbxManifest.txt
2024-12-03T02:26:05Z [Bootstrapper::SetStatus] Installing Roblox...
2024-12-03T02:26:05Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-12-03T02:26:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-RobloxApp.zip
2024-12-03T02:26:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-RobloxApp.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (88492120 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-avatar.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-avatar.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (516549 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\avatar\...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-configs.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-configs.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (256270 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\configs\...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-fonts.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-fonts.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\fonts\...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-models.zip
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-models.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (491904 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\models\...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-sky.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-sky.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\sky\...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-sounds.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-sounds.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (597244 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\sounds\...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-shaders.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-shaders.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (9345681 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\shaders\...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-ssl.zip
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-ssl.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (135951 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ssl\...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-textures2.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-textures2.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (13549632 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\content\textures\...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-textures3.zip
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-textures3.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\PlatformContent\pc\textures\...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-terrain.zip
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-terrain.zip
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\PlatformContent\pc\terrain\...
2024-12-03T02:26:07Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-platform-fonts.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-03T02:26:07Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-03T02:26:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-platform-fonts.zip
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Downloading...
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-platform-dictionaries.zip
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\PlatformContent\pc\fonts\...
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-content-platform-dictionaries.zip
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Finished downloading! (152263 bytes total)
2024-12-03T02:26:08Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting content-platform-dictionaries.zip'
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-extracontent-places.zip
2024-12-03T02:26:08Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-extracontent-places.zip
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1267431 bytes total)
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ExtraContent\places\...
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-extracontent-luapackages.zip
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-extracontent-luapackages.zip
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (6622887 bytes total)
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ExtraContent\LuaPackages\...
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-extracontent-translations.zip
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-extracontent-translations.zip
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (484131 bytes total)
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-extracontent-models.zip
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ExtraContent\translations\...
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-extracontent-models.zip
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (24968875 bytes total)
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ExtraContent\models\...
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-extracontent-textures.zip
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-extracontent-textures.zip
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (17130170 bytes total)
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a\ExtraContent\textures\...
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-WebView2.zip
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-WebView2.zip
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-8aa36bbf0eb1494a...
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-WebView2RuntimeInstaller.zip
2024-12-03T02:26:08Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-WebView2RuntimeInstaller.zip
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.redist.zip] Downloading...
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-redist.zip
2024-12-03T02:26:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-8aa36bbf0eb1494a-redist.zip
2024-12-03T02:26:08Z [Bootstrapper::DownloadPackage.redist.zip] Finished downloading! (1372275 bytes total)
2024-12-03T02:26:08Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting redist.zip'
2024-12-03T02:26:08Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-12-03T02:26:09Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-03T02:26:09Z [Bootstrapper::SetStatus] Configuring Roblox...
```

**Comment by bluepilledgreat** [comment]
Install the latest version of Bloxstrap
