### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'E:\GOD Roblox\Bloxstrap\State.json' is denied.

### ISSUE THREAD

**Issue by THEEsso** [bloxstraplabs/bloxstrap#3906]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.5.4

### What problem did you encounter?

no stap

### Bloxstrap Log

```text
2024-12-05T15:57:41Z [App::OnStartup] Starting Bloxstrap v4.2.1
2024-12-05T15:57:41Z [App::OnStartup] Compiled Thursday, 31 October 2024 at 5:24:35 AM from LUKECOMPUTER\minet
2024-12-05T15:57:41Z [App::OnStartup] Loaded from E:\GOD Roblox\Bloxstrap\Bloxstrap.exe
2024-12-05T15:57:41Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-05T15:57:41Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-05T15:57:41Z [LaunchSettings] Identifier 'player' is active with data
2024-12-05T15:57:41Z [Logger::Initialize] Initializing at E:\GOD Roblox\Bloxstrap\Logs\Bloxstrap_25671205T155741Z.log
2024-12-05T15:57:41Z [Logger::Initialize] Finished initializing!
2024-12-05T15:57:41Z [JsonManager<Settings>::Load] Loading from E:\GOD Roblox\Bloxstrap\Settings.json...
2024-12-05T15:57:41Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-05T15:57:41Z [JsonManager<State>::Load] Loading from E:\GOD Roblox\Bloxstrap\State.json...
2024-12-05T15:57:41Z [JsonManager<State>::Load] Loaded successfully!
2024-12-05T15:57:41Z [FastFlagManager::Load] Loading from E:\GOD Roblox\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-05T15:57:41Z [FastFlagManager::Load] Loaded successfully!
2024-12-05T15:57:41Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-12-05T15:57:41Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-12-05T15:57:41Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-05T15:57:41Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-05T15:57:41Z [Bootstrapper::Run] Running bootstrapper
2024-12-05T15:57:41Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-05T15:57:41Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-05T15:57:41Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-05T15:57:41Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-05T15:57:42Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-05T15:57:42Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-05T15:57:42Z [Bootstrapper::Run] Connectivity check finished
2024-12-05T15:57:42Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-05T15:57:42Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-05T15:57:42Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-05T15:57:42Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-05T15:57:42Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-05T15:57:42Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-05T15:57:42Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-05T15:57:42Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-05T15:57:42Z [Bootstrapper::UpgradeRoblox] Could not clear old files, aborting update.
2024-12-05T15:57:42Z [Bootstrapper::UpgradeRoblox] (0x80070020) System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.FileSystem.MoveDirectory(String sourceFullPath, String destFullPath)
   at System.IO.Directory.Move(String sourceDirName, String destDirName)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
2024-12-05T15:57:42Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-12-05T15:57:42Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-12-05T15:57:42Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-12-05T15:57:42Z [JsonManager<State>::Save] Saving to E:\GOD Roblox\Bloxstrap\State.json...
2024-12-05T15:57:42Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-05T15:57:42Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-05T15:57:42Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'E:\GOD Roblox\Bloxstrap\State.json' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Bloxstrap.JsonManager`1.Save()
   at Bloxstrap.Bootstrapper.ApplyModifications()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by bluepilledgreat** [comment]
We do not support forks.
