### ISSUE TITLE
[BUG] System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Admin\AppData\Local\Roblox\logs'.

### ISSUE THREAD

**Issue by hadepzai2** [bloxstraplabs/bloxstrap#3909]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

2024-12-05T23:59:44Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-05T23:59:44Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 5:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-05T23:59:44Z [App::OnStartup] Loaded from D:\Release\Bloxstrap\Bloxstrap.exe
2024-12-05T23:59:44Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-05T23:59:44Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-05T23:59:44Z [Logger::Initialize] Initializing at D:\Release\Bloxstrap\Logs\Bloxstrap_20241205T235944Z.log
2024-12-05T23:59:44Z [Logger::Initialize] Finished initializing!
2024-12-05T23:59:44Z [JsonManager<Settings>::Load] Loading from D:\Release\Bloxstrap\Settings.json...
2024-12-05T23:59:44Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-05T23:59:44Z [JsonManager<State>::Load] Loading from D:\Release\Bloxstrap\State.json...
2024-12-05T23:59:44Z [JsonManager<State>::Load] Loaded successfully!
2024-12-05T23:59:44Z [FastFlagManager::Load] Loading from D:\Release\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-05T23:59:44Z [FastFlagManager::Load] Loaded successfully!
2024-12-05T23:59:46Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-05T23:59:46Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-05T23:59:46Z [Bootstrapper::Run] Running bootstrapper
2024-12-05T23:59:46Z [Bootstrapper::SetStatus] Đang kết nối đến Roblox...
2024-12-05T23:59:46Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-05T23:59:46Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-05T23:59:46Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-05T23:59:46Z [Bootstrapper::Run] Connectivity check finished
2024-12-05T23:59:46Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-05T23:59:46Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-05T23:59:46Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-05T23:59:46Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-05T23:59:46Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-05T23:59:46Z [Bootstrapper::SetStatus] Đang áp dụng những chỉnh sửa cho Roblox...
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] Begin font check
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] End font check
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\CustomFont.ttf already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\TwemojiMozilla.ttf already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\AccanthisADFStd.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\AmaticSC.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Arimo.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Balthazar.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Bangers.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\BuilderSans.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\ComicNeueAngular.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Creepster.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\DenkOne.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Fondamento.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\FredokaOne.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\GrenzeGotisch.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Guru.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\HighwayGothic.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Inconsolata.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\IndieFlower.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\JosefinSans.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Jura.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Kalam.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\LegacyArial.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\LegacyArimo.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\LuckiestGuy.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Merriweather.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Michroma.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Montserrat.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Nunito.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Oswald.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\PatrickHand.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\PermanentMarker.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\PressStart2P.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Roboto.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\RobotoCondensed.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\RobotoMono.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\RomanAntique.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Sarpanch.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\SourceSansPro.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\SpecialElite.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\TitilliumWeb.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Ubuntu.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Zekton.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [JsonManager<State>::Save] Saving to D:\Release\Bloxstrap\State.json...
2024-12-05T23:59:46Z [JsonManager<State>::Save] Save complete!
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-12-05T23:59:46Z [Bootstrapper::SetStatus] Đang khởi động {product}...
2024-12-05T23:59:46Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-05T23:59:46Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-05T23:59:46Z [App::FinalizeExceptionHandling] (0x80070003) System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Roblox\logs'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-05T23:59:47Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception

### Bloxstrap Log

```text
2024-12-05T23:59:44Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-05T23:59:44Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 5:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-05T23:59:44Z [App::OnStartup] Loaded from D:\Release\Bloxstrap\Bloxstrap.exe
2024-12-05T23:59:44Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-05T23:59:44Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-05T23:59:44Z [Logger::Initialize] Initializing at D:\Release\Bloxstrap\Logs\Bloxstrap_20241205T235944Z.log
2024-12-05T23:59:44Z [Logger::Initialize] Finished initializing!
2024-12-05T23:59:44Z [JsonManager<Settings>::Load] Loading from D:\Release\Bloxstrap\Settings.json...
2024-12-05T23:59:44Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-05T23:59:44Z [JsonManager<State>::Load] Loading from D:\Release\Bloxstrap\State.json...
2024-12-05T23:59:44Z [JsonManager<State>::Load] Loaded successfully!
2024-12-05T23:59:44Z [FastFlagManager::Load] Loading from D:\Release\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-05T23:59:44Z [FastFlagManager::Load] Loaded successfully!
2024-12-05T23:59:46Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-05T23:59:46Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-05T23:59:46Z [Bootstrapper::Run] Running bootstrapper
2024-12-05T23:59:46Z [Bootstrapper::SetStatus] Đang kết nối đến Roblox...
2024-12-05T23:59:46Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-05T23:59:46Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-05T23:59:46Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-05T23:59:46Z [Bootstrapper::Run] Connectivity check finished
2024-12-05T23:59:46Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-05T23:59:46Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-05T23:59:46Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-05T23:59:46Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-05T23:59:46Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-05T23:59:46Z [Bootstrapper::SetStatus] Đang áp dụng những chỉnh sửa cho Roblox...
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] Begin font check
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] End font check
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\CustomFont.ttf already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\TwemojiMozilla.ttf already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\AccanthisADFStd.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\AmaticSC.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Arimo.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Balthazar.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Bangers.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\BuilderSans.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\ComicNeueAngular.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Creepster.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\DenkOne.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Fondamento.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\FredokaOne.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\GrenzeGotisch.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Guru.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\HighwayGothic.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Inconsolata.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\IndieFlower.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\JosefinSans.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Jura.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Kalam.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\LegacyArial.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\LegacyArimo.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\LuckiestGuy.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Merriweather.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Michroma.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Montserrat.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Nunito.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Oswald.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\PatrickHand.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\PermanentMarker.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\PressStart2P.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Roboto.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\RobotoCondensed.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\RobotoMono.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\RomanAntique.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Sarpanch.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\SourceSansPro.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\SpecialElite.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\TitilliumWeb.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Ubuntu.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] content\fonts\families\Zekton.json already exists in the version folder, and is a match
2024-12-05T23:59:46Z [JsonManager<State>::Save] Saving to D:\Release\Bloxstrap\State.json...
2024-12-05T23:59:46Z [JsonManager<State>::Save] Save complete!
2024-12-05T23:59:46Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-12-05T23:59:46Z [Bootstrapper::SetStatus] Đang khởi động {product}...
2024-12-05T23:59:46Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-05T23:59:46Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-05T23:59:46Z [App::FinalizeExceptionHandling] (0x80070003) System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Roblox\logs'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-05T23:59:46Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-05T23:59:47Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
Duplicate issues. Will be fixed next update.
