### ISSUE TITLE
[BUG] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)  [Inner Exception] System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary. while installing old bloxstrap

### ISSUE THREAD

**Issue by surjoturjo** [bloxstraplabs/bloxstrap#3932]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.5.4

### What problem did you encounter?

since the 21 graphic bar
 has been removed i wanted to try old bloxstrap but i wouldnt install it because this error

![image](https://github.com/user-attachments/assets/4c2f0a19-ae8c-42df-a85b-c01dd796934b)

### Bloxstrap Log

```text
2024-12-07T10:37:23Z [App::OnStartup] Starting Bloxstrap v2.5.4
2024-12-07T10:37:23Z [App::OnStartup] Compiled Saturday, 4 November 2023 at 3:46:02 AM from commit 880c076fcd875fc10b5f6bef770033074d79a7a8 (tag/v2.5.4)
2024-12-07T10:37:23Z [App::OnStartup] Loaded from %UserProfile%\OneDrive\Desktop\Bloxstrap-v2.5.4.exe
2024-12-07T10:37:23Z [InstallChecker::FirstTimeRun] Running first-time install
2024-12-07T10:37:23Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap_20241207T103723Z.log
2024-12-07T10:37:23Z [Logger::Initialize] Finished initializing!
2024-12-07T10:37:23Z [JsonManager<Dictionary`2>::Load] Loading from ClientSettings\ClientAppSettings.json...
2024-12-07T10:37:23Z [JsonManager<Dictionary`2>::Load] Failed to load!
2024-12-07T10:37:23Z [JsonManager<Dictionary`2>::Load] Could not find a part of the path '%UserProfile%\OneDrive\Desktop\ClientSettings\ClientAppSettings.json'.
2024-12-07T10:37:23Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-12-07T10:37:23Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-12-07T10:37:23Z [FastFlagManager::SetValue] Setting of 'DFIntTaskSchedulerTargetFps' to '120' is pending
2024-12-07T10:37:23Z [MainWindow::MainWindow] Initializing menu
2024-12-07T10:37:28Z [FastFlagManager::SetValue] Setting of 'FFlagFixGraphicsQuality' to 'True' is pending
2024-12-07T10:37:33Z [NotifyIconWrapper::NotifyIconWrapper] Initializing notification area icon
2024-12-07T10:37:33Z [App::OnStartup] Initializing bootstrapper
2024-12-07T10:37:33Z [App::OnStartup] Initializing bootstrapper dialog
2024-12-07T10:37:33Z [Bootstrapper::Run] Running bootstrapper
2024-12-07T10:37:33Z [Bootstrapper::Run] Performing connectivity check...
2024-12-07T10:37:33Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-07T10:37:33Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-12-07T10:37:33Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-12-07T10:37:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/LIVE
2024-12-07T10:37:34Z [Bootstrapper::Run] Connectivity check finished
2024-12-07T10:37:34Z [RobloxDeployment::GetInfo] Getting deploy info for channel LIVE (extraInformation=False)
2024-12-07T10:37:34Z [RobloxDeployment::GetInfo] Deploy information is cached
2024-12-07T10:37:34Z [DeployManager::DefaultBaseUrl.Set] Testing connection to 'https://setup.rbxcdn.com'...
2024-12-07T10:37:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version
2024-12-07T10:37:35Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version
2024-12-07T10:37:35Z [DeployManager::DefaultBaseUrl.Set] Connection successful!
2024-12-07T10:37:35Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-07T10:37:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-07T10:37:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxManifest.txt
2024-12-07T10:37:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxManifest.txt
2024-12-07T10:37:36Z [Bootstrapper::SetStatus] Installing Roblox...
2024-12-07T10:37:36Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-12-07T10:37:36Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-RobloxApp.zip
2024-12-07T10:37:36Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-RobloxApp.zip
2024-12-07T10:38:22Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (88797938 bytes total)
2024-12-07T10:38:22Z [Bootstrapper::ExtractPackage] Reading RobloxApp.zip...
2024-12-07T10:38:22Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-12-07T10:38:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-avatar.zip
2024-12-07T10:38:22Z [Bootstrapper::ExtractPackage] Read RobloxApp.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1...
2024-12-07T10:38:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-avatar.zip
2024-12-07T10:38:22Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (516549 bytes total)
2024-12-07T10:38:22Z [Bootstrapper::ExtractPackage] Reading content-avatar.zip...
2024-12-07T10:38:22Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-12-07T10:38:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-configs.zip
2024-12-07T10:38:22Z [Bootstrapper::ExtractPackage] Read content-avatar.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\content\avatar\...
2024-12-07T10:38:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-configs.zip
2024-12-07T10:38:22Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-07T10:38:22Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (261963 bytes total)
2024-12-07T10:38:22Z [Bootstrapper::ExtractPackage] Reading content-configs.zip...
2024-12-07T10:38:22Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-12-07T10:38:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-fonts.zip
2024-12-07T10:38:23Z [Bootstrapper::ExtractPackage] Read content-configs.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\content\configs\...
2024-12-07T10:38:23Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-07T10:38:23Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-07T10:38:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-fonts.zip
2024-12-07T10:38:26Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-12-07T10:38:26Z [Bootstrapper::ExtractPackage] Reading content-fonts.zip...
2024-12-07T10:38:26Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-12-07T10:38:26Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-models.zip
2024-12-07T10:38:26Z [Bootstrapper::ExtractPackage] Read content-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\content\fonts\...
2024-12-07T10:38:26Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-12-07T10:38:26Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-models.zip
2024-12-07T10:38:26Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (491904 bytes total)
2024-12-07T10:38:26Z [Bootstrapper::ExtractPackage] Reading content-models.zip...
2024-12-07T10:38:26Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-12-07T10:38:26Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-sky.zip
2024-12-07T10:38:26Z [Bootstrapper::ExtractPackage] Read content-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\content\models\...
2024-12-07T10:38:27Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-07T10:38:27Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-sky.zip
2024-12-07T10:38:28Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-12-07T10:38:28Z [Bootstrapper::ExtractPackage] Reading content-sky.zip...
2024-12-07T10:38:28Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-12-07T10:38:28Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-sounds.zip
2024-12-07T10:38:28Z [Bootstrapper::ExtractPackage] Read content-sky.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\content\sky\...
2024-12-07T10:38:28Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-07T10:38:29Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-sounds.zip
2024-12-07T10:38:29Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (597244 bytes total)
2024-12-07T10:38:29Z [Bootstrapper::ExtractPackage] Reading content-sounds.zip...
2024-12-07T10:38:29Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-12-07T10:38:29Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-shaders.zip
2024-12-07T10:38:29Z [Bootstrapper::ExtractPackage] Read content-sounds.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\content\sounds\...
2024-12-07T10:38:29Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-07T10:38:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-shaders.zip
2024-12-07T10:38:34Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (8449913 bytes total)
2024-12-07T10:38:34Z [Bootstrapper::ExtractPackage] Reading shaders.zip...
2024-12-07T10:38:34Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-12-07T10:38:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-ssl.zip
2024-12-07T10:38:34Z [Bootstrapper::ExtractPackage] Read shaders.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\shaders\...
2024-12-07T10:38:34Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-07T10:38:35Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-ssl.zip
2024-12-07T10:38:35Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (135951 bytes total)
2024-12-07T10:38:35Z [Bootstrapper::ExtractPackage] Reading ssl.zip...
2024-12-07T10:38:35Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-12-07T10:38:35Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-textures2.zip
2024-12-07T10:38:35Z [Bootstrapper::ExtractPackage] Read ssl.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\ssl\...
2024-12-07T10:38:35Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-07T10:38:35Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-textures2.zip
2024-12-07T10:38:42Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (13549632 bytes total)
2024-12-07T10:38:42Z [Bootstrapper::ExtractPackage] Reading content-textures2.zip...
2024-12-07T10:38:42Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-12-07T10:38:42Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-textures3.zip
2024-12-07T10:38:42Z [Bootstrapper::ExtractPackage] Read content-textures2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\content\textures\...
2024-12-07T10:38:42Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-textures3.zip
2024-12-07T10:38:44Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-12-07T10:38:44Z [Bootstrapper::ExtractPackage] Reading content-textures3.zip...
2024-12-07T10:38:44Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-12-07T10:38:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-terrain.zip
2024-12-07T10:38:44Z [Bootstrapper::ExtractPackage] Read content-textures3.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\PlatformContent\pc\textures\...
2024-12-07T10:38:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-terrain.zip
2024-12-07T10:38:45Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-12-07T10:38:45Z [Bootstrapper::ExtractPackage] Reading content-terrain.zip...
2024-12-07T10:38:45Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-12-07T10:38:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-platform-fonts.zip
2024-12-07T10:38:45Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-platform-fonts.zip
2024-12-07T10:38:45Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-07T10:38:45Z [Bootstrapper::ExtractPackage] Read content-terrain.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\PlatformContent\pc\terrain\...
2024-12-07T10:38:45Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-07T10:38:51Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-12-07T10:38:51Z [Bootstrapper::ExtractPackage] Reading content-platform-fonts.zip...
2024-12-07T10:38:51Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Downloading...
2024-12-07T10:38:51Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-platform-dictionaries.zip
2024-12-07T10:38:51Z [Bootstrapper::ExtractPackage] Read content-platform-fonts.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\PlatformContent\pc\fonts\...
2024-12-07T10:38:52Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-12-07T10:38:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-content-platform-dictionaries.zip
2024-12-07T10:38:52Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Finished downloading! (152263 bytes total)
2024-12-07T10:38:52Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-12-07T10:38:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-extracontent-places.zip
2024-12-07T10:38:52Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting content-platform-dictionaries.zip'
2024-12-07T10:38:52Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'content-platform-dictionaries.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'content-platform-dictionaries.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-12-07T10:38:52Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-extracontent-places.zip
2024-12-07T10:38:53Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1510546 bytes total)
2024-12-07T10:38:53Z [Bootstrapper::ExtractPackage] Reading extracontent-places.zip...
2024-12-07T10:38:53Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-12-07T10:38:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-extracontent-luapackages.zip
2024-12-07T10:38:53Z [Bootstrapper::ExtractPackage] Read extracontent-places.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\ExtraContent\places\...
2024-12-07T10:38:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-extracontent-luapackages.zip
2024-12-07T10:38:53Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-07T10:38:56Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-07T10:38:56Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (6622887 bytes total)
2024-12-07T10:38:56Z [Bootstrapper::ExtractPackage] Reading extracontent-luapackages.zip...
2024-12-07T10:38:56Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-12-07T10:38:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-extracontent-translations.zip
2024-12-07T10:38:56Z [Bootstrapper::ExtractPackage] Read extracontent-luapackages.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\ExtraContent\LuaPackages\...
2024-12-07T10:38:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-extracontent-translations.zip
2024-12-07T10:38:56Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-07T10:38:56Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (484131 bytes total)
2024-12-07T10:38:56Z [Bootstrapper::ExtractPackage] Reading extracontent-translations.zip...
2024-12-07T10:38:56Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-12-07T10:38:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-extracontent-models.zip
2024-12-07T10:38:56Z [Bootstrapper::ExtractPackage] Read extracontent-translations.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\ExtraContent\translations\...
2024-12-07T10:38:56Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-07T10:38:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-extracontent-models.zip
2024-12-07T10:39:02Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (10469290 bytes total)
2024-12-07T10:39:02Z [Bootstrapper::ExtractPackage] Reading extracontent-models.zip...
2024-12-07T10:39:02Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-12-07T10:39:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-extracontent-textures.zip
2024-12-07T10:39:02Z [Bootstrapper::ExtractPackage] Read extracontent-models.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\ExtraContent\models\...
2024-12-07T10:39:02Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-07T10:39:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-extracontent-textures.zip
2024-12-07T10:39:11Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (17130170 bytes total)
2024-12-07T10:39:11Z [Bootstrapper::ExtractPackage] Reading extracontent-textures.zip...
2024-12-07T10:39:11Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-12-07T10:39:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-WebView2.zip
2024-12-07T10:39:11Z [Bootstrapper::ExtractPackage] Read extracontent-textures.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1\ExtraContent\textures\...
2024-12-07T10:39:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-WebView2.zip
2024-12-07T10:39:11Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-12-07T10:39:11Z [Bootstrapper::ExtractPackage] Reading WebView2.zip...
2024-12-07T10:39:11Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-12-07T10:39:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-WebView2RuntimeInstaller.zip
2024-12-07T10:39:12Z [Bootstrapper::ExtractPackage] Read WebView2.zip. Extracting to %UserProfile%\AppData\Local\Bloxstrap\Versions\version-a2fb906f52d742c1...
2024-12-07T10:39:12Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-12-07T10:39:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-WebView2RuntimeInstaller.zip
2024-12-07T10:39:13Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-12-07T10:39:13Z [Bootstrapper::DownloadPackage.redist.zip] Downloading...
2024-12-07T10:39:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-redist.zip
2024-12-07T10:39:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-redist.zip
2024-12-07T10:39:14Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-07T10:39:14Z [Bootstrapper::DownloadPackage.redist.zip] Finished downloading! (1372275 bytes total)
2024-12-07T10:39:14Z [AsyncHelpers::ExceptionHandler] An exception occurred while running the task 'extracting redist.zip'
2024-12-07T10:39:14Z [App::FinalizeExceptionHandling] System.AggregateException: One or more errors occurred. (The given key 'redist.zip' was not present in the dictionary.)
 ---> System.Collections.Generic.KeyNotFoundException: The given key 'redist.zip' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package)
   --- End of inner exception stack trace ---
2024-12-07T10:39:15Z [Bootstrapper::SetStatus] Configuring Roblox...
2024-12-07T10:45:10Z [App::Terminate] Terminating with exit code 1603 (ERROR_INSTALL_FAILURE)
2024-12-07T10:45:10Z [JsonManager<Settings>::Save] Save request ignored
2024-12-07T10:45:10Z [JsonManager<State>::Save] Save request ignored
2024-12-07T10:45:10Z [NotifyIconWrapper::Dispose] Disposing NotifyIcon
```

**Comment by nabheyka880** [comment]
update
https://bloxstraplabs.com/

**Comment by surjoturjo** [comment]
i dont want to lose the graphic bar feature

**Comment by nabheyka880** [comment]
it doesn't even work anymore
and that's too bad

**Comment by surjoturjo** [comment]
bruh i hate this i lag now i hate my crusty dusty ahh pc

**Comment by bluepilledgreat** [comment]
Update Bloxstrap.

**Comment by surjoturjo** [comment]
no i dont want to

**Comment by GoingCrazyDude** [comment]
> no i dont want to

then it wont work
