### ISSUE TITLE
[BUG] Exception

### ISSUE THREAD

**Issue by ATCS1** [bloxstraplabs/bloxstrap#3934]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/2c6e142c-f407-413c-8686-9379f1841a30)

System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Admin\AppData\Local\Bloxstrap\Roblox\Player\content\fonts\families'.

### Bloxstrap Log

```text
2024-12-07T12:38:11Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-07T12:38:11Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 1:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-07T12:38:11Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-07T12:38:11Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-07T12:38:11Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-07T12:38:11Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241207T123811Z.log
2024-12-07T12:38:11Z [Logger::Initialize] Finished initializing!
2024-12-07T12:38:11Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-07T12:38:11Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-07T12:38:11Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-07T12:38:11Z [JsonManager<State>::Load] Loaded successfully!
2024-12-07T12:38:11Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-07T12:38:11Z [FastFlagManager::Load] Loaded successfully!
2024-12-07T12:38:12Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-07T12:38:12Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-07T12:38:12Z [Bootstrapper::Run] Running bootstrapper
2024-12-07T12:38:12Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-07T12:38:12Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-07T12:38:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-07T12:38:12Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-07T12:38:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-07T12:38:12Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-07T12:38:12Z [Bootstrapper::Run] Connectivity check finished
2024-12-07T12:38:12Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-07T12:38:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-07T12:38:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-07T12:38:13Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-07T12:38:13Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-07T12:38:13Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-07T12:38:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-07T12:38:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-07T12:38:13Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-07T12:38:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-07T12:38:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-07T12:38:13Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-12-07T12:38:13Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-12-07T12:38:13Z [Bootstrapper::ApplyModifications] Begin font check
2024-12-07T12:38:13Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-07T12:38:13Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-07T12:38:13Z [App::FinalizeExceptionHandling] (0x80070003) System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Bloxstrap\Roblox\Player\content\fonts\families'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
   at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.Directory.GetFiles(String path)
   at Bloxstrap.Bootstrapper.ApplyModifications()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-07T12:38:13Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-07T12:38:13Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
```

**Comment by ATCS1** [comment]
What do i do to fix this?

**Comment by ATCS1** [comment]
Note: It works after i remove the font, I Will try other fonts and see if i get the same problem.

**Comment by ATCS1** [comment]
no font  works it js gives the same issue

**Comment by Dimas091233222** [comment]
bruhhh
