### ISSUE TITLE
[BUG] System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by bluesockpocket** [bloxstraplabs/bloxstrap#3944]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

no, this is not a duplicate
i have gotten this error and have not found a _single_ solution throughtout either the closed bug reports or the wiki
this happens everytime i open bloxstrap , even after deleting and reinstalling
i have no idea what this means or how to fix it
i have already tried the desktop runtime thingamajig , didnt work either

### Bloxstrap Log

```text
N/A2024-12-08T02:34:12Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-08T02:34:12Z [App::OnStartup] Compiled Thursday, 31 October 2024 at 4:04:10 PM from commit 811972d1f56bb517d42bbe32e1ea7394d87f0ee8 (branch/main)
2024-12-08T02:34:12Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Temp\scoped_dir6204_1789817686\Bloxstrap.exe
2024-12-08T02:34:12Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-08T02:34:12Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-08T02:34:12Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241208T023412Z.log
2024-12-08T02:34:12Z [Logger::Initialize] Finished initializing!
2024-12-08T02:34:12Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-08T02:34:12Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-08T02:34:12Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-08T02:34:12Z [JsonManager<State>::Load] Loaded successfully!
2024-12-08T02:34:12Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-08T02:34:12Z [FastFlagManager::Load] Loaded successfully!
2024-12-08T02:34:12Z [FastFlagManager::SetValue] Changing of 'FFlagUserIsBloxstrap' from 'True' to 'True' is pending
2024-12-08T02:34:12Z [FastFlagManager::SetValue] Changing of 'FFlagUserAllowsWindowMovement' from 'True' to 'True' is pending
2024-12-08T02:34:12Z [Utilities::CompareVersions] An exception occurred when comparing versions
2024-12-08T02:34:12Z [Utilities::CompareVersions] versionStr1=2.8.1 versionStr2=2.6.0+1a46e642d51734ed28cd4b2562841349d89e4199
2024-12-08T02:34:12Z [App::GlobalExceptionHandler] An exception occurred
2024-12-08T02:34:12Z [App::FinalizeExceptionHandling] (0x80131537) System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Version.TryParseComponent(ReadOnlySpan`1 component, String componentName, Boolean throwOnFailure, Int32& parsedComponent)
   at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Bloxstrap.Utilities.CompareVersions(String versionStr1, String versionStr2)
   at Bloxstrap.Installer.HandleUpgrade()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by bluesockpocket** [comment]
how do i fix this?
