### ISSUE TITLE
[BUG] System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Killa\AppData\Local\Roblox\logs'.

### ISSUE THREAD

**Issue by MrShapi** [bloxstraplabs/bloxstrap#3949]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

firstly, my roblox file itself does not open when I want to download it and I decided to try through bloxtrap but it didn’t help either. Initially I wanted to transfer roblox from drive C to drive D via the command line with the command mklink /D "C:\Users \User\AppData\Local\Roblox" "D:\Games\Roblox"
it helped, I was able to transfer it, but I suddenly changed my mind and wanted to transfer it back to drive C through a complete reinstallation, but Roblox no longer wanted to download

### Bloxstrap Log

```text
2024-12-09T03:47:23Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-09T03:47:23Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 5:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-09T03:47:23Z [App::OnStartup] Loaded from D:\Games\Bloxstrap\Bloxstrap.exe
2024-12-09T03:47:23Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-09T03:47:23Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-09T03:47:23Z [Logger::Initialize] Initializing at D:\Games\Bloxstrap\Logs\Bloxstrap_20241209T034723Z.log
2024-12-09T03:47:23Z [Logger::Initialize] Finished initializing!
2024-12-09T03:47:23Z [JsonManager<Settings>::Load] Loading from D:\Games\Bloxstrap\Settings.json...
2024-12-09T03:47:23Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-09T03:47:23Z [JsonManager<State>::Load] Loading from D:\Games\Bloxstrap\State.json...
2024-12-09T03:47:23Z [JsonManager<State>::Load] Loaded successfully!
2024-12-09T03:47:23Z [FastFlagManager::Load] Loading from D:\Games\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-09T03:47:23Z [FastFlagManager::Load] Loaded successfully!
2024-12-09T03:47:23Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-12-09T03:47:23Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-12-09T03:47:24Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-09T03:47:24Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-09T03:47:24Z [Bootstrapper::Run] Running bootstrapper
2024-12-09T03:47:24Z [Bootstrapper::SetStatus] Подключение к Roblox...
2024-12-09T03:47:24Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-09T03:47:24Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-09T03:47:25Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-09T03:47:25Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-09T03:47:25Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-09T03:47:25Z [Bootstrapper::Run] Connectivity check finished
2024-12-09T03:47:25Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-09T03:47:25Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-09T03:47:25Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-09T03:47:25Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-09T03:47:25Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-09T03:47:25Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-09T03:47:25Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-09T03:47:26Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-09T03:47:26Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-09T03:47:26Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-09T03:47:26Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-a2fb906f52d742c1-rbxPkgManifest.txt
2024-12-09T03:47:26Z [Bootstrapper::SetStatus] Применяем модификации Roblox...
2024-12-09T03:47:26Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-12-09T03:47:26Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json already exists in the version folder, and is a match
2024-12-09T03:47:26Z [JsonManager<State>::Save] Saving to D:\Games\Bloxstrap\State.json...
2024-12-09T03:47:26Z [JsonManager<State>::Save] Save complete!
2024-12-09T03:47:26Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-12-09T03:47:26Z [Bootstrapper::SetStatus] Запускаем {product}...
2024-12-09T03:47:26Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-09T03:47:26Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-09T03:47:26Z [App::FinalizeExceptionHandling] (0x80070003) System.IO.DirectoryNotFoundException: Could not find a part of the path '%UserProfile%\AppData\Local\Roblox\logs'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Bootstrapper.StartRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-09T03:47:26Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
Duplicate issue. Will be fixed in a future update.
