### ISSUE TITLE
[BUG] System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by redblueofficer** [bloxstraplabs/bloxstrap#3963]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

ver 2.8.1

### What problem did you encounter?

Wtf happened? I just tried to join my game and it slapped me with this straight in the face.

### Bloxstrap Log

```text
2024-12-10T22:18:52Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-10T22:18:52Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 10:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-10T22:18:52Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-10T22:18:52Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-10T22:18:52Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-10T22:18:52Z [LaunchSettings] Identifier 'player' is active with data
2024-12-10T22:18:52Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241210T221852Z.log
2024-12-10T22:18:52Z [Logger::Initialize] Finished initializing!
2024-12-10T22:18:52Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-10T22:18:52Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-10T22:18:52Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-10T22:18:52Z [JsonManager<State>::Load] Loaded successfully!
2024-12-10T22:18:52Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-10T22:18:52Z [FastFlagManager::Load] Loaded successfully!
2024-12-10T22:18:52Z [Frontend::ShowMessageBox] Roblox is currently running, and launching another instance will close it. Are you sure you want to continue launching?
2024-12-10T22:18:54Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-10T22:18:54Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-10T22:18:55Z [Bootstrapper::Run] Running bootstrapper
2024-12-10T22:18:55Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-10T22:18:55Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-10T22:18:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-10T22:18:55Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-10T22:18:55Z [App::GlobalExceptionHandler] An exception occurred
2024-12-10T22:18:55Z [App::FinalizeExceptionHandling] (0x80004001) System.NotImplementedException: The method or operation is not implemented.
   at MS.Internal.AppModel.ITaskbarList.HrInit()
   at System.Windows.Window.ApplyTaskbarItemInfo()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-12-10T22:18:55Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
What operating system are you using?

**Comment by redblueofficer** [comment]
Microsoft Windows 10. The error has been fixed now however, but it has
happened before too.

**Comment by Highseepkuq** [comment]
how did you fix it?it pops up for me too

**Comment by bluepilledgreat** [comment]
Duplicate of #3741
