### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'face.png' is denied.

### ISSUE THREAD

**Issue by drippedoutbeana** [bloxstraplabs/bloxstrap#3976]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

[BUG] System.UnauthorizedAccessException: Access to the path 'face.png' is denied.

I change the textures to make players head the color red

### Bloxstrap Log

```text
2024-12-11T23:17:02Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-11T23:17:02Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 5:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-11T23:17:02Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-11T23:17:02Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-11T23:17:02Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-11T23:17:02Z [LaunchSettings] Identifier 'player' is active
2024-12-11T23:17:02Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241211T231702Z.log
2024-12-11T23:17:02Z [Logger::Initialize] Finished initializing!
2024-12-11T23:17:02Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-11T23:17:02Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-11T23:17:02Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-11T23:17:02Z [JsonManager<State>::Load] Loaded successfully!
2024-12-11T23:17:02Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-11T23:17:02Z [FastFlagManager::Load] Loaded successfully!
2024-12-11T23:17:02Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-11T23:17:02Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-11T23:17:03Z [Bootstrapper::Run] Running bootstrapper
2024-12-11T23:17:03Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-11T23:17:03Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-11T23:17:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-11T23:17:03Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-11T23:17:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-11T23:17:03Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-11T23:17:03Z [Bootstrapper::Run] Connectivity check finished
2024-12-11T23:17:03Z [Bootstrapper::CheckForUpdates] More than one Bloxstrap instance running, aborting update check
2024-12-11T23:17:03Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-11T23:17:03Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-11T23:17:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-11T23:17:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-11T23:17:03Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-11T23:17:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-11T23:17:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-11T23:17:03Z [Bootstrapper::SetStatus] Upgrading {product}...
2024-12-11T23:17:03Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-11T23:17:03Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-11T23:17:03Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'face.png' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-11T23:17:03Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-11T23:17:03Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
```

**Comment by toast-ed** [comment]
first of all changing the face.png only applies to people that doesnt have any faces and uses the default second at all why. just fucking force reinstall roblox
