### ISSUE TITLE
[BUG] System.IO.IOException: The file or directory is corrupted and unreadable. : 'Favorite.png'

### ISSUE THREAD

**Issue by defnotlsplash** [bloxstraplabs/bloxstrap#4009]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Whenever i try to launch Roblox through Bloxstrap. Anytime it would try to load. It will crash and gives me the "System.IO.IOException: The file or directory is corrupted and unreadable. : 'Favorite.png'" Error and eventually close out. I tried to reinstall it. Worked once and then the issue comes back.

Screenshot of the Error:
![Screenshot 2024-12-15 203838](https://github.com/user-attachments/assets/f9e30ee0-e779-4af5-b7e3-50b125d7975d)

### Bloxstrap Log

```text
2024-12-15T17:32:18Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-15T17:32:18Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 1:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-15T17:32:18Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-15T17:32:18Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-15T17:32:18Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-15T17:32:18Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241215T173218Z.log
2024-12-15T17:32:18Z [Logger::Initialize] Finished initializing!
2024-12-15T17:32:18Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-15T17:32:18Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-15T17:32:18Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-15T17:32:18Z [JsonManager<State>::Load] Loaded successfully!
2024-12-15T17:32:18Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-15T17:32:18Z [FastFlagManager::Load] Loaded successfully!
2024-12-15T17:32:19Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-15T17:32:19Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-15T17:32:19Z [Bootstrapper::Run] Running bootstrapper
2024-12-15T17:32:19Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-15T17:32:19Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-15T17:32:19Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-15T17:32:20Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-15T17:32:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-15T17:32:21Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-15T17:32:21Z [Bootstrapper::Run] Connectivity check finished
2024-12-15T17:32:21Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-15T17:32:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-15T17:32:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-15T17:32:22Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-15T17:32:22Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-15T17:32:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zflag
2024-12-15T17:32:22Z [Deployment::GetInfo] Getting deploy info for channel zflag
2024-12-15T17:32:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zflag
2024-12-15T17:32:22Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zflag
2024-12-15T17:32:22Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zflag
2024-12-15T17:32:22Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-15T17:32:22Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-15T17:32:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-15T17:32:23Z [RegistryKeyEx::SetValueSafe] Writing 'zflag' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-15T17:32:23Z [ApplicationSettings::Fetch.PCClientBootstrapper.zflag] Fetching fast flags
2024-12-15T17:32:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zflag
2024-12-15T17:32:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zflag
2024-12-15T17:32:23Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-15T17:32:23Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-15T17:32:23Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-15T17:32:23Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-15T17:32:23Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-15T17:32:23Z [App::FinalizeExceptionHandling] (0x80070570) System.IO.IOException: The file or directory is corrupted and unreadable. : 'Favorite.png'
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-15T17:32:23Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by defnotlsplash** [comment]
UPDATE as of December 16: I reinstalled the bootstrapper to the D drive and now it works. Another problem im facing is i'm unable to delete the install folder due to it being corrupted. But i will close this for now
