### ISSUE TITLE
[BUG] An Exception Occured While Running Bloxstrap

### ISSUE THREAD

**Issue by alvinisthatguy** [bloxstraplabs/bloxstrap#4028]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

An exception occured while running bloxstrap

System.UnauthorizedAccessException: Access to the path 'C:\Program Files\KMSpico\temp\Bloxstrap\Logs' is denied.

### Bloxstrap Log

```text
2024-12-18T12:06:28Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-18T12:06:28Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 12:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-18T12:06:28Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.1 (1).exe
2024-12-18T12:06:28Z [App::OnStartup] Temp path is C:\Program Files\KMSpico\temp\Bloxstrap
2024-12-18T12:06:28Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-18T12:06:28Z [Logger::Initialize] Initializing at C:\Program Files\KMSpico\temp\Bloxstrap\Logs\Bloxstrap_20241218T120628Z.log
2024-12-18T12:06:28Z [App::GlobalExceptionHandler] An exception occurred
2024-12-18T12:06:29Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'C:\Program Files\KMSpico\temp\Bloxstrap\Logs' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-12-18T12:06:29Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-18T12:06:30Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
```

**Comment by alvinisthatguy** [comment]
it was not working to download .NET then i ran it as a administrator then it worked then I entered bloxstrap then it said the the above issue

**Comment by whyd0ineedausername** [comment]
why did you download bloxstrap in the kmspico folder
