### ISSUE TITLE
[BUG] System.Runtime.InteropServices.COMException: {Desktop composition is disabled} The operation could not be completed because desktop composition is disabled. (0x80263001)

### ISSUE THREAD

**Issue by MaouStudent** [bloxstraplabs/bloxstrap#4030]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Help me

### Bloxstrap Log

```text
2024-12-18T17:30:07Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-18T17:30:07Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 5:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-18T17:30:07Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Programs\Bloxstrap-v2.8.1.exe
2024-12-18T17:30:07Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-18T17:30:07Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-18T17:30:07Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap\Logs\Bloxstrap_20241218T173007Z.log
2024-12-18T17:30:07Z [Logger::Initialize] Finished initializing!
2024-12-18T17:30:12Z [App::GlobalExceptionHandler] An exception occurred
2024-12-18T17:30:12Z [App::FinalizeExceptionHandling] (0x80263001) System.Runtime.InteropServices.COMException (0x80263001): {Desktop composition is disabled} The operation could not be completed because desktop composition is disabled. (0x80263001)
   at Standard.NativeMethods.DwmExtendFrameIntoClientArea(IntPtr hwnd, MARGINS& pMarInset)
   at System.Windows.Shell.WindowChromeWorker._ExtendGlassFrame()
   at System.Windows.Shell.WindowChromeWorker._UpdateFrameState(Boolean force)
   at System.Windows.Shell.WindowChromeWorker._ApplyNewCustomChrome()
   at System.Windows.Shell.WindowChromeWorker._WindowSourceInitialized(Object sender, EventArgs e)
   at System.Windows.Window.OnSourceInitialized(EventArgs e)
   at Wpf.Ui.Controls.UiWindow.OnSourceInitialized(EventArgs e)
   at Bloxstrap.UI.Elements.Base.WpfUiWindow.OnSourceInitialized(EventArgs e)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.CreateSourceWindowDuringShow()
   at System.Windows.Window.SafeCreateWindowDuringShow()
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Bloxstrap.LaunchHandler.LaunchInstaller()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-12-18T17:30:12Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
what os are you on
