### ISSUE TITLE
[BUG] System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:80)

### ISSUE THREAD

**Issue by Raafi04** [bloxstraplabs/bloxstrap#4043]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![Screenshot 2024-12-20 175305](https://github.com/user-attachments/assets/264b01db-af9a-48ef-bb70-f554af8bb18f)

### Bloxstrap Log

```text
System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:443)

[Inner Exception]
System.Net.Sockets.SocketException: No such host is known.
```

**Comment by Raafi04** [comment]
2024-12-20T13:59:27Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-20T13:59:27Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 5:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-20T13:59:27Z [App::OnStartup] Loaded from D:\Bloxstrap\Bloxstrap.exe
2024-12-20T13:59:27Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-20T13:59:27Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-20T13:59:27Z [Logger::Initialize] Initializing at D:\Bloxstrap\Logs\Bloxstrap_20241220T135927Z.log
2024-12-20T13:59:27Z [Logger::Initialize] Finished initializing!
2024-12-20T13:59:27Z [JsonManager<Settings>::Load] Loading from D:\Bloxstrap\Settings.json...
2024-12-20T13:59:27Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-20T13:59:27Z [JsonManager<State>::Load] Loading from D:\Bloxstrap\State.json...
2024-12-20T13:59:27Z [JsonManager<State>::Load] Loaded successfully!
2024-12-20T13:59:27Z [FastFlagManager::Load] Loading from D:\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-20T13:59:27Z [FastFlagManager::Load] Loaded successfully!
2024-12-20T13:59:29Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-20T13:59:29Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-20T13:59:30Z [Bootstrapper::Run] Running bootstrapper
2024-12-20T13:59:30Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-20T13:59:30Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-20T13:59:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-20T13:59:30Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-20T13:59:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-20T13:59:30Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-20T13:59:30Z [Bootstrapper::Run] Connectivity check finished
2024-12-20T13:59:30Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-20T13:59:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-20T13:59:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-20T13:59:30Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-20T13:59:30Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-20T13:59:30Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-20T13:59:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-20T13:59:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-20T13:59:31Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-20T13:59:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-20T13:59:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-20T13:59:31Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-20T13:59:31Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-12-20T13:59:31Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-20T13:59:31Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-12-20T13:59:31Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-20T13:59:31Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-12-20T13:59:31Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-20T13:59:31Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-12-20T13:59:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-fonts.zip
2024-12-20T13:59:31Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-20T13:59:31Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-20T13:59:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-fonts.zip
2024-12-20T13:59:32Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-20T13:59:40Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-12-20T13:59:40Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-20T13:59:40Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-12-20T13:59:40Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-models.zip
2024-12-20T13:59:40Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-models.zip
2024-12-20T13:59:40Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-12-20T13:59:40Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (491904 bytes total)
2024-12-20T13:59:40Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-20T13:59:40Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-12-20T13:59:40Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sky.zip
2024-12-20T13:59:40Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-20T13:59:40Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sky.zip
2024-12-20T13:59:43Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-12-20T13:59:43Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-20T13:59:43Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-12-20T13:59:43Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sounds.zip
2024-12-20T13:59:43Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-20T13:59:43Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sounds.zip
2024-12-20T13:59:44Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (597244 bytes total)
2024-12-20T13:59:44Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-20T13:59:44Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-12-20T13:59:44Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-shaders.zip
2024-12-20T13:59:44Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-20T13:59:44Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-shaders.zip
2024-12-20T14:00:02Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (8451732 bytes total)
2024-12-20T14:00:02Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-20T14:00:02Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-12-20T14:00:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-ssl.zip
2024-12-20T14:00:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-ssl.zip
2024-12-20T14:00:02Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-20T14:00:02Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (135951 bytes total)
2024-12-20T14:00:02Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-20T14:00:02Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-12-20T14:00:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures2.zip
2024-12-20T14:00:02Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-20T14:00:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures2.zip
2024-12-20T14:00:24Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (13549632 bytes total)
2024-12-20T14:00:24Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-20T14:00:24Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-12-20T14:00:24Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures3.zip
2024-12-20T14:00:24Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures3.zip
2024-12-20T14:00:25Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-20T14:00:30Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-12-20T14:00:30Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-20T14:00:30Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-12-20T14:00:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-terrain.zip
2024-12-20T14:00:30Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-terrain.zip
2024-12-20T14:00:30Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-12-20T14:00:30Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-20T14:00:30Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-12-20T14:00:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-fonts.zip
2024-12-20T14:00:30Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-20T14:00:31Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-20T14:00:31Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-fonts.zip
2024-12-20T14:01:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] An exception occurred after downloading 11107686 bytes. (1/5)
2024-12-20T14:01:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] (0x80131620) System.IO.IOException: Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..
 ---> System.Net.Sockets.SocketException (10053): An established connection was aborted by the software in your host machine.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.ReadAsync(Memory`1 destination)
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-12-20T14:01:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Retrying download over HTTP...
2024-12-20T14:01:35Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-fonts.zip
2024-12-20T14:01:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] An exception occurred after downloading 0 bytes. (2/5)
2024-12-20T14:01:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] (0x80004005) System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:80)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-12-20T14:01:35Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-fonts.zip
2024-12-20T14:01:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] An exception occurred after downloading 0 bytes. (3/5)
2024-12-20T14:01:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] (0x80004005) System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:80)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-12-20T14:01:35Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-fonts.zip
2024-12-20T14:01:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] An exception occurred after downloading 0 bytes. (4/5)
2024-12-20T14:01:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] (0x80004005) System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:80)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-12-20T14:01:35Z [HttpClientLoggingHandler::ProcessRequest] GET http://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-fonts.zip
2024-12-20T14:01:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] An exception occurred after downloading 0 bytes. (5/5)
2024-12-20T14:01:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] (0x80004005) System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:80)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
2024-12-20T14:01:35Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-20T14:01:35Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-20T14:01:35Z [App::FinalizeExceptionHandling] (0x80004005) System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:80)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Bootstrapper.DownloadPackage(Package package)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-20T14:01:35Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-20T14:01:35Z [App::SendLog] (0x80004005) System.Net.Http.HttpRequestException: No such host is known. (bloxstraplabs.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.App.SendLog()
