### ISSUE TITLE
[BUG] Bloxstrap can't connect to roblox

### ISSUE THREAD

**Issue by jeffbezoson** [bloxstraplabs/bloxstrap#4084]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Whenever i open roblox I get the error of "Bloxstrap can't connect to roblox" and sometimes I don't.

### Bloxstrap Log

```text
2024-12-26T01:59:30Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-26T01:59:30Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 3:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-26T01:59:30Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-26T01:59:30Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-26T01:59:30Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-26T01:59:30Z [LaunchSettings] Identifier 'player' is active with data
2024-12-26T01:59:30Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241226T015930Z.log
2024-12-26T01:59:30Z [Logger::Initialize] Finished initializing!
2024-12-26T01:59:30Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-26T01:59:30Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-26T01:59:30Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-26T01:59:30Z [JsonManager<State>::Load] Loaded successfully!
2024-12-26T01:59:30Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-26T01:59:30Z [FastFlagManager::Load] Loaded successfully!
2024-12-26T01:59:30Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-26T01:59:30Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-26T01:59:30Z [Bootstrapper::Run] Running bootstrapper
2024-12-26T01:59:30Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-26T01:59:30Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-26T01:59:30Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-26T01:59:30Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-26T01:59:30Z [Deployment::TestConnection<https://setup.rbxcdn.com>] (0x80004005) System.Net.Http.HttpRequestException: No such host is known. (setup.rbxcdn.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxInterfaces.Deployment.TestConnection(String url, Int32 priority, CancellationToken token)
2024-12-26T01:59:32Z [Deployment::TestConnection<https://setup-aws.rbxcdn.com>] Connecting...
2024-12-26T01:59:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-aws.rbxcdn.com/versionStudio
2024-12-26T01:59:32Z [Deployment::TestConnection<https://setup-ak.rbxcdn.com>] Connecting...
2024-12-26T01:59:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup-ak.rbxcdn.com/versionStudio
2024-12-26T01:59:32Z [Deployment::TestConnection<https://roblox-setup.cachefly.net>] Connecting...
2024-12-26T01:59:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://roblox-setup.cachefly.net/versionStudio
2024-12-26T01:59:32Z [Deployment::TestConnection<https://setup-ak.rbxcdn.com>] (0x80004005) System.Net.Http.HttpRequestException: No such host is known. (setup-ak.rbxcdn.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.RobloxInterfaces.Deployment.TestConnection(String url, Int32 priority, CancellationToken token)
2024-12-26T01:59:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://roblox-setup.cachefly.net/versionStudio
2024-12-26T01:59:32Z [Deployment::InitializeConnectivity] Got https://roblox-setup.cachefly.net as the optimal base URL
2024-12-26T01:59:32Z [Bootstrapper::Run] Connectivity check finished
2024-12-26T01:59:32Z [Deployment::TestConnection<https://setup-aws.rbxcdn.com>] Connectivity test cancelled.
2024-12-26T01:59:32Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-26T01:59:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-26T01:59:33Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-26T01:59:33Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-26T01:59:33Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-26T01:59:33Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-26T01:59:33Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-26T01:59:33Z [Deployment::GetInfo] Failed to contact clientsettingscdn! Falling back to clientsettings...
2024-12-26T01:59:33Z [Deployment::GetInfo] (0x80004005) System.Net.Http.HttpRequestException: No such host is known. (clientsettingscdn.roblox.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.RobloxInterfaces.Deployment.GetInfo(String channel)
2024-12-26T01:59:33Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettings.roblox.com/v2/client-version/WindowsPlayer
2024-12-26T01:59:33Z [Bootstrapper::HandleConnectionError] Connectivity check failed
2024-12-26T01:59:33Z [Bootstrapper::HandleConnectionError] (0x80004005) System.Net.Http.HttpRequestException: No such host is known. (clientsettings.roblox.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.RobloxInterfaces.Deployment.GetInfo(String channel)
   at Bloxstrap.Bootstrapper.GetLatestVersionInfo()
   at Bloxstrap.Bootstrapper.Run()
2024-12-26T01:59:47Z [Bootstrapper::SetStatus] Starting {product}...
2024-12-26T01:59:47Z [Bootstrapper::StartRoblox] Started Roblox (PID 7164), waiting for log file
2024-12-26T01:59:48Z [Bootstrapper::StartRoblox] Got log file as %UserProfile%\AppData\Local\Roblox\logs\0.654.1.6540477_20241226T015948Z_Player_8E94C_last.log
2024-12-26T01:59:48Z [Bootstrapper::Cancel] Cancelling launch...
2024-12-26T01:59:48Z [App::SoftTerminate] Terminating with exit code 1223 (ERROR_CANCELLED)
```

**Comment by bluepilledgreat** [comment]
fix yo internet
