### ISSUE TITLE
[BUG] System.IO.IOException: The file or directory is corrupted and unreadable. : 'C:\Users\User\AppData\Local\Bloxstrap\Logs' (And its the LATEST version.)

### ISSUE THREAD

**Issue by testingaccoutn** [bloxstraplabs/bloxstrap#4088]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

![BUG](https://github.com/user-attachments/assets/3b0cfe76-702c-49ea-9b53-09e8eb3bd250)

Idk why. But this is not always like this. I wanted to uninstall this, but it just says the same when im uninstalling. 

### Bloxstrap Log

```text
2024-12-26T14:36:20Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-26T14:36:20Z [App::OnStartup] Compiled Wednesday, 30 October 2024 at 5:35:23 AM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-26T14:36:20Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-26T14:36:20Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-26T14:36:20Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-26T14:36:20Z [LaunchSettings] Identifier 'uninstall' is active
2024-12-26T14:36:20Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap\Logs\Bloxstrap_20241226T143620Z.log
2024-12-26T14:36:20Z [Logger::Initialize] Finished initializing!
2024-12-26T14:36:20Z [App::GlobalExceptionHandler] An exception occurred
2024-12-26T14:36:20Z [App::FinalizeExceptionHandling] (0x80070570) System.IO.IOException: The file or directory is corrupted and unreadable. : '%UserProfile%\AppData\Local\Bloxstrap\Logs'
   at System.IO.Enumeration.FileSystemEnumerator`1.FindNextEntry()
   at System.IO.Enumeration.FileSystemEnumerator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.DirectoryInfo.GetFiles(String searchPattern, EnumerationOptions enumerationOptions)
   at System.IO.DirectoryInfo.GetFiles()
   at Bloxstrap.Logger.Initialize(Boolean useTempDir)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-12-26T14:36:20Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
fixed in 2.8.2

**Comment by testingaccoutn** [comment]
![BUG AGAIN](https://github.com/user-attachments/assets/f00ee2ab-99e2-4eb9-9b79-a6a73103cecb)

**Comment by bluepilledgreat** [comment]
nevermind i thought this was a different error.
I have absolutely no idea why thats happening and sounds more like your OS dying
