### ISSUE TITLE
[BUG] Connecting to Roblox

### ISSUE THREAD

**Issue by mrs-figglewatts** [bloxstraplabs/bloxstrap#4089]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Whenever I launch a game off the website, or if I click"Play Roblox" off of Bloxstrap, it'll say "Connecting to Roblox" for a whole minute before loading a game, whenever it only took like a second previously. This started yesterday and I have done multiple reinstallations of Roblox and Bloxstrap.
![ttt](https://github.com/user-attachments/assets/bae162b0-e666-4254-8fab-52dbe58a7c94)

### Bloxstrap Log

```text
2024-12-26T16:07:19Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-26T16:07:19Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 5:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-26T16:07:19Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-26T16:07:19Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-26T16:07:19Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-26T16:07:19Z [LaunchSettings] Identifier 'player' is active with data
2024-12-26T16:07:19Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241226T160719Z.log
2024-12-26T16:07:19Z [Logger::Initialize] Finished initializing!
2024-12-26T16:07:19Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-26T16:07:19Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-26T16:07:19Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-26T16:07:19Z [JsonManager<State>::Load] Loaded successfully!
2024-12-26T16:07:19Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-26T16:07:19Z [FastFlagManager::Load] Loaded successfully!
2024-12-26T16:07:19Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-26T16:07:19Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-26T16:07:19Z [Bootstrapper::Run] Running bootstrapper
2024-12-26T16:07:19Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-26T16:07:19Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-26T16:07:19Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-26T16:07:19Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-26T16:07:19Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-26T16:07:19Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-26T16:07:19Z [Bootstrapper::Run] Connectivity check finished
2024-12-26T16:07:19Z [Bootstrapper::CheckForUpdates] More than one Bloxstrap instance running, aborting update check
2024-12-26T16:07:19Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-26T16:07:19Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-26T16:07:19Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-26T16:07:49Z [Deployment::GetInfo] Failed to contact clientsettingscdn! Falling back to clientsettings...
2024-12-26T16:07:49Z [Deployment::GetInfo] (0x8013153B) System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Bloxstrap.Utility.Http.GetJson[T](String url)
   at Bloxstrap.RobloxInterfaces.Deployment.GetInfo(String channel)
2024-12-26T16:07:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettings.roblox.com/v2/client-version/WindowsPlayer
2024-12-26T16:07:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettings.roblox.com/v2/client-version/WindowsPlayer
2024-12-26T16:07:49Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-26T16:07:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-26T16:07:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-26T16:07:50Z [Bootstrapper::SetStatus] Applying Roblox modifications...
2024-12-26T16:07:50Z [Bootstrapper::ApplyModifications] Checking file mods...
2024-12-26T16:07:50Z [Bootstrapper::ApplyModifications] ClientSettings\ClientAppSettings.json has been copied to the version folder
2024-12-26T16:07:50Z [Bootstrapper::ApplyModifications] content\sounds\ouch.ogg has been copied to the version folder
2024-12-26T16:07:50Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-26T16:07:50Z [JsonManager<State>::Save] Save complete!
2024-12-26T16:07:50Z [Bootstrapper::ApplyModifications] Finished checking file mods
2024-12-26T16:07:50Z [Bootstrapper::SetStatus] Starting {product}...
2024-12-26T16:07:50Z [Bootstrapper::StartRoblox] Started Roblox (PID 32752), waiting for log file
2024-12-26T16:07:51Z [Bootstrapper::StartRoblox] Got log file as %UserProfile%\AppData\Local\Roblox\logs\0.654.1.6540477_20241226T160751Z_Player_AFCE4_last.log
2024-12-26T16:07:52Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-26T16:07:52Z [App::Terminate] Terminating with exit code 0 (ERROR_SUCCESS)
```

**Comment by mrs-figglewatts** [comment]
my internet is fine?

**Comment by orangedareoranges** [comment]
Well it's not a bloxstrap or roblox issue - it's either a firewall or your internet genuinely is not fine

**Comment by mrs-figglewatts** [comment]
how would i fix it if its a firewall issue?

**Comment by AXCWZ** [comment]
Okay, but for real though, everyone always say it's your anti-virus and firewall, but none actually tells you how.
