### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'D:\Bloxtrup\Versions\version-b71c150c7c1f40de\ucrtbase.dll' is denied.

### ISSUE THREAD

**Issue by ImKeepRim** [bloxstraplabs/bloxstrap#4102]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.2

### What problem did you encounter?

Path is denied idk why (I didn't see that in wiki)
![kal](https://github.com/user-attachments/assets/b54784d1-7b84-4391-bb7a-6a7d03153f69)

### Bloxstrap Log

```text
2024-12-26T19:47:30Z [App::OnStartup] Starting Bloxstrap v2.8.2
2024-12-26T19:47:30Z [App::OnStartup] Compiled Thursday, 26 December 2024 at 7:11:09 PM from commit 51ededbf206343245bcd9646871872840a91d369 (tag/v2.8.2)
2024-12-26T19:47:30Z [App::OnStartup] Loaded from D:\Bloxtrup\Bloxstrap.exe
2024-12-26T19:47:30Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-26T19:47:30Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-26T19:47:30Z [Logger::Initialize] Initializing at D:\Bloxtrup\Logs\Bloxstrap_20241226T194730Z.log
2024-12-26T19:47:30Z [Logger::Initialize] Finished initializing!
2024-12-26T19:47:30Z [JsonManager<Settings>::Load] Loading from D:\Bloxtrup\Settings.json...
2024-12-26T19:47:30Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-26T19:47:30Z [JsonManager<State>::Load] Loading from D:\Bloxtrup\State.json...
2024-12-26T19:47:30Z [JsonManager<State>::Load] Loaded successfully!
2024-12-26T19:47:30Z [FastFlagManager::Load] Loading from D:\Bloxtrup\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-26T19:47:30Z [FastFlagManager::Load] Loaded successfully!
2024-12-26T19:47:34Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-26T19:47:34Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-26T19:47:34Z [Bootstrapper::Run] Running bootstrapper
2024-12-26T19:47:34Z [Bootstrapper::SetStatus] Подключение к Roblox...
2024-12-26T19:47:34Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-26T19:47:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-26T19:47:34Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-26T19:47:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-26T19:47:34Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-26T19:47:34Z [Bootstrapper::Run] Connectivity check finished
2024-12-26T19:47:34Z [Bootstrapper::CheckForUpdates] More than one Bloxstrap instance running, aborting update check
2024-12-26T19:47:34Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-26T19:47:34Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-26T19:47:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-26T19:47:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-26T19:47:34Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-26T19:47:34Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-26T19:47:34Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-26T19:47:34Z [Bootstrapper::SetStatus] Устанавливаем {product}...
2024-12-26T19:47:34Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-12-26T19:47:34Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-12-26T19:47:34Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-26T19:47:34Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-26T19:47:34Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-12-26T19:47:34Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-26T19:47:34Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-12-26T19:47:34Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-12-26T19:47:35Z [Bootstrapper::SetStatus] Настраиваем {product}...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-26T19:47:35Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-12-26T19:47:36Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-26T19:47:36Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-26T19:47:36Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-26T19:47:36Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-12-26T19:47:37Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-26T19:47:37Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-26T19:47:37Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-26T19:47:37Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-26T19:47:38Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'D:\Bloxtrup\Versions\version-b71c150c7c1f40de\ucrtbase.dll' is denied.
   at Bloxstrap.Bootstrapper.<>c.<.ctor>b__25_0(Object _, ScanFailureEventArgs e)
   at ICSharpCode.SharpZipLib.Zip.FastZipEvents.OnFileFailure(String file, Exception e)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractFileEntry(ZipEntry entry, String targetName)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner, Boolean allowParentTraversal)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass37_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
```

**Comment by Kaicvr** [comment]
i cant run roblox why?

**Comment by DingusLing0** [comment]
SAME HAPPENED TO ME

**Comment by bluepilledgreat** [comment]
was roblox already running when this error appeared?

**Comment by ImKeepRim** [comment]
> was roblox already running when this error appeared?

No, but I restarted my pc and bug disappeared
