### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: Acceso denegado.

### ISSUE THREAD

**Issue by Holaxdxdxd123** [bloxstraplabs/bloxstrap#4129]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.3

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/80cf6b70-1e63-4781-8ba8-ea8eba309f3e)
This error started today when I tried to play roblox, I think it's an error for only this version.

### Bloxstrap Log

```text
2024-12-27T18:24:27Z [App::OnStartup] Starting Bloxstrap v2.8.3
2024-12-27T18:24:27Z [App::OnStartup] Compiled Friday, 27 December 2024 at 1:10:17 PM from commit a7e28200a9b14b94474dade8f0e7bb192e413067 (tag/v2.8.3)
2024-12-27T18:24:27Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Temp\scoped_dir2436_1591039562\Bloxstrap-v2.8.3.exe
2024-12-27T18:24:27Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-27T18:24:27Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-27T18:24:27Z [App::OnStartup] Entering main logic
2024-12-27T18:24:27Z [Logger::Initialize] Initializing at D:\Bloxstrap\Logs\Bloxstrap_20241227T182427Z.log
2024-12-27T18:24:27Z [Logger::Initialize] Finished initializing!
2024-12-27T18:24:27Z [JsonManager<Settings>::Load] Loading from D:\Bloxstrap\Settings.json...
2024-12-27T18:24:28Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-27T18:24:28Z [JsonManager<State>::Load] Loading from D:\Bloxstrap\State.json...
2024-12-27T18:24:28Z [JsonManager<State>::Load] Loaded successfully!
2024-12-27T18:24:28Z [FastFlagManager::Load] Loading from D:\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-27T18:24:28Z [FastFlagManager::Load] Loaded successfully!
2024-12-27T18:24:28Z [LaunchHandler::ProcessLaunchArgs] Opening menu
2024-12-27T18:24:30Z [LaunchHandler::ProcessNextAction] Opening Roblox
2024-12-27T18:24:30Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-27T18:24:30Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-27T18:24:31Z [Bootstrapper::Run] Running bootstrapper
2024-12-27T18:24:31Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-27T18:24:31Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-27T18:24:31Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-27T18:24:31Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-27T18:24:32Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-27T18:24:32Z [Bootstrapper::Run] Connectivity check finished
2024-12-27T18:24:32Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T18:24:32Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-27T18:24:32Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=robloxChannel&value=zflag
2024-12-27T18:24:32Z [Deployment::GetInfo] Getting deploy info for channel zflag
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zflag
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer/channel/zflag
2024-12-27T18:24:32Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T18:24:32Z [RegistryKeyEx::SetValueSafe] Writing 'zflag' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-27T18:24:32Z [ApplicationSettings::Fetch.PCClientBootstrapper.zflag] Fetching fast flags
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zflag
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/settings/application/PCClientBootstrapper/bucket/zflag
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/channel/common/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T18:24:32Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/channel/common/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T18:24:32Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-27T18:24:32Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-27T18:24:32Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-27T18:24:33Z [App::FinalizeExceptionHandling] (0x80004005) System.ComponentModel.Win32Exception (5): Acceso denegado.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at Bloxstrap.Bootstrapper.KillRunningRobloxInDirectory(String path)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-27T18:24:33Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
Fixed in v2.8.4
