### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\domin\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\ucrtbase.dll' is denied.

### ISSUE THREAD

**Issue by ezlolhaha** [bloxstraplabs/bloxstrap#4130]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.1

### What problem did you encounter?

ok so i keep downloading my update but it just doesnt let me all it says is loading roblox (roblox doesnt load anyway) and when the "update" comes its back at 2.8.1 its not fair and idk how to fix this

**Comment by OceanEmperor** [comment]
same problem for me, the log is as follows:

2024-12-27T18:52:07Z [App::OnStartup] Starting Bloxstrap v2.8.3
2024-12-27T18:52:07Z [App::OnStartup] Compiled Friday, 27 December 2024 at 6:10:17 PM from commit a7e28200a9b14b94474dade8f0e7bb192e413067 (tag/v2.8.3)
2024-12-27T18:52:07Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-27T18:52:07Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-27T18:52:07Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-27T18:52:07Z [App::OnStartup] Entering main logic
2024-12-27T18:52:07Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241227T185207Z.log
2024-12-27T18:52:07Z [Logger::Initialize] Finished initializing!
2024-12-27T18:52:07Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-27T18:52:07Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-27T18:52:07Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-27T18:52:07Z [JsonManager<State>::Load] Loaded successfully!
2024-12-27T18:52:07Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-27T18:52:07Z [FastFlagManager::Load] Loaded successfully!
2024-12-27T18:52:07Z [LaunchHandler::ProcessLaunchArgs] Opening menu
2024-12-27T18:52:09Z [LaunchHandler::ProcessNextAction] Opening Roblox
2024-12-27T18:52:09Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-27T18:52:09Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-27T18:52:09Z [Bootstrapper::Run] Running bootstrapper
2024-12-27T18:52:09Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-27T18:52:09Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-27T18:52:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-27T18:52:09Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-27T18:52:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-27T18:52:09Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-27T18:52:09Z [Bootstrapper::Run] Connectivity check finished
2024-12-27T18:52:09Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-27T18:52:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T18:52:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T18:52:09Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-27T18:52:10Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-27T18:52:10Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-27T18:52:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T18:52:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T18:52:10Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-27T18:52:10Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T18:52:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T18:52:10Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-12-27T18:52:11Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-12-27T18:52:11Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-12-27T18:52:12Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-12-27T18:52:12Z [Bootstrapper::SetStatus] Configuring {product}...
2024-12-27T18:52:12Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-12-27T18:52:12Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-12-27T18:52:12Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-27T18:52:12Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-27T18:52:12Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-27T18:52:12Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-12-27T18:52:12Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-27T18:52:12Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-12-27T18:52:12Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-27T18:52:12Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-27T18:52:13Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-27T18:52:13Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-27T18:52:13Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-27T18:52:13Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\ucrtbase.dll' is denied.
   at Bloxstrap.Bootstrapper.<>c.<.ctor>b__25_0(Object _, ScanFailureEventArgs e)
   at ICSharpCode.SharpZipLib.Zip.FastZipEvents.OnFileFailure(String file, Exception e)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractFileEntry(ZipEntry entry, String targetName)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner, Boolean allowParentTraversal)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass38_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-27T18:52:13Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-27T18:52:13Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception

**Comment by bluepilledgreat** [comment]
Assumed to be fixed.
