### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: Access is denied.

### ISSUE THREAD

**Issue by DanK4789** [bloxstraplabs/bloxstrap#4141]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.3

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/9c8ce2e9-d080-454a-a4eb-bbd27600ca7b)
Attempted to open the game and this happened.

Attempted to turn on option to reinstall roblox but wouldnt let me toggle
![image](https://github.com/user-attachments/assets/ab46ce1e-8515-458d-82e5-5dd8677074a3)

### Bloxstrap Log

```text
2024-12-27T19:39:34Z [App::OnStartup] Starting Bloxstrap v2.8.3
2024-12-27T19:39:34Z [App::OnStartup] Compiled Friday, 27 December 2024 at 6:10:17 PM from commit a7e28200a9b14b94474dade8f0e7bb192e413067 (tag/v2.8.3)
2024-12-27T19:39:34Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-27T19:39:34Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-27T19:39:34Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-27T19:39:34Z [App::OnStartup] Entering main logic
2024-12-27T19:39:34Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241227T193934Z.log
2024-12-27T19:39:34Z [Logger::Initialize] Finished initializing!
2024-12-27T19:39:34Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-27T19:39:34Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-27T19:39:34Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-27T19:39:34Z [JsonManager<State>::Load] Loaded successfully!
2024-12-27T19:39:34Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-27T19:39:34Z [FastFlagManager::Load] Loaded successfully!
2024-12-27T19:39:34Z [LaunchHandler::ProcessLaunchArgs] Opening menu
2024-12-27T19:39:37Z [LaunchHandler::ProcessNextAction] Opening Roblox
2024-12-27T19:39:37Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-27T19:39:37Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-27T19:39:37Z [Bootstrapper::Run] Running bootstrapper
2024-12-27T19:39:37Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-27T19:39:37Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-27T19:39:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-27T19:39:37Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-27T19:39:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-27T19:39:37Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-27T19:39:37Z [Bootstrapper::Run] Connectivity check finished
2024-12-27T19:39:37Z [Bootstrapper::CheckForUpdates] More than one Bloxstrap instance running, aborting update check
2024-12-27T19:39:37Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-27T19:39:37Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-27T19:39:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T19:39:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T19:39:37Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-27T19:39:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T19:39:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T19:39:37Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-27T19:39:37Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-27T19:39:37Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-27T19:39:37Z [App::FinalizeExceptionHandling] (0x80004005) System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at Bloxstrap.Bootstrapper.KillRunningRobloxInDirectory(String path)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-27T19:39:37Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
Fixed in v2.8.4
