### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: Access is denied.

### ISSUE THREAD

**Issue by MrPlenty711** [bloxstraplabs/bloxstrap#4143]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.3

### What problem did you encounter?

When i try and run bloxstrap, it shows me what i have sent in the screenshot. I dont know how to get around it, i tried to delete bloxstrap and run roblox without it and somehow bloxstrap is still running it and giving me the promp. 
![Screenshot 2024-12-27 105151](https://github.com/user-attachments/assets/eecb257c-7026-453c-a307-0ff430fc7dc8)
[bloxstrap log1.txt](https://github.com/user-attachments/files/18263130/bloxstrap.log1.txt)

### Bloxstrap Log

```text
2024-12-27T19:42:19Z [App::OnStartup] Starting Bloxstrap v2.8.3
2024-12-27T19:42:19Z [App::OnStartup] Compiled Friday, 27 December 2024 at 10:10:17 AM from commit a7e28200a9b14b94474dade8f0e7bb192e413067 (tag/v2.8.3)
2024-12-27T19:42:19Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-27T19:42:19Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-27T19:42:19Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-27T19:42:19Z [LaunchSettings] Identifier 'player' is active with data
2024-12-27T19:42:19Z [LaunchSettings] Invalid argument: roblox://placeID=1537690962/
2024-12-27T19:42:19Z [LaunchSettings::ParsePlayer] Got Roblox launch arguments
2024-12-27T19:42:19Z [App::OnStartup] Entering main logic
2024-12-27T19:42:19Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241227T194219Z.log
2024-12-27T19:42:19Z [Logger::Initialize] Finished initializing!
2024-12-27T19:42:19Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-27T19:42:19Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-27T19:42:19Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-27T19:42:19Z [JsonManager<State>::Load] Loaded successfully!
2024-12-27T19:42:19Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-27T19:42:19Z [FastFlagManager::Load] Loaded successfully!
2024-12-27T19:42:19Z [LaunchHandler::ProcessLaunchArgs] Opening bootstrapper (Player)
2024-12-27T19:42:19Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-27T19:42:19Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-27T19:42:20Z [Bootstrapper::Run] Running bootstrapper
2024-12-27T19:42:20Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-27T19:42:20Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-27T19:42:20Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-27T19:42:20Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-27T19:42:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-27T19:42:21Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-27T19:42:21Z [Bootstrapper::Run] Connectivity check finished
2024-12-27T19:42:21Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-27T19:42:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T19:42:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T19:42:21Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-27T19:42:21Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-27T19:42:21Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-27T19:42:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T19:42:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T19:42:21Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-27T19:42:21Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T19:42:21Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T19:42:21Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-27T19:42:21Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-27T19:42:21Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-27T19:42:21Z [App::FinalizeExceptionHandling] (0x80004005) System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at Bloxstrap.Bootstrapper.KillRunningRobloxInDirectory(String path)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-27T19:42:21Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
Fixed in v2.8.4
