### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: Access is denied.

### ISSUE THREAD

**Issue by Sharkiii27** [bloxstraplabs/bloxstrap#4144]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.3

### What problem did you encounter?

[BUG] System.ComponentModel.Win32Exception: Access is denied.
![image_2024-12-27_215727875](https://github.com/user-attachments/assets/b29c5ea8-8b68-4ae8-9469-3fdf8b3b0f3b)

### Bloxstrap Log

```text
2024-12-27T19:55:51Z [App::OnStartup] Starting Bloxstrap v2.8.3
2024-12-27T19:55:51Z [App::OnStartup] Compiled Friday, 27 December 2024 at 8:10:17 PM from commit a7e28200a9b14b94474dade8f0e7bb192e413067 (tag/v2.8.3)
2024-12-27T19:55:51Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-27T19:55:51Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-27T19:55:51Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-27T19:55:51Z [App::OnStartup] Entering main logic
2024-12-27T19:55:51Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241227T195551Z.log
2024-12-27T19:55:51Z [Logger::Initialize] Finished initializing!
2024-12-27T19:55:51Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-27T19:55:51Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-27T19:55:51Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-27T19:55:51Z [JsonManager<State>::Load] Loaded successfully!
2024-12-27T19:55:51Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-27T19:55:51Z [FastFlagManager::Load] Loaded successfully!
2024-12-27T19:55:51Z [LaunchHandler::ProcessLaunchArgs] Opening menu
2024-12-27T19:55:52Z [LaunchHandler::ProcessNextAction] Opening Roblox
2024-12-27T19:55:52Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-27T19:55:52Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-27T19:55:52Z [Bootstrapper::Run] Running bootstrapper
2024-12-27T19:55:52Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-27T19:55:52Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-27T19:55:52Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-27T19:55:52Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-27T19:55:53Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-27T19:55:53Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-27T19:55:53Z [Bootstrapper::Run] Connectivity check finished
2024-12-27T19:55:53Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-27T19:55:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T19:55:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T19:55:54Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-27T19:55:54Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-27T19:55:54Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-27T19:55:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T19:55:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T19:55:54Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-27T19:55:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T19:55:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T19:55:54Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-27T19:55:54Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-27T19:55:54Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-27T19:55:54Z [App::FinalizeExceptionHandling] (0x80004005) System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at Bloxstrap.Bootstrapper.KillRunningRobloxInDirectory(String path)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-27T19:55:54Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
Fixed in v2.8.4
