### ISSUE TITLE
[BUG] System.IO.IOException: A operação solicitada não pode ser executada em um arquivo com uma seção mapeada pelo usuário aberta. : 'C:\Users\User\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\content\fonts\NotoNaskhArabicUI-Regular.ttf'

### ISSUE THREAD

**Issue by guruguru1205** [bloxstraplabs/bloxstrap#4155]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.4

### What problem did you encounter?

Não estou conseguindo entrar no Bloxtrap eu já instalei e desinstalei várias vezes e não consigo entrar no jogo ou entrar pelo bloxstrap fica sempre travado na parte de "Configurando Roblox..."
![image](https://github.com/user-attachments/assets/6f12612d-f49f-4228-9d16-1231937129a5)

### Bloxstrap Log

```text
2024-12-27T21:45:44Z [App::OnStartup] Starting Bloxstrap v2.8.4
2024-12-27T21:45:44Z [App::OnStartup] Compiled Friday, 27 December 2024 at 5:39:47 PM from commit 534e3bbc0e3a205b7fef9949a1173e9efbaea20e (tag/v2.8.4)
2024-12-27T21:45:44Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.4.exe
2024-12-27T21:45:44Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-27T21:45:44Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-27T21:45:44Z [App::OnStartup] Entering main logic
2024-12-27T21:45:44Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241227T214544Z.log
2024-12-27T21:45:44Z [Logger::Initialize] Finished initializing!
2024-12-27T21:45:44Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241220T204955Z.log'
2024-12-27T21:45:44Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-27T21:45:45Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-27T21:45:45Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-27T21:45:45Z [JsonManager<State>::Load] Loaded successfully!
2024-12-27T21:45:45Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-27T21:45:45Z [FastFlagManager::Load] Loaded successfully!
2024-12-27T21:45:45Z [LaunchHandler::ProcessLaunchArgs] Opening menu
2024-12-27T21:45:48Z [LaunchHandler::ProcessNextAction] Opening Roblox
2024-12-27T21:45:48Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-27T21:45:48Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-27T21:45:49Z [Bootstrapper::Run] Running bootstrapper
2024-12-27T21:45:49Z [Bootstrapper::SetStatus] Conectando-se ao Roblox...
2024-12-27T21:45:49Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-27T21:45:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-27T21:45:49Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-27T21:45:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-27T21:45:49Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-27T21:45:49Z [Bootstrapper::Run] Connectivity check finished
2024-12-27T21:45:49Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-27T21:45:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T21:45:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T21:45:50Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-27T21:45:50Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-27T21:45:50Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-27T21:45:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T21:45:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T21:45:50Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-27T21:45:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T21:45:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T21:45:50Z [Bootstrapper::SetStatus] Instalando {product}...
2024-12-27T21:45:50Z [Bootstrapper::KillRunningRobloxInDirectory] Failed to close process 27464
2024-12-27T21:45:50Z [Bootstrapper::KillRunningRobloxInDirectory] (0x80004005) System.ComponentModel.Win32Exception (5): Acesso negado.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at Bloxstrap.Bootstrapper.KillRunningRobloxInDirectory(String path)
2024-12-27T21:45:55Z [Bootstrapper::UpgradeRoblox] Failed to delete the latest version directory
2024-12-27T21:45:55Z [Bootstrapper::UpgradeRoblox] (0x80070005) System.UnauthorizedAccessException: Access to the path 'CustomFont.ttf' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-27T21:46:07Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-27T21:46:07Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-27T21:46:07Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-27T21:46:07Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::SetStatus] Configurando {product}...
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-12-27T21:46:09Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-12-27T21:46:09Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-27T21:46:09Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-12-27T21:46:12Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-27T21:46:13Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-27T21:46:14Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-27T21:46:14Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-27T21:46:14Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-27T21:46:14Z [App::FinalizeExceptionHandling] (0x800704C8) System.IO.IOException: A operação solicitada não pode ser executada em um arquivo com uma seção mapeada pelo usuário aberta. : '%UserProfile%\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\content\fonts\NotoNaskhArabicUI-Regular.ttf'
   at Bloxstrap.Bootstrapper.<>c.<.ctor>b__25_0(Object _, ScanFailureEventArgs e)
   at ICSharpCode.SharpZipLib.Zip.FastZipEvents.OnFileFailure(String file, Exception e)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractFileEntry(ZipEntry entry, String targetName)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner, Boolean allowParentTraversal)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass38_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-27T21:46:14Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-27T21:46:15Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception

```

**Comment by guruguru1205** [comment]
esqueci de colocar o registro
2024-12-27T21:45:44Z [App::OnStartup] Starting Bloxstrap v2.8.4
2024-12-27T21:45:44Z [App::OnStartup] Compiled Friday, 27 December 2024 at 5:39:47 PM from commit 534e3bbc0e3a205b7fef9949a1173e9efbaea20e (tag/v2.8.4)
2024-12-27T21:45:44Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.4.exe
2024-12-27T21:45:44Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-27T21:45:44Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-27T21:45:44Z [App::OnStartup] Entering main logic
2024-12-27T21:45:44Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241227T214544Z.log
2024-12-27T21:45:44Z [Logger::Initialize] Finished initializing!
2024-12-27T21:45:44Z [Logger::Initialize] Cleaning up old log file 'Bloxstrap_20241220T204955Z.log'
2024-12-27T21:45:44Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-27T21:45:45Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-27T21:45:45Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-27T21:45:45Z [JsonManager<State>::Load] Loaded successfully!
2024-12-27T21:45:45Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-27T21:45:45Z [FastFlagManager::Load] Loaded successfully!
2024-12-27T21:45:45Z [LaunchHandler::ProcessLaunchArgs] Opening menu
2024-12-27T21:45:48Z [LaunchHandler::ProcessNextAction] Opening Roblox
2024-12-27T21:45:48Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-27T21:45:48Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-27T21:45:49Z [Bootstrapper::Run] Running bootstrapper
2024-12-27T21:45:49Z [Bootstrapper::SetStatus] Conectando-se ao Roblox...
2024-12-27T21:45:49Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-27T21:45:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-27T21:45:49Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-27T21:45:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-27T21:45:49Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-27T21:45:49Z [Bootstrapper::Run] Connectivity check finished
2024-12-27T21:45:49Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-27T21:45:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T21:45:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T21:45:50Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-27T21:45:50Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-27T21:45:50Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-27T21:45:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T21:45:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T21:45:50Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-27T21:45:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T21:45:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T21:45:50Z [Bootstrapper::SetStatus] Instalando {product}...
2024-12-27T21:45:50Z [Bootstrapper::KillRunningRobloxInDirectory] Failed to close process 27464
2024-12-27T21:45:50Z [Bootstrapper::KillRunningRobloxInDirectory] (0x80004005) System.ComponentModel.Win32Exception (5): Acesso negado.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at Bloxstrap.Bootstrapper.KillRunningRobloxInDirectory(String path)
2024-12-27T21:45:55Z [Bootstrapper::UpgradeRoblox] Failed to delete the latest version directory
2024-12-27T21:45:55Z [Bootstrapper::UpgradeRoblox] (0x80070005) System.UnauthorizedAccessException: Access to the path 'CustomFont.ttf' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-27T21:46:06Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-12-27T21:46:06Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-27T21:46:07Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-27T21:46:07Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-27T21:46:07Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-27T21:46:07Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-12-27T21:46:07Z [Bootstrapper::SetStatus] Configurando {product}...
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-27T21:46:08Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-12-27T21:46:09Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-12-27T21:46:09Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-27T21:46:09Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-12-27T21:46:10Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-12-27T21:46:12Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-27T21:46:13Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-27T21:46:14Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-27T21:46:14Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-27T21:46:14Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-27T21:46:14Z [App::FinalizeExceptionHandling] (0x800704C8) System.IO.IOException: A operação solicitada não pode ser executada em um arquivo com uma seção mapeada pelo usuário aberta. : '%UserProfile%\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\content\fonts\NotoNaskhArabicUI-Regular.ttf'
   at Bloxstrap.Bootstrapper.<>c.<.ctor>b__25_0(Object _, ScanFailureEventArgs e)
   at ICSharpCode.SharpZipLib.Zip.FastZipEvents.OnFileFailure(String file, Exception e)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractFileEntry(ZipEntry entry, String targetName)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner, Boolean allowParentTraversal)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass38_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-27T21:46:14Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-27T21:46:15Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception

**Comment by Storm-930** [comment]
O problema parece ser com um ficheiro de tipo de letra. Podias tentar executar o Bloxstrap sem esse ficheiro?

**Comment by guruguru1205** [comment]
> O problema parece ser com um arquivo de fonte. Você poderia tentar executar o Bloxstrap sem esse arquivo?

Como que eu posso tirar o arquivo de fonte?

**Comment by bluepilledgreat** [comment]
Assumed to be fixed.
