### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path is denied.

### ISSUE THREAD

**Issue by Mastersyntagmavocals27** [bloxstraplabs/bloxstrap#4156]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v.2.8.4

### What problem did you encounter?

I had the same problem like a hour ago but with the version 2.8.3. Now that i installed the latest version 2.8.4, it still gives me the same Exception error. Again, good work :)

### Bloxstrap Log

```text
2024-12-27T21:38:29Z [App::OnStartup] Starting Bloxstrap v2.8.4
2024-12-27T21:38:29Z [App::OnStartup] Compiled Friday, 27 December 2024 at 8:39:47 PM from commit 534e3bbc0e3a205b7fef9949a1173e9efbaea20e (tag/v2.8.4)
2024-12-27T21:38:29Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.4.exe
2024-12-27T21:38:29Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-27T21:38:29Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-27T21:38:29Z [App::OnStartup] Entering main logic
2024-12-27T21:38:29Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241227T213829Z.log
2024-12-27T21:38:29Z [Logger::Initialize] Finished initializing!
2024-12-27T21:38:29Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-27T21:38:29Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-27T21:38:29Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-27T21:38:29Z [JsonManager<State>::Load] Loaded successfully!
2024-12-27T21:38:29Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-27T21:38:29Z [FastFlagManager::Load] Loaded successfully!
2024-12-27T21:38:29Z [Frontend::ShowMessageBox] The version of Bloxstrap you've launched is different to the version you currently have installed.
Would you like to upgrade your currently installed version?
2024-12-27T21:38:40Z [Installer::HandleUpgrade] Doing upgrade
2024-12-27T21:38:40Z [Installer::HandleUpgrade] Waiting for write permissions to update version
2024-12-27T21:38:45Z [Installer::HandleUpgrade] Failed to update! (Could not get write permissions after 10 tries/5 seconds)
2024-12-27T21:38:45Z [Installer::HandleUpgrade] (0x80070020) System.IO.IOException: The process cannot access the file '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Bloxstrap.Installer.HandleUpgrade()
2024-12-27T21:38:45Z [LaunchHandler::ProcessLaunchArgs] Opening menu
2024-12-27T21:38:53Z [LaunchHandler::ProcessNextAction] Opening Roblox
2024-12-27T21:38:53Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-27T21:38:53Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-27T21:38:53Z [Bootstrapper::Run] Running bootstrapper
2024-12-27T21:38:53Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-27T21:38:53Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-27T21:38:53Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-27T21:38:53Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-27T21:38:54Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-27T21:38:54Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-27T21:38:54Z [Bootstrapper::Run] Connectivity check finished
2024-12-27T21:38:54Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-27T21:38:54Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T21:38:55Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-27T21:38:55Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-27T21:38:55Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-27T21:38:55Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-27T21:38:55Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T21:38:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-27T21:38:56Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-27T21:38:56Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T21:38:56Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-27T21:38:56Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-27T21:39:03Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-27T21:39:03Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-27T21:39:03Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-12-27T21:39:03Z [Bootstrapper::SetStatus] Configuring {product}...
2024-12-27T21:39:04Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-27T21:39:04Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-27T21:39:04Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-27T21:39:04Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-27T21:39:04Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-27T21:39:04Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-27T21:39:04Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-27T21:39:04Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-12-27T21:39:04Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-27T21:39:05Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-12-27T21:39:06Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-12-27T21:39:06Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-12-27T21:39:06Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-27T21:39:06Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-12-27T21:39:06Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-12-27T21:39:06Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-12-27T21:39:06Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-27T21:39:08Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-27T21:39:12Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-27T21:39:12Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-27T21:39:12Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-27T21:39:12Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\ucrtbase.dll' is denied.
   at Bloxstrap.Bootstrapper.<>c.<.ctor>b__25_0(Object _, ScanFailureEventArgs e)
   at ICSharpCode.SharpZipLib.Zip.FastZipEvents.OnFileFailure(String file, Exception e)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractFileEntry(ZipEntry entry, String targetName)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner, Boolean allowParentTraversal)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass38_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-27T21:39:12Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-27T21:39:14Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
```

**Comment by Storm-930** [comment]
And I quote, `The process cannot access the file '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' because it is being used by another process.`
Which other process is using Bloxstrap? Did you try to execute multiple instances at once? Did you open Roblox while Bloxstrap was mid update?

**Comment by Mastersyntagmavocals27** [comment]
When i click to play the game i want, since this problem started, there is always the process of "installing roblox", wich is not usual, and then when i reach "configuring roblox" it simply shows me the error from bloxstrap. I don't remenber seeing anything else apart from this.

**Comment by Loganjayy** [comment]
run as admin maybe?

**Comment by Mastersyntagmavocals27** [comment]
How am i supposed to do that? If you know could you explain it?

**Comment by Loganjayy** [comment]
right click on bloxstrap and click run as admin
