### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\name\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\content\sky\moon.jpg' is denied.

### ISSUE THREAD

**Issue by FentFold69** [bloxstraplabs/bloxstrap#4165]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.4

### What problem did you encounter?

Believe it was during an update to Bloxstrap or Roblox. Just randomly popped up during it and the Bloxstrap which opens roblox says its configuring roblox right now and has been for a while

### Bloxstrap Log

```text
2024-12-28T00:21:01Z [App::OnStartup] Starting Bloxstrap v2.8.4
2024-12-28T00:21:01Z [App::OnStartup] Compiled Saturday, 28 December 2024 at 6:39:47 AM from commit 534e3bbc0e3a205b7fef9949a1173e9efbaea20e (tag/v2.8.4)
2024-12-28T00:21:01Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Temp\Bloxstrap\Updates\Bloxstrap-v2.8.4.exe
2024-12-28T00:21:01Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-28T00:21:01Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-28T00:21:01Z [LaunchSettings] Identifier 'upgrade' is active
2024-12-28T00:21:01Z [LaunchSettings] Identifier 'player' is active with data
2024-12-28T00:21:01Z [LaunchSettings] Invalid argument: roblox-player:1+launchmode:play+gameinfo:EOK2M-SdLjCa2yd3c9f0i570k-nnU4vBRPRoUDWNxpW4QkhQYjoaTCMu9ixxd8zmSBjPbuo9kZpuvUQGvxuVzmAs-zTLt8PHJlW2chqjzzCzYhiZstnCTSwD3GCikSszwAmp8ovVn40926Dvod5K2wr-BWySQzykURP9fqrCmXz2cT5N-hDfkkpfFS7rdoF_awY-lS8mYOtf-61DBUX9N6Zc5h6nrLFqU1jrML-BKl4+launchtime:1735345249969+placelauncherurl:https%3A%2F%2Fwww.roblox.com%2FGame%2FPlaceLauncher.ashx%3Frequest%3DRequestGame%26browserTrackerId%3D1735282664467002%26placeId%3D10082031223%26isPlayTogetherGame%3Dfalse%26referredByPlayerId%3D0%26joinAttemptId%3D4081aab3-5fb1-4e86-9720-84e00b8ec588%26joinAttemptOrigin%3DPlayButton+browsertrackerid:1735282664467002+robloxLocale:en_us+gameLocale:en_us+channel:+LaunchExp:InApp
2024-12-28T00:21:01Z [LaunchSettings::ParsePlayer] Got Roblox launch arguments
2024-12-28T00:21:01Z [App::OnStartup] Entering main logic
2024-12-28T00:21:01Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241228T002101Z.log
2024-12-28T00:21:01Z [Logger::Initialize] Finished initializing!
2024-12-28T00:21:01Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-28T00:21:01Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-28T00:21:01Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-28T00:21:01Z [JsonManager<State>::Load] Loaded successfully!
2024-12-28T00:21:01Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-28T00:21:01Z [FastFlagManager::Load] Loaded successfully!
2024-12-28T00:21:01Z [Installer::HandleUpgrade] Doing upgrade
2024-12-28T00:21:01Z [RegistryKeyEx::SetValueSafe] Writing '2.8.4' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\DisplayVersion
2024-12-28T00:21:01Z [RegistryKeyEx::SetValueSafe] Writing 'Bloxstrap' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\Publisher
2024-12-28T00:21:01Z [RegistryKeyEx::SetValueSafe] Writing 'https://github.com/bloxstraplabs/bloxstrap/wiki' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\HelpLink
2024-12-28T00:21:01Z [RegistryKeyEx::SetValueSafe] Writing 'https://github.com/bloxstraplabs/bloxstrap/issues/new' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\URLInfoAbout
2024-12-28T00:21:01Z [RegistryKeyEx::SetValueSafe] Writing 'https://bloxstraplabs.com' to HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Bloxstrap\URLUpdateInfo
2024-12-28T00:21:01Z [JsonManager<Settings>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-28T00:21:01Z [JsonManager<Settings>::Save] Save complete!
2024-12-28T00:21:01Z [FastFlagManager::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-28T00:21:01Z [FastFlagManager::Save] Save complete!
2024-12-28T00:21:01Z [JsonManager<State>::Save] Saving to %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-28T00:21:01Z [JsonManager<State>::Save] Save complete!
2024-12-28T00:21:01Z [HttpClientLoggingHandler::ProcessRequest] GET https://bloxstraplabs.com/metrics/post?key=installAction&value=upgrade
2024-12-28T00:21:01Z [LaunchHandler::ProcessLaunchArgs] Opening bootstrapper (Player)
2024-12-28T00:21:01Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-28T00:21:01Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-28T00:21:02Z [Bootstrapper::Run] Running bootstrapper
2024-12-28T00:21:02Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-28T00:21:02Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-28T00:21:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-28T00:21:02Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-28T00:21:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://bloxstraplabs.com/metrics/post?key=installAction&value=upgrade
2024-12-28T00:21:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-28T00:21:03Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-28T00:21:03Z [Bootstrapper::Run] Connectivity check finished
2024-12-28T00:21:03Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-28T00:21:03Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-28T00:21:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-28T00:21:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-28T00:21:03Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-28T00:21:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-28T00:21:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-28T00:21:03Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-28T00:21:08Z [Bootstrapper::UpgradeRoblox] Failed to delete the latest version directory
2024-12-28T00:21:08Z [Bootstrapper::UpgradeRoblox] (0x80070005) System.UnauthorizedAccessException: Access to the path 'moon.jpg' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-12-28T00:21:08Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-12-28T00:21:08Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-12-28T00:21:09Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-28T00:21:09Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-12-28T00:21:09Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-12-28T00:21:09Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-12-28T00:21:09Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-12-28T00:21:09Z [Bootstrapper::SetStatus] Configuring {product}...
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-28T00:21:09Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-12-28T00:21:10Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-28T00:21:10Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-28T00:21:10Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-28T00:21:10Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\content\sky\moon.jpg' is denied.
   at Bloxstrap.Bootstrapper.<>c.<.ctor>b__25_0(Object _, ScanFailureEventArgs e)
   at ICSharpCode.SharpZipLib.Zip.FastZipEvents.OnFileFailure(String file, Exception e)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractFileEntry(ZipEntry entry, String targetName)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner, Boolean allowParentTraversal)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass38_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-28T00:21:10Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-28T00:21:10Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://bloxstraplabs.com/metrics/post-exception
```

**Comment by RyanayR-wiggy** [comment]
I got the same issue! I was trying to launch Roblox multiple times but always ended up with "Access to the path 'C:\Users\#####\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\content\sky\moon.jpg' is denied." I'm stuck with using the normal Roblox now... Hope the devs fix this quickly!

**Comment by vended** [comment]
yeah, I got the same issue. but it says:
System.UnauthorizedAccessException: Access to the path 'RobloxPlayerBeta.exe' is denied.
it started today, when I got 2.8.4 update

**Comment by ihatewoodenspoons** [comment]
Similar to #4190, I think. It's an issue with versions v2.8.3-v2.8.5 afaik.

**Comment by bluepilledgreat** [comment]
> Similar to #4190, I think. It's an issue with versions v2.8.3-v2.8.5 afaik.

not similar in any way

**Comment by bluepilledgreat** [comment]
Assumed to be fixed.
