### ISSUE TITLE
[BUG] System.IO.IOException: A operação solicitada não pode ser executada em um arquivo com uma seção mapeada pelo usuário aberta. : 'C:\Users\User\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\content\fonts\NotoNaskhArabicUI-Regular.ttf'

### ISSUE THREAD

**Issue by guruguru1205** [bloxstraplabs/bloxstrap#4167]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.4

### What problem did you encounter?

Não estou conseguindo entrar no jogo, apenas fica na tela "configurando Roblox". Isso está me atrapalhando a jogar. Desinstalei e instalei novamente, mas não estou conseguindo entrar. Se alguém souber como arrumar este problema, me fale por favor.

### Bloxstrap Log

```text
2024-12-28T02:24:42Z [App::OnStartup] Starting Bloxstrap v2.8.4
2024-12-28T02:24:42Z [App::OnStartup] Compiled Friday, 27 December 2024 at 5:39:47 PM from commit 534e3bbc0e3a205b7fef9949a1173e9efbaea20e (tag/v2.8.4)
2024-12-28T02:24:42Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.4.exe
2024-12-28T02:24:42Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-28T02:24:42Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-28T02:24:42Z [App::OnStartup] Entering main logic
2024-12-28T02:24:42Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241228T022442Z.log
2024-12-28T02:24:42Z [Logger::Initialize] Finished initializing!
2024-12-28T02:24:42Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-28T02:24:42Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-28T02:24:42Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-28T02:24:42Z [JsonManager<State>::Load] Loaded successfully!
2024-12-28T02:24:42Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-28T02:24:42Z [FastFlagManager::Load] Loaded successfully!
2024-12-28T02:24:42Z [LaunchHandler::ProcessLaunchArgs] Opening menu
2024-12-28T02:24:45Z [LaunchHandler::ProcessNextAction] Opening Roblox
2024-12-28T02:24:45Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-28T02:24:45Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-28T02:24:45Z [Bootstrapper::Run] Running bootstrapper
2024-12-28T02:24:45Z [Bootstrapper::SetStatus] Conectando-se ao Roblox...
2024-12-28T02:24:45Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-28T02:24:45Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-28T02:24:45Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-28T02:24:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-28T02:24:46Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-28T02:24:46Z [Bootstrapper::Run] Connectivity check finished
2024-12-28T02:24:46Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-28T02:24:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-28T02:24:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-28T02:24:46Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-28T02:24:46Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-28T02:24:46Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-28T02:24:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-28T02:24:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-28T02:24:46Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-28T02:24:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-28T02:24:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-28T02:24:46Z [Bootstrapper::SetStatus] Instalando {product}...
2024-12-28T02:24:46Z [Bootstrapper::KillRunningRobloxInDirectory] Failed to close process 27464
2024-12-28T02:24:46Z [Bootstrapper::KillRunningRobloxInDirectory] (0x80004005) System.ComponentModel.Win32Exception (5): Acesso negado.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at Bloxstrap.Bootstrapper.KillRunningRobloxInDirectory(String path)
2024-12-28T02:24:46Z [Bootstrapper::UpgradeRoblox] Failed to delete the latest version directory
2024-12-28T02:24:46Z [Bootstrapper::UpgradeRoblox] (0x80070005) System.UnauthorizedAccessException: Access to the path 'CustomFont.ttf' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
2024-12-28T02:24:46Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-12-28T02:24:46Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-RobloxApp.zip
2024-12-28T02:24:46Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-RobloxApp.zip
2024-12-28T02:25:02Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (88922844 bytes total)
2024-12-28T02:25:02Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-12-28T02:25:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-avatar.zip
2024-12-28T02:25:02Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-28T02:25:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-avatar.zip
2024-12-28T02:25:02Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (516549 bytes total)
2024-12-28T02:25:02Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-28T02:25:02Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-12-28T02:25:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-configs.zip
2024-12-28T02:25:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-configs.zip
2024-12-28T02:25:02Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (261962 bytes total)
2024-12-28T02:25:02Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-12-28T02:25:02Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-fonts.zip
2024-12-28T02:25:02Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-28T02:25:02Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-fonts.zip
2024-12-28T02:25:02Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-28T02:25:02Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-28T02:25:03Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-12-28T02:25:03Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-28T02:25:03Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-12-28T02:25:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-models.zip
2024-12-28T02:25:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-models.zip
2024-12-28T02:25:03Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (491904 bytes total)
2024-12-28T02:25:03Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-12-28T02:25:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sky.zip
2024-12-28T02:25:03Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-28T02:25:03Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sky.zip
2024-12-28T02:25:04Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-28T02:25:04Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-12-28T02:25:04Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-28T02:25:04Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-12-28T02:25:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sounds.zip
2024-12-28T02:25:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sounds.zip
2024-12-28T02:25:04Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (597244 bytes total)
2024-12-28T02:25:04Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-28T02:25:04Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-12-28T02:25:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-shaders.zip
2024-12-28T02:25:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-shaders.zip
2024-12-28T02:25:04Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-28T02:25:05Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-28T02:25:06Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (8451732 bytes total)
2024-12-28T02:25:06Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-12-28T02:25:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-ssl.zip
2024-12-28T02:25:06Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-28T02:25:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-ssl.zip
2024-12-28T02:25:06Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (135951 bytes total)
2024-12-28T02:25:06Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-28T02:25:06Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-12-28T02:25:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures2.zip
2024-12-28T02:25:06Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-28T02:25:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures2.zip
2024-12-28T02:25:08Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (13549632 bytes total)
2024-12-28T02:25:08Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-28T02:25:08Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-12-28T02:25:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures3.zip
2024-12-28T02:25:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures3.zip
2024-12-28T02:25:08Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-28T02:25:09Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-12-28T02:25:09Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-28T02:25:09Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-12-28T02:25:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-terrain.zip
2024-12-28T02:25:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-terrain.zip
2024-12-28T02:25:09Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-12-28T02:25:09Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-12-28T02:25:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-fonts.zip
2024-12-28T02:25:09Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-28T02:25:09Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-28T02:25:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-fonts.zip
2024-12-28T02:25:09Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-28T02:25:10Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-28T02:25:11Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-12-28T02:25:11Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-12-28T02:25:11Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Downloading...
2024-12-28T02:25:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-dictionaries.zip
2024-12-28T02:25:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-dictionaries.zip
2024-12-28T02:25:12Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Finished downloading! (174486 bytes total)
2024-12-28T02:25:12Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-12-28T02:25:12Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-12-28T02:25:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-places.zip
2024-12-28T02:25:12Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-12-28T02:25:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-places.zip
2024-12-28T02:25:12Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1510546 bytes total)
2024-12-28T02:25:12Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-12-28T02:25:12Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-12-28T02:25:12Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-luapackages.zip
2024-12-28T02:25:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-luapackages.zip
2024-12-28T02:25:12Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-28T02:25:13Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (6622887 bytes total)
2024-12-28T02:25:13Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-12-28T02:25:13Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-12-28T02:25:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-translations.zip
2024-12-28T02:25:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-translations.zip
2024-12-28T02:25:13Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (484208 bytes total)
2024-12-28T02:25:13Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-12-28T02:25:13Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-12-28T02:25:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-models.zip
2024-12-28T02:25:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-models.zip
2024-12-28T02:25:13Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-28T02:25:13Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-28T02:25:15Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (10474300 bytes total)
2024-12-28T02:25:15Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-12-28T02:25:15Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-12-28T02:25:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-textures.zip
2024-12-28T02:25:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-textures.zip
2024-12-28T02:25:16Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-28T02:25:16Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-28T02:25:18Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (17130170 bytes total)
2024-12-28T02:25:18Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-12-28T02:25:18Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-12-28T02:25:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-WebView2.zip
2024-12-28T02:25:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-WebView2.zip
2024-12-28T02:25:18Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-12-28T02:25:18Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-12-28T02:25:18Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-12-28T02:25:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-WebView2RuntimeInstaller.zip
2024-12-28T02:25:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-WebView2RuntimeInstaller.zip
2024-12-28T02:25:18Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-12-28T02:25:18Z [Bootstrapper::DownloadPackage.redist.zip] Downloading...
2024-12-28T02:25:18Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-redist.zip
2024-12-28T02:25:18Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-redist.zip
2024-12-28T02:25:19Z [Bootstrapper::DownloadPackage.redist.zip] Finished downloading! (1372275 bytes total)
2024-12-28T02:25:19Z [Bootstrapper::SetStatus] Configurando {product}...
2024-12-28T02:25:19Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-12-28T02:25:19Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-12-28T02:25:20Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-28T02:25:20Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-28T02:25:20Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-28T02:25:20Z [App::FinalizeExceptionHandling] (0x800704C8) System.IO.IOException: A operação solicitada não pode ser executada em um arquivo com uma seção mapeada pelo usuário aberta. : '%UserProfile%\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\content\fonts\NotoNaskhArabicUI-Regular.ttf'
   at Bloxstrap.Bootstrapper.<>c.<.ctor>b__25_0(Object _, ScanFailureEventArgs e)
   at ICSharpCode.SharpZipLib.Zip.FastZipEvents.OnFileFailure(String file, Exception e)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractFileEntry(ZipEntry entry, String targetName)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner, Boolean allowParentTraversal)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass38_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-28T02:25:20Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-28T02:25:21Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
Assumed to be fixed.
