### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'RobloxPlayerBeta.exe' is denied.

### ISSUE THREAD

**Issue by vended** [bloxstraplabs/bloxstrap#4171]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

2.8.4

### What problem did you encounter?

when its "configuring roblox" state, that error appears every time
i tried to reinstall bloxstrap a few times or install 2.8.2 version, but it didn't solve the problem as well

### Bloxstrap Log

```text
2024-12-28T08:32:02Z [App::OnStartup] Starting Bloxstrap v2.8.4
2024-12-28T08:32:02Z [App::OnStartup] Compiled Friday, 27 December 2024 at 11:39:47 PM from commit 534e3bbc0e3a205b7fef9949a1173e9efbaea20e (tag/v2.8.4)
2024-12-28T08:32:02Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-28T08:32:02Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-28T08:32:02Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-28T08:32:02Z [App::OnStartup] Entering main logic
2024-12-28T08:32:02Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241228T083202Z.log
2024-12-28T08:32:02Z [Logger::Initialize] Finished initializing!
2024-12-28T08:32:02Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-28T08:32:02Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-28T08:32:02Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-28T08:32:02Z [JsonManager<State>::Load] Loaded successfully!
2024-12-28T08:32:02Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-28T08:32:02Z [FastFlagManager::Load] Loaded successfully!
2024-12-28T08:32:02Z [LaunchHandler::ProcessLaunchArgs] Opening menu
2024-12-28T08:32:03Z [LaunchHandler::ProcessNextAction] Opening Roblox
2024-12-28T08:32:03Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-28T08:32:03Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-28T08:32:03Z [Bootstrapper::Run] Running bootstrapper
2024-12-28T08:32:03Z [Bootstrapper::SetStatus] Подключение к Roblox...
2024-12-28T08:32:03Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-28T08:32:03Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-28T08:32:04Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-28T08:32:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-28T08:32:04Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-28T08:32:04Z [Bootstrapper::Run] Connectivity check finished
2024-12-28T08:32:04Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-28T08:32:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-28T08:32:04Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-28T08:32:04Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-28T08:32:04Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-28T08:32:04Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-28T08:32:04Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-28T08:32:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-28T08:32:05Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-28T08:32:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-28T08:32:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-28T08:32:05Z [Bootstrapper::SetStatus] Устанавливаем {product}...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-28T08:32:05Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-12-28T08:32:05Z [Bootstrapper::SetStatus] Настраиваем {product}...
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-28T08:32:06Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-28T08:32:07Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-12-28T08:32:43Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-28T08:32:56Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-28T08:32:56Z [Bootstrapper::UpgradeRoblox] Writing AppSettings.xml...
2024-12-28T08:32:56Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-28T08:32:56Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-28T08:32:56Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'RobloxPlayerBeta.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.CleanupVersionsFolder()
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-28T08:32:56Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-28T08:32:56Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
```

**Comment by prozaccccc** [comment]
hey i found the fix for this, (i think), try going to the file location of bloxstrap (should be something with appdata) and select all, then go to properties and unselect read-only

**Comment by vended** [comment]
oh, k
i will try it, thanks
