### ISSUE TITLE
[BUG] System.IO.IOException: The process cannot access the file 'C:\Users\thoma\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\content\fonts\NotoSansBengaliUI-Regular.ttf' because it is being used by another process.

### ISSUE THREAD

**Issue by mrtommyguy** [bloxstraplabs/bloxstrap#4175]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.5

### What problem did you encounter?

kept saying the font was being used by another process

### Bloxstrap Log

```text
2024-12-28T18:14:58Z [App::OnStartup] Starting Bloxstrap v2.8.5
2024-12-28T18:14:58Z [App::OnStartup] Compiled Saturday, 28 December 2024 at 11:18:01 AM from commit 632b6d4db4dead521468bf14d400577b5898794d (tag/v2.8.5)
2024-12-28T18:14:58Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-28T18:14:58Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-28T18:14:58Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-28T18:14:58Z [LaunchSettings] Identifier 'player' is active with data
2024-12-28T18:14:58Z [LaunchSettings] Invalid argument: roblox-player:1+launchmode:play+gameinfo:NZEfAcxpyJQuCFe06pTGb-jkiZ9r1McLMIPynMoJJI5Ssee1jN5kg_x36CNynMk8fP9jRJsi1dGzpbp6ohi8bnrL6cI30x9DhxiyuPleCOSHtwAqnrvKw7CouPEaCvKmzhrO2Mi0Qj89FsHOk3koscVQ88wZ18-zsSJSfZsGCOLtlGPL1kFqSDltS-FDYs9SOulLIG1DA8iTleLF54FF_VN84l2nXDnlclY7vyvId20+launchtime:1735409697726+placelauncherurl:https%3A%2F%2Fwww.roblox.com%2FGame%2FPlaceLauncher.ashx%3Frequest%3DRequestFollowUser%26browserTrackerId%3D1712620540213001%26userId%3D1471860762%26joinAttemptId%3De9e01af2-673f-4b99-a706-95b78f03ed08%26joinAttemptOrigin%3DJoinUser+browsertrackerid:1712620540213001+robloxLocale:en_us+gameLocale:en_us+channel:+LaunchExp:InApp
2024-12-28T18:14:58Z [LaunchSettings::ParsePlayer] Got Roblox launch arguments
2024-12-28T18:14:58Z [App::OnStartup] Entering main logic
2024-12-28T18:14:58Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241228T181458Z.log
2024-12-28T18:14:58Z [Logger::Initialize] Finished initializing!
2024-12-28T18:14:58Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-28T18:14:58Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-28T18:14:58Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-28T18:14:58Z [JsonManager<State>::Load] Loaded successfully!
2024-12-28T18:14:58Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-28T18:14:58Z [FastFlagManager::Load] Loaded successfully!
2024-12-28T18:14:58Z [LaunchHandler::ProcessLaunchArgs] Opening bootstrapper (Player)
2024-12-28T18:14:58Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-28T18:14:58Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-28T18:14:58Z [Bootstrapper::Run] Running bootstrapper
2024-12-28T18:14:58Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-28T18:14:58Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-28T18:14:58Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-28T18:14:58Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-28T18:14:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-28T18:14:59Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-28T18:14:59Z [Bootstrapper::Run] Connectivity check finished
2024-12-28T18:14:59Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-28T18:14:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-28T18:14:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-28T18:14:59Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-28T18:14:59Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-28T18:14:59Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-28T18:14:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-28T18:14:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-28T18:14:59Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-28T18:14:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-28T18:14:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-28T18:14:59Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-28T18:14:59Z [Bootstrapper::UpgradeRoblox] Failed to delete the latest version directory
2024-12-28T18:14:59Z [Bootstrapper::UpgradeRoblox] (0x80070020) System.IO.IOException: The process cannot access the file 'CustomFont.ttf' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
2024-12-28T18:14:59Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Downloading...
2024-12-28T18:14:59Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-RobloxApp.zip
2024-12-28T18:14:59Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-RobloxApp.zip
2024-12-28T18:15:05Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Finished downloading! (88922844 bytes total)
2024-12-28T18:15:05Z [Bootstrapper::DownloadPackage.content-avatar.zip] Downloading...
2024-12-28T18:15:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-avatar.zip
2024-12-28T18:15:05Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-28T18:15:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-avatar.zip
2024-12-28T18:15:05Z [Bootstrapper::DownloadPackage.content-avatar.zip] Finished downloading! (516549 bytes total)
2024-12-28T18:15:05Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-28T18:15:05Z [Bootstrapper::DownloadPackage.content-configs.zip] Downloading...
2024-12-28T18:15:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-configs.zip
2024-12-28T18:15:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-configs.zip
2024-12-28T18:15:05Z [Bootstrapper::DownloadPackage.content-configs.zip] Finished downloading! (261962 bytes total)
2024-12-28T18:15:05Z [Bootstrapper::DownloadPackage.content-fonts.zip] Downloading...
2024-12-28T18:15:05Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-fonts.zip
2024-12-28T18:15:05Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-28T18:15:05Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-fonts.zip
2024-12-28T18:15:05Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-28T18:15:05Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-28T18:15:06Z [Bootstrapper::DownloadPackage.content-fonts.zip] Finished downloading! (6005683 bytes total)
2024-12-28T18:15:06Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-28T18:15:06Z [Bootstrapper::DownloadPackage.content-models.zip] Downloading...
2024-12-28T18:15:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-models.zip
2024-12-28T18:15:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-models.zip
2024-12-28T18:15:06Z [Bootstrapper::DownloadPackage.content-models.zip] Finished downloading! (491904 bytes total)
2024-12-28T18:15:06Z [Bootstrapper::DownloadPackage.content-sky.zip] Downloading...
2024-12-28T18:15:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sky.zip
2024-12-28T18:15:06Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-28T18:15:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sky.zip
2024-12-28T18:15:06Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-28T18:15:06Z [Bootstrapper::DownloadPackage.content-sky.zip] Finished downloading! (2448711 bytes total)
2024-12-28T18:15:06Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-28T18:15:06Z [Bootstrapper::DownloadPackage.content-sounds.zip] Downloading...
2024-12-28T18:15:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sounds.zip
2024-12-28T18:15:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-sounds.zip
2024-12-28T18:15:06Z [Bootstrapper::DownloadPackage.content-sounds.zip] Finished downloading! (597244 bytes total)
2024-12-28T18:15:06Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-28T18:15:06Z [Bootstrapper::DownloadPackage.shaders.zip] Downloading...
2024-12-28T18:15:06Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-shaders.zip
2024-12-28T18:15:06Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-28T18:15:06Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-shaders.zip
2024-12-28T18:15:06Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-28T18:15:07Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-28T18:15:07Z [Bootstrapper::DownloadPackage.shaders.zip] Finished downloading! (8451732 bytes total)
2024-12-28T18:15:07Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-28T18:15:07Z [Bootstrapper::DownloadPackage.ssl.zip] Downloading...
2024-12-28T18:15:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-ssl.zip
2024-12-28T18:15:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-ssl.zip
2024-12-28T18:15:07Z [Bootstrapper::DownloadPackage.ssl.zip] Finished downloading! (135951 bytes total)
2024-12-28T18:15:07Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-28T18:15:07Z [Bootstrapper::DownloadPackage.content-textures2.zip] Downloading...
2024-12-28T18:15:07Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures2.zip
2024-12-28T18:15:07Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-28T18:15:07Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures2.zip
2024-12-28T18:15:08Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-28T18:15:08Z [Bootstrapper::DownloadPackage.content-textures2.zip] Finished downloading! (13549632 bytes total)
2024-12-28T18:15:08Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-28T18:15:08Z [Bootstrapper::DownloadPackage.content-textures3.zip] Downloading...
2024-12-28T18:15:08Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures3.zip
2024-12-28T18:15:08Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-textures3.zip
2024-12-28T18:15:09Z [Bootstrapper::DownloadPackage.content-textures3.zip] Finished downloading! (3713218 bytes total)
2024-12-28T18:15:09Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-28T18:15:09Z [Bootstrapper::DownloadPackage.content-terrain.zip] Downloading...
2024-12-28T18:15:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-terrain.zip
2024-12-28T18:15:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-terrain.zip
2024-12-28T18:15:09Z [Bootstrapper::DownloadPackage.content-terrain.zip] Finished downloading! (3267 bytes total)
2024-12-28T18:15:09Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Downloading...
2024-12-28T18:15:09Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-fonts.zip
2024-12-28T18:15:09Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-28T18:15:09Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-fonts.zip
2024-12-28T18:15:09Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-28T18:15:09Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-28T18:15:11Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Finished downloading! (13686751 bytes total)
2024-12-28T18:15:11Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Downloading...
2024-12-28T18:15:11Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-12-28T18:15:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-dictionaries.zip
2024-12-28T18:15:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-content-platform-dictionaries.zip
2024-12-28T18:15:11Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Finished downloading! (174486 bytes total)
2024-12-28T18:15:11Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Downloading...
2024-12-28T18:15:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-places.zip
2024-12-28T18:15:11Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-12-28T18:15:11Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-places.zip
2024-12-28T18:15:11Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-12-28T18:15:11Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Finished downloading! (1510546 bytes total)
2024-12-28T18:15:11Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Downloading...
2024-12-28T18:15:11Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-luapackages.zip
2024-12-28T18:15:11Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-12-28T18:15:12Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-luapackages.zip
2024-12-28T18:15:12Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-12-28T18:15:12Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-28T18:15:12Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-28T18:15:13Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Finished downloading! (6622887 bytes total)
2024-12-28T18:15:13Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Downloading...
2024-12-28T18:15:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-translations.zip
2024-12-28T18:15:13Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-12-28T18:15:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-translations.zip
2024-12-28T18:15:13Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Finished downloading! (484208 bytes total)
2024-12-28T18:15:13Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Downloading...
2024-12-28T18:15:13Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-models.zip
2024-12-28T18:15:13Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-12-28T18:15:13Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-models.zip
2024-12-28T18:15:13Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-28T18:15:13Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-28T18:15:14Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Finished downloading! (10474300 bytes total)
2024-12-28T18:15:14Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-12-28T18:15:14Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Downloading...
2024-12-28T18:15:14Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-textures.zip
2024-12-28T18:15:14Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-extracontent-textures.zip
2024-12-28T18:15:14Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-28T18:15:15Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Finished downloading! (17130170 bytes total)
2024-12-28T18:15:15Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-12-28T18:15:15Z [Bootstrapper::DownloadPackage.WebView2.zip] Downloading...
2024-12-28T18:15:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-WebView2.zip
2024-12-28T18:15:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-WebView2.zip
2024-12-28T18:15:15Z [Bootstrapper::DownloadPackage.WebView2.zip] Finished downloading! (81240 bytes total)
2024-12-28T18:15:15Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-12-28T18:15:15Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Downloading...
2024-12-28T18:15:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-WebView2RuntimeInstaller.zip
2024-12-28T18:15:15Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-12-28T18:15:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-WebView2RuntimeInstaller.zip
2024-12-28T18:15:15Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Finished downloading! (1486447 bytes total)
2024-12-28T18:15:15Z [Bootstrapper::DownloadPackage.redist.zip] Downloading...
2024-12-28T18:15:15Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-redist.zip
2024-12-28T18:15:15Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-redist.zip
2024-12-28T18:15:15Z [Bootstrapper::DownloadPackage.redist.zip] Finished downloading! (1372275 bytes total)
2024-12-28T18:15:15Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-12-28T18:15:15Z [Bootstrapper::SetStatus] Configuring {product}...
2024-12-28T18:15:15Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-12-28T18:15:16Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-28T18:15:16Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-28T18:15:16Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-28T18:15:16Z [App::FinalizeExceptionHandling] (0x80070020) System.IO.IOException: The process cannot access the file '%UserProfile%\AppData\Local\Bloxstrap\Versions\version-b71c150c7c1f40de\content\fonts\NotoSansBengaliUI-Regular.ttf' because it is being used by another process.
   at Bloxstrap.Bootstrapper.<>c.<.ctor>b__25_0(Object _, ScanFailureEventArgs e)
   at ICSharpCode.SharpZipLib.Zip.FastZipEvents.OnFileFailure(String file, Exception e)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractFileEntry(ZipEntry entry, String targetName)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractEntry(ZipEntry entry)
   at ICSharpCode.SharpZipLib.Zip.FastZip.ExtractZip(Stream inputStream, String targetDirectory, Overwrite overwrite, ConfirmOverwriteDelegate confirmDelegate, String fileFilter, String directoryFilter, Boolean restoreDateTime, Boolean isStreamOwner, Boolean allowParentTraversal)
   at Bloxstrap.Bootstrapper.ExtractPackage(Package package, List`1 files)
   at Bloxstrap.Bootstrapper.<>c__DisplayClass38_1.<UpgradeRoblox>b__6()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-28T18:15:16Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-28T18:15:16Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
something has NotoSansBengaliUI-Regular.ttf open and is preventing Bloxstrap from finishing installation. are you sure the font file isnt opened anywhere?

**Comment by bluepilledgreat** [comment]
Not latest.
