### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'ArrowCursor.png' is denied.

### ISSUE THREAD

**Issue by splofie** [bloxstraplabs/bloxstrap#4176]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.5

### What problem did you encounter?

Started getting this error around 3 days ago, and it was working perfectly before then. The first time it gave me the error, I could open it when playing a game from the browser, but not when trying to open roblox from the bloxstrap app. completely stopped working after that. reinstalling bloxstrap seemed to do nothing, and removing my mods didn't do anything either.

### Bloxstrap Log

```text
2024-12-28T18:32:56Z [App::OnStartup] Starting Bloxstrap v2.8.5
2024-12-28T18:32:56Z [App::OnStartup] Compiled Saturday, 28 December 2024 at 9:18:01 AM from commit 632b6d4db4dead521468bf14d400577b5898794d (tag/v2.8.5)
2024-12-28T18:32:56Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-28T18:32:56Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-28T18:32:56Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-28T18:32:56Z [App::OnStartup] Entering main logic
2024-12-28T18:32:56Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241228T183256Z.log
2024-12-28T18:32:56Z [Logger::Initialize] Finished initializing!
2024-12-28T18:32:56Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-28T18:32:56Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-28T18:32:56Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-28T18:32:56Z [JsonManager<State>::Load] Loaded successfully!
2024-12-28T18:32:56Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-28T18:32:56Z [FastFlagManager::Load] Loaded successfully!
2024-12-28T18:32:56Z [LaunchHandler::ProcessLaunchArgs] Opening menu
2024-12-28T18:35:49Z [LaunchHandler::ProcessNextAction] Opening Roblox
2024-12-28T18:35:49Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-28T18:35:49Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-28T18:35:49Z [Bootstrapper::Run] Running bootstrapper
2024-12-28T18:35:49Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-28T18:35:49Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-28T18:35:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-28T18:35:49Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-28T18:35:49Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-28T18:35:49Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-28T18:35:49Z [Bootstrapper::Run] Connectivity check finished
2024-12-28T18:35:49Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-28T18:35:49Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-28T18:35:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-28T18:35:50Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-28T18:35:50Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-28T18:35:50Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-28T18:35:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-28T18:35:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-28T18:35:50Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-28T18:35:50Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-28T18:35:50Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-28T18:35:50Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-12-28T18:35:51Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-12-28T18:35:51Z [Bootstrapper::SetStatus] Configuring {product}...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-28T18:35:51Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-12-28T18:35:52Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-28T18:35:52Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-28T18:35:52Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-28T18:35:52Z [Bootstrapper::UpgradeRoblox] Writing AppSettings.xml...
2024-12-28T18:35:52Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-28T18:35:52Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-28T18:35:52Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'ArrowCursor.png' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.CleanupVersionsFolder()
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-28T18:35:52Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-28T18:35:53Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
```

**Comment by splofie** [comment]
deleting an old version folder fixed it for some reason.

**Comment by splofie** [comment]
deleting an old version folder that was empty seemed to fix it for some reason
