### ISSUE TITLE
[BUG] System.ComponentModel.Win32Exception: An error occurred trying to start process 'cmd.exe' with working directory 'C:\Windows\ImmersiveControlPanel'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by xXArfxZyXx** [bloxstraplabs/bloxstrap#4179]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.5

### What problem did you encounter?

![image](https://github.com/user-attachments/assets/0e78fb87-24d3-41ec-b28e-6c058759eb54)

### Bloxstrap Log

```text
2024-12-28T23:37:07Z [App::OnStartup] Starting Bloxstrap v2.8.5
2024-12-28T23:37:07Z [App::OnStartup] Compiled Sunday, 29 December 2024 at 12:18:01 AM from commit 632b6d4db4dead521468bf14d400577b5898794d (tag/v2.8.5)
2024-12-28T23:37:07Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-28T23:37:07Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-28T23:37:07Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-28T23:37:07Z [LaunchSettings] Identifier 'uninstall' is active
2024-12-28T23:37:07Z [App::OnStartup] Entering main logic
2024-12-28T23:37:07Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Temp\Bloxstrap\Logs\Bloxstrap_20241228T233707Z.log
2024-12-28T23:37:07Z [Logger::Initialize] Finished initializing!
2024-12-28T23:37:07Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-28T23:37:07Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-28T23:37:07Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-28T23:37:07Z [JsonManager<State>::Load] Loaded successfully!
2024-12-28T23:37:07Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-28T23:37:07Z [FastFlagManager::Load] Loaded successfully!
2024-12-28T23:37:07Z [LaunchHandler::ProcessLaunchArgs] Opening uninstaller
2024-12-28T23:37:11Z [Protocol::Unregister] Failed to unregister roblox: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Bloxstrap.Utility.WindowsRegistry.Unregister(String key)
2024-12-28T23:37:11Z [Protocol::Unregister] Failed to unregister roblox-player: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Bloxstrap.Utility.WindowsRegistry.Unregister(String key)
2024-12-28T23:37:11Z [Protocol::Unregister] Failed to unregister roblox-studio-auth: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Bloxstrap.Utility.WindowsRegistry.Unregister(String key)
2024-12-28T23:37:11Z [Protocol::Unregister] Failed to unregister Roblox.Place: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Bloxstrap.Utility.WindowsRegistry.Unregister(String key)
2024-12-28T23:37:11Z [Protocol::Unregister] Failed to unregister .rbxl: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Bloxstrap.Utility.WindowsRegistry.Unregister(String key)
2024-12-28T23:37:11Z [Protocol::Unregister] Failed to unregister .rbxlx: System.ArgumentException: Cannot delete a subkey tree because the subkey does not exist.
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey)
   at Bloxstrap.Utility.WindowsRegistry.Unregister(String key)
2024-12-28T23:37:12Z [Installer::DoUninstall] Encountered exception when running cleanup sequence (#8)
2024-12-28T23:37:12Z [Installer::DoUninstall] (0x80070005) System.UnauthorizedAccessException: Access to the path 'Bloxstrap.exe' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at Bloxstrap.Installer.<>c.<DoUninstall>b__19_0()
   at Bloxstrap.Installer.DoUninstall(Boolean keepData)
2024-12-28T23:37:12Z [App::GlobalExceptionHandler] An exception occurred
2024-12-28T23:37:12Z [App::FinalizeExceptionHandling] (0x80004005) System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'cmd.exe' with working directory 'C:\Windows\ImmersiveControlPanel'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Bloxstrap.Installer.DoUninstall(Boolean keepData)
   at Bloxstrap.LaunchHandler.LaunchUninstaller()
   at Bloxstrap.LaunchHandler.ProcessLaunchArgs()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-12-28T23:37:12Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by bluepilledgreat** [comment]
you appear to be lacking cmd.exe (somehow)
to finish uninstallation, go to %localappdata% and delete the `Bloxstrap` folder. the rest of the installation has been completed.
i have no idea what's going on with your system.
