### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\tomat\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by LyoFlex** [bloxstraplabs/bloxstrap#4182]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.1

### What problem did you encounter?

Help pls

### Bloxstrap Log

```text
2024-12-29T00:25:32Z [App::OnStartup] Starting Bloxstrap v2.8.1
2024-12-29T00:25:32Z [App::OnStartup] Compiled Tuesday, 29 October 2024 at 11:35:23 PM from commit 2be2f4d0d275e60eabf2f63ecbbe4e38b2aa0773 (tag/v2.8.1)
2024-12-29T00:25:32Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Temp\scoped_dir5436_691885535\Bloxstrap-v2.8.1 (1).exe
2024-12-29T00:25:32Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-29T00:25:32Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-29T00:25:32Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241229T002532Z.log
2024-12-29T00:25:32Z [Logger::Initialize] Finished initializing!
2024-12-29T00:25:32Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-29T00:25:32Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-29T00:25:32Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-29T00:25:32Z [JsonManager<State>::Load] Loaded successfully!
2024-12-29T00:25:32Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-29T00:25:32Z [FastFlagManager::Load] Loaded successfully!
2024-12-29T00:25:32Z [FastFlagManager::SetValue] Setting of 'FLogNetwork' to '7' is pending
2024-12-29T00:25:32Z [FastFlagManager::SetValue] Setting of 'FFlagHandleAltEnterFullscreenManually' to 'False' is pending
2024-12-29T00:25:32Z [App::GlobalExceptionHandler] An exception occurred
2024-12-29T00:25:32Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.File.OpenRead(String path)
   at Bloxstrap.Utility.MD5Hash.FromFile(String filename)
   at Bloxstrap.Installer.HandleUpgrade()
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-12-29T00:25:32Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
```

**Comment by gamerloch10** [comment]
update to 2.8.5, that may fix this

**Comment by LyoFlex** [comment]
i don't find any blostrap 2.8.5

**Comment by LyoFlex** [comment]
still don't work :C

**Comment by gamerloch10** [comment]
alright sorry I couldn't help :(, wait for someone smarter then me to pop in and help

**Comment by IzeAack** [comment]
Try reinstalling maybe that will work

**Comment by bluepilledgreat** [comment]
your anti-virus is interfering with bloxstrap
