### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'C:\Users\saint\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.

### ISSUE THREAD

**Issue by BBcadum78** [bloxstraplabs/bloxstrap#4186]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [X] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.5

### What problem did you encounter?

Something is blocking my download bloxstrap i cant use it

### Bloxstrap Log

```text
2024-12-29T17:52:33Z [App::OnStartup] Starting Bloxstrap v2.8.5
2024-12-29T17:52:33Z [App::OnStartup] Compiled Saturday, 28 December 2024 at 5:18:01 PM from commit 632b6d4db4dead521468bf14d400577b5898794d (tag/v2.8.5)
2024-12-29T17:52:33Z [App::OnStartup] Loaded from %UserProfile%\Downloads\Bloxstrap-v2.8.5(1).exe
2024-12-29T17:52:33Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-29T17:52:33Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-29T17:52:33Z [App::OnStartup] Entering main logic
2024-12-29T17:52:33Z [App::OnStartup] Copying to install directory
2024-12-29T17:52:33Z [App::GlobalExceptionHandler] An exception occurred
2024-12-29T17:52:33Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path '%UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe' is denied.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName)
   at Bloxstrap.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
2024-12-29T17:52:33Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-29T17:52:33Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
```

**Comment by ihatewoodenspoons** [comment]
Unlikely, but could be related to #4190

There have been multiple issues surrounding file permissions errors, and this is one of them.

**Comment by bluepilledgreat** [comment]
> Unlikely, but could be related to #4190
> 
> There have been multiple issues surrounding file permissions errors, and this is one of them.

these are different errors. dont try to help if you dont know what you're doing.
this error is related to anti-viruses interfering with the bloxstrap process.
