### ISSUE TITLE
[BUG] System.UnauthorizedAccessException: Access to the path 'face.png' is denied.

### ISSUE THREAD

**Issue by DONTDDOSME** [bloxstraplabs/bloxstrap#4194]
### Acknowledgement of preliminary instructions

- [X] I have read the preliminary instructions, and I am certain that my problem has not already been addressed.
- [X] I have thoroughly looked through the available Wiki articles and could not find a solution to my problem.
- [X] I am using the latest version of Bloxstrap.
- [ ] I did not answer truthfully to all the above checkboxes.

### Bloxstrap Version

v2.8.5

### What problem did you encounter?

When i try to start roblox locally, it gives me THIS error.
![image](https://github.com/user-attachments/assets/5cdd806d-3c19-4904-933b-e1e291b9eb86)
This has been happening for me for a lot of time now.

### Bloxstrap Log

```text
2024-12-30T21:21:34Z [App::OnStartup] Starting Bloxstrap v2.8.5
2024-12-30T21:21:34Z [App::OnStartup] Compiled Saturday, 28 December 2024 at 1:18:01 PM from commit 632b6d4db4dead521468bf14d400577b5898794d (tag/v2.8.5)
2024-12-30T21:21:34Z [App::OnStartup] Loaded from %UserProfile%\AppData\Local\Bloxstrap\Bloxstrap.exe
2024-12-30T21:21:34Z [App::OnStartup] Temp path is %UserProfile%\AppData\Local\Temp\Bloxstrap
2024-12-30T21:21:34Z [App::OnStartup] WindowsStartMenu path is %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs
2024-12-30T21:21:34Z [App::OnStartup] Entering main logic
2024-12-30T21:21:34Z [Logger::Initialize] Initializing at %UserProfile%\AppData\Local\Bloxstrap\Logs\Bloxstrap_20241230T212134Z.log
2024-12-30T21:21:34Z [Logger::Initialize] Finished initializing!
2024-12-30T21:21:34Z [JsonManager<Settings>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Settings.json...
2024-12-30T21:21:35Z [JsonManager<Settings>::Load] Loaded successfully!
2024-12-30T21:21:35Z [JsonManager<State>::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\State.json...
2024-12-30T21:21:35Z [JsonManager<State>::Load] Loaded successfully!
2024-12-30T21:21:35Z [FastFlagManager::Load] Loading from %UserProfile%\AppData\Local\Bloxstrap\Modifications\ClientSettings\ClientAppSettings.json...
2024-12-30T21:21:35Z [FastFlagManager::Load] Loaded successfully!
2024-12-30T21:21:35Z [LaunchHandler::ProcessLaunchArgs] Opening menu
2024-12-30T21:21:36Z [LaunchHandler::ProcessNextAction] Opening Roblox
2024-12-30T21:21:36Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper
2024-12-30T21:21:37Z [LaunchHandler::LaunchRoblox] Initializing bootstrapper dialog
2024-12-30T21:21:37Z [Bootstrapper::Run] Running bootstrapper
2024-12-30T21:21:37Z [Bootstrapper::SetStatus] Connecting to Roblox...
2024-12-30T21:21:37Z [Deployment::TestConnection<https://setup.rbxcdn.com>] Connecting...
2024-12-30T21:21:37Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/versionStudio
2024-12-30T21:21:37Z [Deployment::InitializeConnectivity] Testing connectivity...
2024-12-30T21:21:37Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/versionStudio
2024-12-30T21:21:37Z [Deployment::InitializeConnectivity] Got https://setup.rbxcdn.com as the optimal base URL
2024-12-30T21:21:37Z [Bootstrapper::Run] Connectivity check finished
2024-12-30T21:21:38Z [Bootstrapper::CheckForUpdates] Checking for updates...
2024-12-30T21:21:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-30T21:21:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://api.github.com/repos/bloxstraplabs/bloxstrap/releases/latest
2024-12-30T21:21:38Z [Bootstrapper::CheckForUpdates] No updates found
2024-12-30T21:21:38Z [Bootstrapper::GetLatestVersionInfo] Got channel as production
2024-12-30T21:21:38Z [Deployment::GetInfo] Getting deploy info for channel production
2024-12-30T21:21:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-30T21:21:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://clientsettingscdn.roblox.com/v2/client-version/WindowsPlayer
2024-12-30T21:21:38Z [RegistryKeyEx::SetValueSafe] Writing '' to HKEY_CURRENT_USER\SOFTWARE\ROBLOX Corporation\Environments\RobloxPlayer\Channel\www.roblox.com
2024-12-30T21:21:38Z [HttpClientLoggingHandler::ProcessRequest] GET https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-30T21:21:38Z [HttpClientLoggingHandler::ProcessResponse] 200 OK https://setup.rbxcdn.com/version-b71c150c7c1f40de-rbxPkgManifest.txt
2024-12-30T21:21:38Z [Bootstrapper::SetStatus] Installing {product}...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.RobloxApp.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Extracting RobloxApp.zip...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.content-avatar.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Extracting content-avatar.zip...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.content-configs.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Extracting content-configs.zip...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.content-fonts.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Extracting content-fonts.zip...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.content-models.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Extracting content-models.zip...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.content-sky.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.content-sounds.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.shaders.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.ssl.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Finished extracting content-configs.zip
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Extracting content-sky.zip...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.content-textures2.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Finished extracting content-models.zip
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Extracting content-sounds.zip...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.content-textures3.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.content-terrain.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Finished extracting content-sounds.zip
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Finished extracting content-avatar.zip
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Extracting shaders.zip...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.content-platform-fonts.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.content-platform-dictionaries.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.extracontent-places.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Finished extracting content-sky.zip
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Extracting ssl.zip...
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Finished extracting ssl.zip
2024-12-30T21:21:42Z [Bootstrapper::ExtractPackage] Extracting content-textures2.zip...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.extracontent-luapackages.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.extracontent-translations.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.extracontent-models.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.extracontent-textures.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.WebView2.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.WebView2RuntimeInstaller.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::DownloadPackage.redist.zip] Package is already downloaded, skipping...
2024-12-30T21:21:42Z [Bootstrapper::SetStatus] Configuring {product}...
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Finished extracting content-fonts.zip
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Extracting content-textures3.zip...
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Finished extracting content-textures3.zip
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Extracting content-terrain.zip...
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Finished extracting content-terrain.zip
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Extracting content-platform-fonts.zip...
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Finished extracting shaders.zip
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Extracting content-platform-dictionaries.zip...
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-dictionaries.zip
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Extracting extracontent-places.zip...
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-places.zip
2024-12-30T21:21:43Z [Bootstrapper::ExtractPackage] Extracting extracontent-luapackages.zip...
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-luapackages.zip
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Extracting extracontent-translations.zip...
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-translations.zip
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Extracting extracontent-models.zip...
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Finished extracting content-platform-fonts.zip
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Extracting extracontent-textures.zip...
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-models.zip
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Extracting WebView2.zip...
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Extracting redist.zip...
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Finished extracting WebView2.zip
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Finished extracting redist.zip
2024-12-30T21:21:44Z [Bootstrapper::ExtractPackage] Finished extracting RobloxApp.zip
2024-12-30T21:21:46Z [Bootstrapper::ExtractPackage] Finished extracting extracontent-textures.zip
2024-12-30T21:21:49Z [Bootstrapper::ExtractPackage] Finished extracting content-textures2.zip
2024-12-30T21:21:49Z [Bootstrapper::UpgradeRoblox] Writing AppSettings.xml...
2024-12-30T21:21:49Z [LaunchHandler::LaunchRoblox] Bootstrapper task has finished
2024-12-30T21:21:49Z [LaunchHandler::LaunchRoblox] An exception occurred when running the bootstrapper
2024-12-30T21:21:49Z [App::FinalizeExceptionHandling] (0x80070005) System.UnauthorizedAccessException: Access to the path 'face.png' is denied.
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Bloxstrap.Bootstrapper.CleanupVersionsFolder()
   at Bloxstrap.Bootstrapper.UpgradeRoblox()
   at Bloxstrap.Bootstrapper.Run()
   at Bloxstrap.Bootstrapper.Run()
2024-12-30T21:21:49Z [HttpClientLoggingHandler::ProcessRequest] POST https://bloxstraplabs.com/metrics/post-exception
2024-12-30T21:21:50Z [HttpClientLoggingHandler::ProcessResponse] 429 Too Many Requests https://bloxstraplabs.com/metrics/post-exception
2024-12-31T01:20:26Z [App::Terminate] Terminating with exit code 1603 (ERROR_INSTALL_FAILURE)
```

**Comment by DONTDDOSME** [comment]
?

**Comment by bluepilledgreat** [comment]
> ?

why do you think i closed this as completed
